// Peso de animales. El valor es una masa típica aproximada de un adulto de la especie
// indicada, en kilogramos. Varía con sexo, edad y población, por eso la explicación
// nunca pretende describir el peso máximo excepcional de un individuo.
window.ANIMAL_WEIGHT_CARDS = [
  { id: 10001, value: 0.0001, title: "Abeja melífera", detail: "Una obrera adulta pesa aproximadamente 100 miligramos: una fracción diminuta de un gramo." },
  { id: 10002, value: 0.0005, title: "Mariposa monarca", detail: "Un adulto suele rondar medio gramo, pese a poder recorrer miles de kilómetros durante la migración." },
  { id: 10003, value: 0.002, title: "Mantis religiosa", detail: "Una mantis adulta típica pesa alrededor de dos gramos, aunque las hembras suelen superar a los machos." },
  { id: 10004, value: 0.01, title: "Rana arborícola verde", detail: "Su masa típica está cerca de diez gramos; el cuerpo ligero facilita que se agarre a las hojas." },
  { id: 10005, value: 0.025, title: "Ratón doméstico", detail: "Un adulto pesa aproximadamente 25 gramos, menos que una pila pequeña." },
  { id: 10006, value: 0.12, title: "Rata parda", detail: "Una rata adulta suele rondar los 120 gramos, con los machos por lo general más pesados." },
  { id: 10007, value: 0.35, title: "Paloma bravía", detail: "La paloma común de las ciudades suele pesar alrededor de 350 gramos." },
  { id: 10008, value: 0.9, title: "Cobaya", detail: "Una cobaya adulta suele pesar cerca de 900 gramos, aunque el rango depende mucho de su raza." },
  { id: 10009, value: 2.5, title: "Liebre europea", detail: "Una liebre adulta pesa de forma típica unos dos kilos y medio y puede correr a gran velocidad." },
  { id: 10010, value: 4.5, title: "Gato doméstico", detail: "Un gato adulto de tamaño común ronda los cuatro o cinco kilogramos." },
  { id: 10011, value: 6.5, title: "Zorro rojo", detail: "Un zorro rojo adulto pesa aproximadamente seis kilos y medio; las hembras suelen ser algo más ligeras." },
  { id: 10012, value: 11, title: "Castor europeo", detail: "El mayor roedor de Europa suele pesar alrededor de once kilogramos." },
  { id: 10013, value: 18, title: "Lince ibérico", detail: "Un adulto pesa cerca de 18 kilogramos; es mucho más ligero de lo que su aspecto de gran felino sugiere." },
  { id: 10014, value: 30, title: "Gran danés", detail: "Un adulto de esta raza canina grande ronda los 30 kilogramos, aunque algunos ejemplares pesan más." },
  { id: 10015, value: 45, title: "Lobo gris", detail: "Un lobo gris adulto representativo ronda los 45 kilogramos; el tamaño cambia mucho entre poblaciones." },
  { id: 10016, value: 60, title: "Capibara", detail: "El roedor más grande del mundo suele pesar alrededor de 60 kilogramos." },
  { id: 10017, value: 80, title: "Chimpancé común", detail: "Un adulto silvestre ronda los 80 kilogramos en este valor de referencia, con gran diferencia entre sexos." },
  { id: 10018, value: 110, title: "Panda gigante", detail: "Un panda adulto pesa de forma típica algo más de cien kilogramos." },
  { id: 10019, value: 150, title: "Oso negro americano", detail: "Un adulto de tamaño medio ronda los 150 kilogramos, aunque puede variar mucho según estación y alimento." },
  { id: 10020, value: 190, title: "León africano", detail: "Un macho adulto suele rondar los 190 kilogramos, bastante por encima de una hembra." },
  { id: 10021, value: 250, title: "Tigre de Bengala", detail: "Un macho adulto representativo puede pesar alrededor de 250 kilogramos." },
  { id: 10022, value: 350, title: "Cebra de llanura", detail: "Una cebra adulta suele pesar cerca de 350 kilogramos." },
  { id: 10023, value: 500, title: "Caballo doméstico", detail: "Un caballo de silla de tamaño medio ronda los 500 kilogramos." },
  { id: 10024, value: 700, title: "Alce", detail: "Un alce adulto grande puede rondar los 700 kilogramos; es el mayor de los ciervos." },
  { id: 10025, value: 900, title: "Bisonte americano", detail: "Un macho adulto de bisonte puede pesar alrededor de 900 kilogramos." },
  { id: 10026, value: 1200, title: "Jirafa", detail: "Una jirafa adulta suele rondar 1,2 toneladas, sostenidas por sus largas patas y cuello." },
  { id: 10027, value: 1500, title: "Hipopótamo común", detail: "Un hipopótamo adulto pesa aproximadamente una tonelada y media." },
  { id: 10028, value: 2300, title: "Rinoceronte blanco", detail: "Un rinoceronte blanco adulto típico ronda las 2,3 toneladas." },
  { id: 10029, value: 4000, title: "Elefante marino del sur", detail: "Un macho adulto puede rondar cuatro toneladas, más que muchos vehículos pesados." },
  { id: 10030, value: 6000, title: "Elefante africano de sabana", detail: "Un macho adulto grande pesa aproximadamente seis toneladas." },
  { id: 10031, value: 9000, title: "Tiburón ballena", detail: "El pez más grande del mundo puede rondar nueve toneladas; su dieta se basa sobre todo en plancton." },
  { id: 10032, value: 12000, title: "Orca", detail: "Un macho adulto grande puede alcanzar alrededor de doce toneladas." },
  { id: 10033, value: 25000, title: "Ballena gris", detail: "Una ballena gris adulta suele pesar cerca de 25 toneladas." },
  { id: 10034, value: 35000, title: "Ballena jorobada", detail: "Una jorobada adulta ronda las 35 toneladas y es célebre por sus saltos y cantos." },
  { id: 10035, value: 50000, title: "Cachalote", detail: "Un macho adulto puede rondar las 50 toneladas; es el mayor animal con dientes." },
  { id: 10036, value: 70000, title: "Rorcual común", detail: "El segundo animal más grande conocido suele pesar en torno a 70 toneladas." },
  { id: 10037, value: 100000, title: "Ballena franca austral", detail: "Una ballena franca adulta puede rondar las cien toneladas." },
  { id: 10038, value: 150000, title: "Ballena azul", detail: "El animal más pesado conocido puede rondar las 150 toneladas en un adulto grande." }
];
