// Astronomía y exploración espacial. Las cartas anteriores a la era espacial se fechan
// por la publicación o descubrimiento; las modernas, por el lanzamiento, llegada o
// anuncio que se describe. Cada hito tiene un único año dentro del mazo.
window.ASTRONOMY_CARDS = [
  { id: 8001, year: 1543, title: "Copérnico publica su modelo heliocéntrico", detail: "De revolutionibus sitúa a la Tierra entre los planetas que giran alrededor del Sol." },
  { id: 8002, year: 1572, title: "Tycho Brahe observa una nueva estrella", detail: "La supernova visible en Casiopea contradice la idea de un cielo perfecto e inmutable." },
  { id: 8003, year: 1609, title: "Galileo apunta un telescopio al cielo", detail: "Observa relieve en la Luna y una multitud de estrellas invisibles a simple vista." },
  { id: 8004, year: 1610, title: "Descubrimiento de las lunas de Júpiter", detail: "Galileo publica que cuatro cuerpos orbitan Júpiter: no todo gira alrededor de la Tierra." },
  { id: 8005, year: 1619, title: "Kepler formula su tercera ley", detail: "Relaciona matemáticamente el tiempo que tarda un planeta en orbitar con su distancia al Sol." },
  { id: 8006, year: 1655, title: "Huygens descubre Titán", detail: "Christiaan Huygens identifica la mayor luna de Saturno con un telescopio construido por él y su hermano." },
  { id: 8007, year: 1675, title: "Fundación del Observatorio de Greenwich", detail: "Carlos II crea el observatorio para mejorar la astronomía y la navegación marítima." },
  { id: 8008, year: 1687, title: "Newton publica los Principia", detail: "Las leyes del movimiento y la gravitación explican con una misma física la caída de una manzana y las órbitas." },
  { id: 8009, year: 1705, title: "Halley predice el regreso de su cometa", detail: "Edmond Halley calcula que varios cometas observados eran el mismo y anuncia que volverá en 1758." },
  { id: 8010, year: 1781, title: "Descubrimiento de Urano", detail: "William Herschel observa el primer planeta descubierto con telescopio y amplía el tamaño conocido del sistema solar." },
  { id: 8011, year: 1801, title: "Descubrimiento de Ceres", detail: "Giuseppe Piazzi encuentra el primer objeto conocido del cinturón de asteroides, hoy clasificado como planeta enano." },
  { id: 8012, year: 1838, title: "Primera distancia estelar por paralaje", detail: "Friedrich Bessel mide el pequeño desplazamiento aparente de 61 Cygni y calcula por primera vez la distancia a otra estrella." },
  { id: 8013, year: 1846, title: "Descubrimiento de Neptuno", detail: "Johann Galle observa el planeta cerca de la posición que Urbain Le Verrier había calculado por sus efectos gravitatorios." },
  { id: 8014, year: 1868, title: "El helio aparece primero en el Sol", detail: "Una línea desconocida en el espectro solar revela un elemento que todavía no se había encontrado en la Tierra." },
  { id: 8015, year: 1905, title: "Relatividad especial", detail: "Einstein publica una teoría en la que espacio y tiempo dependen del movimiento y la velocidad de la luz es constante." },
  { id: 8016, year: 1915, title: "Relatividad general", detail: "Einstein describe la gravedad como curvatura del espacio-tiempo causada por la materia y la energía." },
  { id: 8017, year: 1923, title: "Andrómeda queda fuera de la Vía Láctea", detail: "Edwin Hubble identifica estrellas cefeidas en Andrómeda y demuestra que el universo contiene otras galaxias." },
  { id: 8018, year: 1929, title: "El universo se expande", detail: "Hubble relaciona la distancia de las galaxias con la velocidad a la que se alejan." },
  { id: 8019, year: 1930, title: "Descubrimiento de Plutón", detail: "Clyde Tombaugh encuentra el objeto buscado más allá de Neptuno en placas fotográficas tomadas desde Arizona." },
  { id: 8020, year: 1933, title: "Zwicky propone la materia oscura", detail: "Al estudiar el cúmulo de Coma, Fritz Zwicky deduce que hay mucha más masa de la que se ve." },
  { id: 8021, year: 1946, title: "Primera fotografía de la Tierra desde el espacio", detail: "Una cámara instalada en un cohete V-2 fotografía el planeta desde más de cien kilómetros de altura." },
  { id: 8022, year: 1957, title: "Sputnik 1", detail: "La Unión Soviética pone en órbita el primer satélite artificial y abre la era espacial." },
  { id: 8023, year: 1959, title: "Luna 2 alcanza la Luna", detail: "La sonda soviética se convierte en el primer objeto humano que llega a otro cuerpo celeste." },
  { id: 8024, year: 1961, title: "Yuri Gagarin orbita la Tierra", detail: "Vostok 1 completa una vuelta al planeta con la primera persona que viaja al espacio." },
  { id: 8025, year: 1963, title: "Valentina Tereshkova viaja al espacio", detail: "La cosmonauta soviética se convierte en la primera mujer en salir de la Tierra." },
  { id: 8026, year: 1965, title: "Primer paseo espacial", detail: "Alexéi Leónov abandona la cápsula Vosjod 2 y flota durante unos doce minutos unido por un cable." },
  { id: 8027, year: 1968, title: "Apollo 8 orbita la Luna", detail: "Tres astronautas son los primeros humanos en abandonar la órbita terrestre y contemplar la salida de la Tierra sobre la Luna." },
  { id: 8028, year: 1969, title: "Primeros pasos humanos en la Luna", detail: "Neil Armstrong y Buzz Aldrin caminan por el mar de la Tranquilidad durante la misión Apollo 11." },
  { id: 8029, year: 1971, title: "Salyut 1, primera estación espacial", detail: "La Unión Soviética coloca en órbita el primer laboratorio diseñado para que una tripulación viva y trabaje en él." },
  { id: 8030, year: 1973, title: "Pioneer 10 sobrevuela Júpiter", detail: "La sonda envía las primeras imágenes cercanas del planeta gigante y atraviesa su intensa radiación." },
  { id: 8031, year: 1976, title: "Viking 1 aterriza en Marte", detail: "La sonda de la NASA transmite las primeras imágenes desde una misión que opera con éxito en la superficie marciana." },
  { id: 8032, year: 1977, title: "Parten las sondas Voyager", detail: "Voyager 1 y 2 comienzan el gran recorrido por los planetas exteriores llevando discos con sonidos e imágenes de la Tierra." },
  { id: 8033, year: 1981, title: "Primer vuelo de un transbordador espacial", detail: "Columbia despega en la misión STS-1 y regresa planeando para ser reutilizado." },
  { id: 8034, year: 1986, title: "Giotto fotografía el núcleo del cometa Halley", detail: "La sonda europea atraviesa la nube de polvo del cometa y observa por primera vez su núcleo de cerca." },
  { id: 8035, year: 1990, title: "Lanzamiento del telescopio Hubble", detail: "El observatorio espacial comienza una misión que transformará la medida de la edad, expansión y composición del universo." },
  { id: 8036, year: 1992, title: "Primeros exoplanetas confirmados", detail: "Aleksander Wolszczan y Dale Frail anuncian planetas alrededor de un púlsar, los primeros fuera del sistema solar confirmados." },
  { id: 8037, year: 1995, title: "Un exoplaneta alrededor de una estrella como el Sol", detail: "Michel Mayor y Didier Queloz descubren 51 Pegasi b, un gigante gaseoso en una órbita de solo cuatro días." },
  { id: 8038, year: 1997, title: "Mars Pathfinder recorre Marte", detail: "El pequeño vehículo Sojourner se convierte en el primer rover que funciona sobre la superficie marciana." },
  { id: 8039, year: 2004, title: "Cassini entra en órbita de Saturno", detail: "Tras siete años de viaje, la misión comienza a estudiar el planeta, sus anillos y sus lunas durante más de una década." },
  { id: 8040, year: 2006, title: "Plutón pasa a ser planeta enano", detail: "La Unión Astronómica Internacional adopta una definición de planeta y reclasifica a Plutón." },
  { id: 8041, year: 2012, title: "Curiosity aterriza en Marte", detail: "Una grúa propulsada deposita el rover en el cráter Gale para investigar si Marte pudo albergar vida microbiana." },
  { id: 8042, year: 2014, title: "Philae aterriza en un cometa", detail: "El módulo de Rosetta toca la superficie de 67P y logra el primer aterrizaje de la historia sobre un cometa." },
  { id: 8043, year: 2015, title: "New Horizons llega a Plutón", detail: "La sonda revela montañas de hielo y una llanura con forma de corazón durante el primer sobrevuelo del planeta enano." },
  { id: 8044, year: 2016, title: "Primera detección directa de ondas gravitacionales", detail: "LIGO anuncia la señal producida por la fusión de dos agujeros negros, un siglo después de la predicción de Einstein." },
  { id: 8045, year: 2019, title: "Primera imagen de un agujero negro", detail: "El Event Horizon Telescope reconstruye la sombra del agujero negro de la galaxia M87 mediante observatorios de todo el mundo." },
  { id: 8046, year: 2021, title: "Lanzamiento del telescopio James Webb", detail: "El mayor observatorio infrarrojo enviado al espacio parte hacia un punto situado a millón y medio de kilómetros de la Tierra." },
  { id: 8047, year: 2022, title: "Primeras imágenes científicas del James Webb", detail: "Nebulosas, galaxias y un campo profundo muestran con detalle la capacidad infrarroja del nuevo telescopio." },
  { id: 8048, year: 2023, title: "OSIRIS-REx trae muestras de Bennu", detail: "Una cápsula devuelve a la Tierra rocas y polvo recogidos directamente de un asteroide." },
  { id: 8049, year: 2024, title: "Chang'e 6 trae muestras de la cara oculta", detail: "La misión china devuelve por primera vez material recogido en el hemisferio de la Luna que nunca mira a la Tierra." }
];
