window.HISTORY_CARDS = [
  { id: 1, year: -218, title: "Desembarco romano en Emporion", detail: "Roma inicia la conquista de Hispania durante la segunda guerra púnica." },
  { id: 2, year: -133, title: "Caída de Numancia", detail: "La ciudad celtíbera cae tras el asedio romano de Escipión Emiliano." },
  { id: 3, year: -19, title: "Fin de las guerras cántabras", detail: "Roma completa la conquista de la península ibérica." },
  { id: 4, year: 212, title: "Ciudadanía romana para los hispanos", detail: "La Constitutio Antoniniana extiende la ciudadanía a los hombres libres del Imperio." },
  { id: 5, year: 409, title: "Llegada de suevos, vándalos y alanos", detail: "Diversos pueblos cruzan los Pirineos y se asientan en Hispania." },
  { id: 6, year: 589, title: "III Concilio de Toledo", detail: "Recaredo adopta el catolicismo como religión del reino visigodo." },
  { id: 7, year: 654, title: "Promulgación del Liber Iudiciorum", detail: "El reino visigodo unifica buena parte de su derecho." },
  { id: 8, year: 711, title: "Batalla de Guadalete", detail: "La derrota visigoda abre paso a la conquista musulmana." },
  { id: 9, year: 722, title: "Batalla de Covadonga", detail: "La tradición sitúa aquí el inicio del reino de Asturias." },
  { id: 10, year: 756, title: "Emirato independiente de Córdoba", detail: "Abderramán I establece un emirato independiente de Damasco." },
  { id: 11, year: 929, title: "Califato de Córdoba", detail: "Abderramán III se proclama califa." },
  { id: 12, year: 1031, title: "Fin del Califato de Córdoba", detail: "Al-Ándalus se fragmenta en reinos de taifas." },
  { id: 13, year: 1085, title: "Conquista cristiana de Toledo", detail: "Alfonso VI incorpora Toledo a sus dominios." },
  { id: 14, year: 1094, title: "El Cid conquista Valencia", detail: "Rodrigo Díaz de Vivar toma la ciudad de Valencia." },
  { id: 15, year: 1212, title: "Batalla de las Navas de Tolosa", detail: "Una coalición cristiana derrota al ejército almohade." },
  { id: 16, year: 1230, title: "Unión definitiva de León y Castilla", detail: "Fernando III reúne ambas coronas." },
  { id: 17, year: 1238, title: "Conquista de Valencia por Jaime I", detail: "Jaime I incorpora Valencia a la Corona de Aragón." },
  { id: 18, year: 1348, title: "La peste negra llega a la península", detail: "La gran epidemia causa una profunda crisis demográfica." },
  { id: 19, year: 1469, title: "Matrimonio de Isabel y Fernando", detail: "Se casan los futuros Reyes Católicos." },
  { id: 20, year: 1478, title: "Creación de la Inquisición española", detail: "Los Reyes Católicos obtienen autorización papal para establecerla." },
  { id: 21, year: 1492, title: "Conquista de Granada", detail: "Boabdil entrega Granada a los Reyes Católicos." },
  { id: 22, year: 1492, title: "Primer viaje de Colón a América", detail: "La expedición castellana llega al continente americano." },
  { id: 23, year: 1492, title: "Expulsión de los judíos", detail: "El Edicto de Granada ordena la salida o conversión de los judíos." },
  { id: 24, year: 1494, title: "Tratado de Tordesillas", detail: "Castilla y Portugal acuerdan el reparto de sus áreas de expansión atlántica." },
  { id: 25, year: 1512, title: "Conquista de Navarra", detail: "Fernando el Católico ocupa la mayor parte del reino navarro." },
  { id: 26, year: 1516, title: "Carlos I accede al trono", detail: "Carlos de Habsburgo se convierte en rey de Castilla y Aragón." },
  { id: 27, year: 1521, title: "Derrota de los comuneros en Villalar", detail: "Las tropas reales vencen a la revuelta de las Comunidades de Castilla." },
  { id: 28, year: 1556, title: "Felipe II inicia su reinado", detail: "Carlos I abdica sus reinos hispánicos en su hijo." },
  { id: 29, year: 1561, title: "Madrid se convierte en sede de la Corte", detail: "Felipe II establece de forma permanente la Corte en Madrid." },
  { id: 30, year: 1571, title: "Batalla de Lepanto", detail: "La Liga Santa derrota a la flota otomana." },
  { id: 31, year: 1580, title: "Unión Ibérica", detail: "Felipe II es reconocido como rey de Portugal." },
  { id: 32, year: 1588, title: "Fracaso de la Armada Invencible", detail: "La Gran Armada no logra invadir Inglaterra." },
  { id: 33, year: 1605, title: "Publicación de la primera parte del Quijote", detail: "Miguel de Cervantes publica la primera parte de su gran novela." },
  { id: 34, year: 1609, title: "Expulsión de los moriscos", detail: "Felipe III decreta su expulsión de los reinos hispánicos." },
  { id: 35, year: 1640, title: "Sublevaciones de Cataluña y Portugal", detail: "La Monarquía Hispánica afronta dos grandes rebeliones simultáneas." },
  { id: 36, year: 1659, title: "Paz de los Pirineos", detail: "España y Francia ponen fin a su guerra y redefinen la frontera." },
  { id: 37, year: 1700, title: "Inicio de la dinastía borbónica", detail: "Felipe V sucede a Carlos II y comienza la guerra de Sucesión." },
  { id: 38, year: 1713, title: "Tratado de Utrecht", detail: "Los acuerdos europeos encaminan el final de la guerra de Sucesión." },
  { id: 39, year: 1716, title: "Decretos de Nueva Planta", detail: "Culmina la reorganización institucional impulsada por Felipe V." },
  { id: 40, year: 1766, title: "Motín de Esquilache", detail: "Una revuelta popular sacude Madrid durante el reinado de Carlos III." },
  { id: 41, year: 1778, title: "Reglamento de libre comercio con América", detail: "Se amplía el comercio entre numerosos puertos peninsulares y americanos." },
  { id: 42, year: 1805, title: "Batalla de Trafalgar", detail: "La flota franco-española es derrotada por Gran Bretaña." },
  { id: 43, year: 1808, title: "Levantamiento del 2 de mayo", detail: "La insurrección de Madrid marca el inicio de la Guerra de la Independencia." },
  { id: 44, year: 1812, title: "Constitución de Cádiz", detail: "Las Cortes promulgan la primera constitución española de larga influencia." },
  { id: 45, year: 1814, title: "Regreso de Fernando VII", detail: "El monarca restaura el absolutismo y anula la Constitución de Cádiz." },
  { id: 46, year: 1820, title: "Inicio del Trienio Liberal", detail: "El pronunciamiento de Riego obliga a restaurar la Constitución de 1812." },
  { id: 47, year: 1833, title: "Primera guerra carlista", detail: "La disputa sucesoria tras la muerte de Fernando VII inicia una guerra civil." },
  { id: 48, year: 1836, title: "Desamortización de Mendizábal", detail: "Se impulsa la venta de bienes eclesiásticos nacionalizados." },
  { id: 49, year: 1868, title: "La Revolución Gloriosa", detail: "Isabel II es destronada y comienza el Sexenio Democrático." },
  { id: 50, year: 1873, title: "Proclamación de la Primera República", detail: "Las Cortes proclaman la República tras la abdicación de Amadeo I." },
  { id: 51, year: 1874, title: "Restauración borbónica", detail: "Alfonso XII inicia la etapa de la Restauración." },
  { id: 52, year: 1898, title: "Desastre del 98", detail: "España pierde Cuba, Puerto Rico y Filipinas tras la guerra con Estados Unidos." },
  { id: 53, year: 1909, title: "Semana Trágica de Barcelona", detail: "Una protesta contra la guerra de Marruecos deriva en una grave revuelta." },
  { id: 54, year: 1923, title: "Dictadura de Primo de Rivera", detail: "El general Miguel Primo de Rivera da un golpe de Estado." },
  { id: 55, year: 1931, title: "Proclamación de la Segunda República", detail: "La salida de Alfonso XIII da paso al nuevo régimen republicano." },
  { id: 56, year: 1936, title: "Inicio de la Guerra Civil", detail: "Una sublevación militar desemboca en una guerra que durará casi tres años." },
  { id: 57, year: 1937, title: "Bombardeo de Guernica", detail: "La aviación alemana e italiana bombardea la villa vasca." },
  { id: 58, year: 1939, title: "Fin de la Guerra Civil", detail: "La victoria franquista da inicio a una larga dictadura." },
  { id: 59, year: 1955, title: "España entra en la ONU", detail: "La Asamblea General aprueba el ingreso de España en Naciones Unidas." },
  { id: 60, year: 1959, title: "Plan de Estabilización", detail: "La economía española inicia una etapa de apertura y fuerte crecimiento." },
  { id: 61, year: 1969, title: "Juan Carlos, sucesor a título de rey", detail: "Las Cortes franquistas lo designan sucesor de Franco." },
  { id: 62, year: 1975, title: "Muerte de Franco y proclamación de Juan Carlos I", detail: "Comienza la transición hacia la democracia." },
  { id: 63, year: 1977, title: "Primeras elecciones democráticas", detail: "España celebra sus primeras elecciones libres desde 1936." },
  { id: 64, year: 1978, title: "Constitución española", detail: "La ciudadanía aprueba en referéndum la actual Constitución." },
  { id: 65, year: 1981, title: "Intento de golpe de Estado del 23-F", detail: "El asalto al Congreso fracasa y se mantiene el orden constitucional." },
  { id: 66, year: 1982, title: "España entra en la OTAN", detail: "España se incorpora a la Alianza Atlántica." },
  { id: 67, year: 1986, title: "Entrada en la Comunidad Económica Europea", detail: "España se integra en el proyecto europeo junto con Portugal." },
  { id: 68, year: 1992, title: "Juegos Olímpicos de Barcelona", detail: "Barcelona acoge los Juegos de la XXV Olimpiada." },
  { id: 69, year: 2002, title: "Entrada en circulación del euro", detail: "Los billetes y monedas de euro sustituyen a la peseta." },
  { id: 70, year: 2004, title: "Atentados del 11-M", detail: "Los atentados en trenes de Madrid causan 193 víctimas mortales." },
  { id: 71, year: 2010, title: "España gana el Mundial de fútbol", detail: "La selección española conquista su primera Copa Mundial." },
  { id: 72, year: 2014, title: "Proclamación de Felipe VI", detail: "Felipe VI es proclamado rey tras la abdicación de Juan Carlos I." }
];
