window.HISTORY_CARDS = [
  { id: 1, year: -218, title: "Desembarco romano en Emporion", detail: "Roma inicia la conquista de Hispania durante la segunda guerra púnica." },
  { id: 2, year: -133, title: "Caída de Numancia", detail: "La ciudad celtíbera cae tras el asedio romano de Escipión Emiliano." },
  { id: 3, year: -19, title: "Fin de las guerras cántabras", detail: "Roma completa la conquista de la península ibérica." },
  { id: 4, year: 212, title: "Ciudadanía romana para los hispanos", detail: "La Constitutio Antoniniana extiende la ciudadanía a los hombres libres del Imperio." },
  { id: 5, year: 409, title: "Llegada de suevos, vándalos y alanos", detail: "Diversos pueblos cruzan los Pirineos y se asientan en Hispania." },
  { id: 6, year: 589, title: "III Concilio de Toledo", detail: "Recaredo adopta el catolicismo como religión del reino visigodo." },
  { id: 7, year: 654, title: "Promulgación del Liber Iudiciorum", detail: "El reino visigodo unifica buena parte de su derecho." },
  { id: 8, year: 711, title: "Batalla de Guadalete", detail: "La derrota visigoda abre paso a la conquista musulmana." },
  { id: 9, year: 722, title: "Batalla de Covadonga (fecha tradicional)", detail: "La historiografía tradicional la fecha en 722 y la considera un hito simbólico del reino de Asturias; su cronología exacta es debatida." },
  { id: 10, year: 756, title: "Emirato independiente de Córdoba", detail: "Abderramán I establece un emirato independiente de Damasco." },
  { id: 11, year: 929, title: "Califato de Córdoba", detail: "Abderramán III se proclama califa." },
  { id: 12, year: 1031, title: "Fin del Califato de Córdoba", detail: "Al-Ándalus se fragmenta en reinos de taifas." },
  { id: 13, year: 1085, title: "Conquista cristiana de Toledo", detail: "Alfonso VI incorpora Toledo a sus dominios." },
  { id: 14, year: 1094, title: "El Cid conquista Valencia", detail: "Rodrigo Díaz de Vivar toma la ciudad de Valencia." },
  { id: 15, year: 1212, title: "Batalla de las Navas de Tolosa", detail: "Una coalición cristiana derrota al ejército almohade." },
  { id: 16, year: 1230, title: "Unión definitiva de León y Castilla", detail: "Fernando III reúne ambas coronas." },
  { id: 17, year: 1238, title: "Conquista de Valencia por Jaime I", detail: "Jaime I incorpora Valencia a la Corona de Aragón." },
  { id: 18, year: 1348, title: "La peste negra llega a la península", detail: "La gran epidemia causa una profunda crisis demográfica." },
  { id: 19, year: 1469, title: "Matrimonio de Isabel y Fernando", detail: "Se casan los futuros Reyes Católicos." },
  { id: 20, year: 1478, title: "Creación de la Inquisición española", detail: "Los Reyes Católicos obtienen autorización papal para establecerla." },
  { id: 21, year: 1492, title: "Conquista de Granada", detail: "Boabdil entrega Granada a los Reyes Católicos." },
  { id: 22, year: 1492, title: "Primer viaje de Colón a América", detail: "La expedición castellana llega al continente americano." },
  { id: 23, year: 1492, title: "Expulsión de los judíos", detail: "El Edicto de Granada ordena la salida o conversión de los judíos." },
  { id: 24, year: 1494, title: "Tratado de Tordesillas", detail: "Castilla y Portugal acuerdan el reparto de sus áreas de expansión atlántica." },
  { id: 25, year: 1512, title: "Conquista de Navarra", detail: "Fernando el Católico ocupa la mayor parte del reino navarro." },
  { id: 26, year: 1516, title: "Carlos I accede al trono", detail: "Carlos de Habsburgo se convierte en rey de Castilla y Aragón." },
  { id: 27, year: 1521, title: "Derrota de los comuneros en Villalar", detail: "Las tropas reales vencen a la revuelta de las Comunidades de Castilla." },
  { id: 28, year: 1556, title: "Felipe II inicia su reinado", detail: "Carlos I abdica sus reinos hispánicos en su hijo." },
  { id: 29, year: 1561, title: "Madrid se convierte en sede de la Corte", detail: "Felipe II establece de forma permanente la Corte en Madrid." },
  { id: 30, year: 1571, title: "Batalla de Lepanto", detail: "La Liga Santa derrota a la flota otomana." },
  { id: 31, year: 1580, title: "Unión Ibérica", detail: "Felipe II es reconocido como rey de Portugal." },
  { id: 32, year: 1588, title: "Fracaso de la Armada Invencible", detail: "La Gran Armada no logra invadir Inglaterra." },
  { id: 33, year: 1605, title: "Publicación de la primera parte del Quijote", detail: "Miguel de Cervantes publica la primera parte de su gran novela." },
  { id: 34, year: 1609, title: "Expulsión de los moriscos", detail: "Felipe III decreta su expulsión de los reinos hispánicos." },
  { id: 35, year: 1640, title: "Sublevaciones de Cataluña y Portugal", detail: "La Monarquía Hispánica afronta dos grandes rebeliones simultáneas." },
  { id: 36, year: 1659, title: "Paz de los Pirineos", detail: "España y Francia ponen fin a su guerra y redefinen la frontera." },
  { id: 37, year: 1700, title: "Inicio de la dinastía borbónica", detail: "Felipe V sucede a Carlos II; la crisis sucesoria desembocará en la guerra de Sucesión desde 1701." },
  { id: 38, year: 1713, title: "Tratado de Utrecht", detail: "Los acuerdos europeos encaminan el final de la guerra de Sucesión." },
  { id: 39, year: 1716, title: "Decretos de Nueva Planta", detail: "Culmina la reorganización institucional impulsada por Felipe V." },
  { id: 40, year: 1766, title: "Motín de Esquilache", detail: "Una revuelta popular sacude Madrid durante el reinado de Carlos III." },
  { id: 41, year: 1778, title: "Reglamento de libre comercio con América", detail: "Se amplía el comercio entre numerosos puertos peninsulares y americanos." },
  { id: 42, year: 1805, title: "Batalla de Trafalgar", detail: "La flota franco-española es derrotada por Gran Bretaña." },
  { id: 43, year: 1808, title: "Levantamiento del 2 de mayo", detail: "La insurrección de Madrid marca el inicio de la Guerra de la Independencia." },
  { id: 44, year: 1812, title: "Constitución de Cádiz", detail: "Las Cortes promulgan la primera constitución española de larga influencia." },
  { id: 45, year: 1814, title: "Regreso de Fernando VII", detail: "El monarca restaura el absolutismo y anula la Constitución de Cádiz." },
  { id: 46, year: 1820, title: "Inicio del Trienio Liberal", detail: "El pronunciamiento de Riego obliga a restaurar la Constitución de 1812." },
  { id: 47, year: 1833, title: "Primera guerra carlista", detail: "La disputa sucesoria tras la muerte de Fernando VII inicia una guerra civil." },
  { id: 48, year: 1836, title: "Desamortización de Mendizábal", detail: "Se impulsa la venta de bienes eclesiásticos nacionalizados." },
  { id: 49, year: 1868, title: "La Revolución Gloriosa", detail: "Isabel II es destronada y comienza el Sexenio Democrático." },
  { id: 50, year: 1873, title: "Proclamación de la Primera República", detail: "Las Cortes proclaman la República tras la abdicación de Amadeo I." },
  { id: 51, year: 1874, title: "Restauración borbónica", detail: "Alfonso XII inicia la etapa de la Restauración." },
  { id: 52, year: 1898, title: "Desastre del 98", detail: "España pierde Cuba, Puerto Rico y Filipinas tras la guerra con Estados Unidos." },
  { id: 53, year: 1909, title: "Semana Trágica de Barcelona", detail: "Una protesta contra la guerra de Marruecos deriva en una grave revuelta." },
  { id: 54, year: 1923, title: "Dictadura de Primo de Rivera", detail: "El general Miguel Primo de Rivera da un golpe de Estado." },
  { id: 55, year: 1931, title: "Proclamación de la Segunda República", detail: "La salida de Alfonso XIII da paso al nuevo régimen republicano." },
  { id: 56, year: 1936, title: "Inicio de la Guerra Civil", detail: "Una sublevación militar desemboca en una guerra que durará casi tres años." },
  { id: 57, year: 1937, title: "Bombardeo de Guernica", detail: "La aviación alemana e italiana bombardea la villa vasca." },
  { id: 58, year: 1939, title: "Fin de la Guerra Civil", detail: "La victoria franquista da inicio a una larga dictadura." },
  { id: 59, year: 1955, title: "España entra en la ONU", detail: "La Asamblea General aprueba el ingreso de España en Naciones Unidas." },
  { id: 60, year: 1959, title: "Plan de Estabilización", detail: "La economía española inicia una etapa de apertura y fuerte crecimiento." },
  { id: 61, year: 1969, title: "Juan Carlos, sucesor a título de rey", detail: "Las Cortes franquistas lo designan sucesor de Franco." },
  { id: 62, year: 1975, title: "Muerte de Franco y proclamación de Juan Carlos I", detail: "Comienza la transición hacia la democracia." },
  { id: 63, year: 1977, title: "Primeras elecciones democráticas", detail: "España celebra sus primeras elecciones libres desde 1936." },
  { id: 64, year: 1978, title: "Constitución española", detail: "La ciudadanía aprueba en referéndum la actual Constitución." },
  { id: 65, year: 1981, title: "Intento de golpe de Estado del 23-F", detail: "El asalto al Congreso fracasa y se mantiene el orden constitucional." },
  { id: 66, year: 1982, title: "España entra en la OTAN", detail: "España se incorpora a la Alianza Atlántica." },
  { id: 67, year: 1986, title: "Entrada en la Comunidad Económica Europea", detail: "España se integra en el proyecto europeo junto con Portugal." },
  { id: 68, year: 1992, title: "Juegos Olímpicos de Barcelona", detail: "Barcelona acoge los Juegos de la XXV Olimpiada." },
  { id: 69, year: 2002, title: "Entrada en circulación del euro", detail: "Los billetes y monedas de euro sustituyen a la peseta." },
  { id: 70, year: 2004, title: "Atentados del 11-M", detail: "Los atentados en trenes de Madrid causan 193 víctimas mortales." },
  { id: 71, year: 2010, title: "España gana el Mundial de fútbol", detail: "La selección española conquista su primera Copa Mundial." },
  { id: 72, year: 2014, title: "Proclamación de Felipe VI", detail: "Felipe VI es proclamado rey tras la abdicación de Juan Carlos I." },
  { id: 73, year: -575, title: "Fundación griega de Emporion", detail: "Colonos focenses procedentes de Massalia fundan Emporion, la actual Empúries, hacia el 575 a. C." },
  { id: 74, year: -237, title: "Amílcar Barca desembarca en Gadir", detail: "El general cartaginés inicia la expansión bárcida por la península ibérica." },
  { id: 75, year: -226, title: "Tratado del Ebro", detail: "Roma y Asdrúbal acuerdan situar en el río Ebro el límite de la expansión cartaginesa." },
  { id: 76, year: -209, title: "Roma conquista Carthago Nova", detail: "Publio Cornelio Escipión toma la principal base cartaginesa de la península." },
  { id: 77, year: -197, title: "Hispania Citerior y Ulterior", detail: "Roma organiza sus dominios peninsulares en dos provincias." },
  { id: 78, year: -139, title: "Asesinato de Viriato", detail: "El caudillo lusitano muere durante la resistencia contra Roma." },
  { id: 79, year: -29, title: "Comienzan las guerras cántabras", detail: "Roma inicia la campaña final contra cántabros y astures, concluida en el 19 a. C." },
  { id: 80, year: -25, title: "Fundación tradicional de Emerita Augusta", detail: "La fundación de la colonia, futura capital de Lusitania, suele fecharse en el 25 a. C.; existe una propuesta alternativa que la sitúa en el 19 a. C." },
  { id: 81, year: 98, title: "Trajano se convierte en emperador", detail: "El emperador nacido en Itálica inaugura una etapa de máxima expansión romana." },
  { id: 82, year: 117, title: "Adriano sucede a Trajano", detail: "Otro emperador vinculado a Itálica accede al trono de Roma." },
  { id: 83, year: 507, title: "Batalla de Vouillé", detail: "La derrota ante los francos desplaza el centro del reino visigodo hacia Hispania." },
  { id: 84, year: 552, title: "Comienza la provincia bizantina de Spania", detail: "El Imperio romano de Oriente ocupa territorios del sur y sureste peninsular." },
  { id: 85, year: 624, title: "Fin de la presencia bizantina en Hispania", detail: "El rey visigodo Suintila culmina la expulsión de los bizantinos de la península." },
  { id: 86, year: 785, title: "Comienza la gran mezquita de Córdoba", detail: "Abderramán I inicia la construcción del gran edificio religioso cordobés." },
  { id: 87, year: 801, title: "Los francos conquistan Barcelona", detail: "El ejército de Luis el Piadoso incorpora Barcelona a la Marca Hispánica." },
  { id: 88, year: 824, title: "Origen tradicional del reino de Pamplona", detail: "Íñigo Arista aparece asociado al nacimiento de un poder pamplonés independiente; la fecha es convencional." },
  { id: 89, year: 910, title: "Nacimiento del reino de León", detail: "Tras la muerte de Alfonso III, García I establece en León el centro de su reino." },
  { id: 90, year: 997, title: "Almanzor saquea Santiago de Compostela", detail: "La campaña de Almanzor alcanza la ciudad compostelana." },
  { id: 91, year: 1002, title: "Muerte de Almanzor", detail: "La desaparición del caudillo andalusí precede a la crisis del Califato de Córdoba." },
  { id: 92, year: 1035, title: "Ramiro I y el reino de Aragón", detail: "Ramiro I recibe Aragón y es considerado tradicionalmente su primer rey." },
  { id: 93, year: 1118, title: "Conquista cristiana de Zaragoza", detail: "Alfonso I el Batallador incorpora Zaragoza al reino de Aragón." },
  { id: 94, year: 1137, title: "Unión dinástica de Aragón y Barcelona", detail: "El acuerdo matrimonial entre Petronila y Ramón Berenguer IV sienta las bases de la Corona de Aragón." },
  { id: 95, year: 1188, title: "Cortes de León", detail: "Alfonso IX convoca una curia con representantes de las ciudades, considerada el testimonio parlamentario más antiguo conservado en Europa." },
  { id: 96, year: 1229, title: "Jaime I conquista Mallorca", detail: "La toma de Madina Mayurqa inicia la incorporación de Mallorca a la Corona de Aragón." },
  { id: 97, year: 1248, title: "Fernando III conquista Sevilla", detail: "La ciudad se incorpora a la Corona de Castilla tras un largo asedio." },
  { id: 98, year: 1252, title: "Comienza el reinado de Alfonso X", detail: "Alfonso X el Sabio impulsa una importante obra jurídica, científica y cultural." },
  { id: 99, year: 1282, title: "Vísperas Sicilianas", detail: "La revuelta siciliana facilita la expansión mediterránea de la Corona de Aragón." },
  { id: 100, year: 1302, title: "Paz de Caltabellotta", detail: "El acuerdo consolida la presencia de la dinastía aragonesa en Sicilia." },
  { id: 101, year: 1340, title: "Batalla del Salado", detail: "Castilla y Portugal derrotan a benimerines y granadinos cerca de Tarifa." },
  { id: 102, year: 1391, title: "Asaltos contra las juderías", detail: "Una ola de violencia antijudía se extiende desde Sevilla a numerosas ciudades peninsulares." },
  { id: 103, year: 1412, title: "Compromiso de Caspe", detail: "Nueve compromisarios eligen a Fernando de Antequera como rey de Aragón." },
  { id: 104, year: 1442, title: "Alfonso V conquista Nápoles", detail: "El monarca de la Corona de Aragón entra en Nápoles y establece allí su corte." },
  { id: 105, year: 1474, title: "Isabel I es proclamada reina de Castilla", detail: "Isabel se proclama reina en Segovia tras la muerte de Enrique IV." },
  { id: 106, year: 1479, title: "Unión dinástica de Castilla y Aragón", detail: "Fernando hereda la Corona de Aragón; ambas coronas comparten monarcas, pero conservan leyes e instituciones propias." },
  { id: 107, year: 1496, title: "Finaliza la conquista de Canarias", detail: "La derrota de la resistencia guanche en Tenerife culmina la conquista castellana del archipiélago." },
  { id: 108, year: 1499, title: "Primera edición conocida de La Celestina", detail: "La edición más antigua conocida de la obra atribuida a Fernando de Rojas se fecha tradicionalmente hacia 1499." },
  { id: 109, year: 1503, title: "Creación de la Casa de Contratación", detail: "La Corona establece en Sevilla el organismo que regula el tráfico con América." },
  { id: 110, year: 1513, title: "Balboa alcanza el océano Pacífico", detail: "Vasco Núñez de Balboa cruza el istmo de Panamá y avista el llamado Mar del Sur." },
  { id: 111, year: 1519, title: "Parte la expedición de Magallanes", detail: "La Armada de la Especiería zarpa de Sevilla y Sanlúcar para buscar una ruta occidental a las Molucas." },
  { id: 112, year: 1522, title: "Elcano completa la primera vuelta al mundo", detail: "La nao Victoria regresa bajo el mando de Juan Sebastián Elcano y culmina la primera circunnavegación documentada." },
  { id: 113, year: 1525, title: "Batalla de Pavía", detail: "Las tropas de Carlos V derrotan y capturan al rey francés Francisco I." },
  { id: 114, year: 1535, title: "Creación del virreinato de Nueva España", detail: "La Monarquía organiza gran parte de sus territorios americanos en un virreinato." },
  { id: 115, year: 1547, title: "Nacimiento de Miguel de Cervantes", detail: "Nace en Alcalá de Henares el futuro autor del Quijote." },
  { id: 116, year: 1557, title: "Batalla de San Quintín", detail: "El ejército de Felipe II obtiene una importante victoria sobre Francia." },
  { id: 117, year: 1563, title: "Comienza la construcción de El Escorial", detail: "Se coloca la primera piedra del monasterio y complejo real de San Lorenzo." },
  { id: 118, year: 1568, title: "Rebelión de las Alpujarras", detail: "La población morisca del reino de Granada se subleva contra la política de la Monarquía." },
  { id: 119, year: 1581, title: "Cortes de Tomar", detail: "Felipe II es reconocido como rey de Portugal, manteniendo el reino sus propias instituciones." },
  { id: 120, year: 1598, title: "Felipe III inicia su reinado", detail: "La muerte de Felipe II da paso al gobierno de Felipe III y sus validos." },
  { id: 121, year: 1618, title: "Comienza la guerra de los Treinta Años", detail: "La Monarquía Hispánica interviene en el gran conflicto europeo junto a los Habsburgo imperiales." },
  { id: 122, year: 1621, title: "Felipe IV accede al trono", detail: "Comienza un reinado marcado por el gobierno del conde-duque de Olivares y las guerras europeas." },
  { id: 123, year: 1643, title: "Batalla de Rocroi", detail: "El ejército francés derrota a fuerzas de la Monarquía Hispánica en Flandes." },
  { id: 124, year: 1648, title: "Paz de Münster", detail: "La Monarquía Hispánica reconoce formalmente la independencia de las Provincias Unidas." },
  { id: 125, year: 1665, title: "Carlos II accede al trono", detail: "Comienza el último reinado de la Casa de Austria en España." },
  { id: 126, year: 1668, title: "España reconoce la independencia de Portugal", detail: "El Tratado de Lisboa pone fin a la guerra de Restauración portuguesa." },
  { id: 127, year: 1680, title: "Recopilación de Leyes de Indias", detail: "Se publica una gran compilación de normas para los territorios americanos de la Monarquía." },
  { id: 128, year: 1704, title: "Una flota anglo-neerlandesa toma Gibraltar", detail: "Gibraltar es ocupado durante la guerra de Sucesión española." },
  { id: 129, year: 1707, title: "Batalla de Almansa", detail: "La victoria borbónica resulta decisiva para el control de los reinos de Valencia y Aragón." },
  { id: 130, year: 1713, title: "Fundación de la Real Academia Española", detail: "La primera reunión formal de la Academia se celebra en 1713; recibirá protección real en 1714." },
  { id: 131, year: 1738, title: "Real Academia de la Historia", detail: "Felipe V convierte en Real Academia la reunión de estudiosos iniciada en 1735." },
  { id: 132, year: 1759, title: "Carlos III inicia su reinado", detail: "El monarca impulsa reformas asociadas al despotismo ilustrado." },
  { id: 133, year: 1767, title: "Expulsión de los jesuitas", detail: "Carlos III ordena expulsar a la Compañía de Jesús de los dominios españoles." },
  { id: 134, year: 1782, title: "Fundación del Banco de San Carlos", detail: "Se crea el antecedente institucional del actual Banco de España." },
  { id: 135, year: 1785, title: "Carlos III adopta la bandera rojigualda naval", detail: "Un real decreto establece el diseño rojo y amarillo para la Armada; su uso como bandera nacional será posterior." },
  { id: 136, year: 1788, title: "Carlos IV accede al trono", detail: "La muerte de Carlos III da comienzo al reinado de Carlos IV." },
  { id: 137, year: 1793, title: "Guerra de la Convención", detail: "España entra en guerra contra la Francia revolucionaria." },
  { id: 138, year: 1801, title: "Guerra de las Naranjas", detail: "España, aliada con Francia, libra una breve guerra contra Portugal." },
  { id: 139, year: 1807, title: "Tratado de Fontainebleau", detail: "España permite el paso de tropas francesas para invadir Portugal." },
  { id: 140, year: 1808, title: "Abdicaciones de Bayona", detail: "Carlos IV y Fernando VII ceden sus derechos a Napoleón, que sitúa a José Bonaparte en el trono." },
  { id: 141, year: 1810, title: "Se reúnen las Cortes de Cádiz", detail: "Las Cortes inauguran sus sesiones en la Isla de León durante la ocupación napoleónica." },
  { id: 142, year: 1813, title: "Batalla de Vitoria", detail: "La derrota francesa acelera el final de la Guerra de la Independencia en la península." },
  { id: 143, year: 1819, title: "Abre el Museo del Prado", detail: "El Real Museo de Pinturas abre sus puertas al público en Madrid." },
  { id: 144, year: 1823, title: "Los Cien Mil Hijos de San Luis", detail: "Un ejército francés invade España y restaura el poder absoluto de Fernando VII." },
  { id: 145, year: 1834, title: "Estatuto Real", detail: "María Cristina promulga una carta otorgada que establece unas Cortes bicamerales." },
  { id: 146, year: 1837, title: "Constitución de 1837", detail: "Las Cortes aprueban una constitución liberal durante la regencia de María Cristina." },
  { id: 147, year: 1839, title: "Abrazo de Vergara", detail: "El acuerdo entre Espartero y Maroto encamina el final de la primera guerra carlista en el norte." },
  { id: 148, year: 1844, title: "Creación de la Guardia Civil", detail: "Un real decreto crea un cuerpo de seguridad de ámbito estatal." },
  { id: 149, year: 1845, title: "Constitución de 1845", detail: "La mayoría moderada aprueba una nueva constitución durante el reinado de Isabel II." },
  { id: 150, year: 1848, title: "Primer ferrocarril de la España peninsular", detail: "Se inaugura la línea Barcelona–Mataró; en Cuba ya funcionaba una línea desde 1837." },
  { id: 151, year: 1855, title: "Desamortización de Madoz", detail: "La Ley General de Desamortización impulsa la venta de bienes municipales y eclesiásticos." },
  { id: 152, year: 1856, title: "Nace el Banco de España con ese nombre", detail: "Una ley rebautiza el Banco Español de San Fernando como Banco de España." },
  { id: 153, year: 1869, title: "Constitución de 1869", detail: "El Sexenio Democrático aprueba una constitución basada en la soberanía nacional y amplios derechos." },
  { id: 154, year: 1870, title: "Amadeo de Saboya es elegido rey", detail: "Las Cortes eligen a Amadeo como rey; jurará la Constitución en enero de 1871." },
  { id: 155, year: 1872, title: "Tercera guerra carlista", detail: "Una nueva insurrección carlista abre un conflicto que se prolongará hasta 1876." },
  { id: 156, year: 1876, title: "Constitución de la Restauración", detail: "Se promulga la constitución que regirá la monarquía restaurada durante décadas." },
  { id: 157, year: 1879, title: "Fundación del PSOE", detail: "Pablo Iglesias y otros trabajadores fundan en Madrid el Partido Socialista Obrero Español." },
  { id: 158, year: 1882, title: "Comienza la construcción de la Sagrada Família", detail: "Se coloca la primera piedra del templo barcelonés, posteriormente dirigido por Antoni Gaudí." },
  { id: 159, year: 1888, title: "Fundación de la UGT", detail: "Se constituye en Barcelona la Unión General de Trabajadores." },
  { id: 160, year: 1890, title: "Sufragio universal masculino", detail: "Una nueva ley electoral restablece el derecho de voto para los varones adultos." },
  { id: 161, year: 1895, title: "Comienza la última guerra de Cuba", detail: "El levantamiento independentista abre el conflicto que terminará en 1898." },
  { id: 162, year: 1902, title: "Comienza el reinado efectivo de Alfonso XIII", detail: "Alfonso XIII alcanza la mayoría de edad y jura la Constitución." },
  { id: 163, year: 1906, title: "Nobel para Santiago Ramón y Cajal", detail: "El científico español recibe el Premio Nobel de Fisiología o Medicina por sus estudios del sistema nervioso." },
  { id: 164, year: 1907, title: "Junta para Ampliación de Estudios", detail: "Se crea una institución esencial para modernizar la ciencia y la educación españolas." },
  { id: 165, year: 1910, title: "Fundación de la CNT", detail: "Organizaciones obreras constituyen en Barcelona la Confederación Nacional del Trabajo." },
  { id: 166, year: 1917, title: "Crisis política, militar y social de 1917", detail: "Juntas militares, parlamentarios y una huelga general desafían al sistema de la Restauración." },
  { id: 167, year: 1921, title: "Desastre de Annual", detail: "El ejército español sufre una grave derrota frente a las fuerzas rifeñas." },
  { id: 168, year: 1925, title: "Desembarco de Alhucemas", detail: "Una operación hispano-francesa resulta decisiva en la guerra del Rif." },
  { id: 169, year: 1927, title: "Encuentro de la Generación del 27", detail: "El homenaje a Góngora celebrado en Sevilla se convierte en símbolo de una generación literaria." },
  { id: 170, year: 1932, title: "Estatuto de autonomía de Cataluña", detail: "Las Cortes republicanas aprueban el primer Estatuto catalán de la etapa contemporánea." },
  { id: 171, year: 1933, title: "Las mujeres votan en elecciones generales", detail: "Las españolas ejercen por primera vez el sufragio en unas elecciones generales." },
  { id: 172, year: 1934, title: "Revolución de Asturias", detail: "Una insurrección obrera es reprimida durante la crisis de octubre de 1934." },
  { id: 173, year: 1940, title: "Encuentro de Franco y Hitler en Hendaya", detail: "Ambos dictadores se reúnen para negociar sin que España entre formalmente en la guerra mundial." },
  { id: 174, year: 1947, title: "Ley de Sucesión en la Jefatura del Estado", detail: "La dictadura define España como reino y reserva a Franco la elección de sucesor." },
  { id: 175, year: 1953, title: "Pactos de Madrid con Estados Unidos", detail: "España y Estados Unidos firman acuerdos económicos y defensivos durante la dictadura." },
  { id: 176, year: 1956, title: "España reconoce la independencia de Marruecos", detail: "Un acuerdo pone fin al Protectorado español en la zona norte de Marruecos." },
  { id: 177, year: 1962, title: "Reunión de la oposición en Múnich", detail: "Un amplio grupo de opositores al franquismo reclama democratización e integración europea." },
  { id: 178, year: 1966, title: "Ley de Prensa e Imprenta", detail: "La llamada Ley Fraga elimina la censura previa general, aunque mantiene importantes controles." },
  { id: 179, year: 1973, title: "Asesinato de Carrero Blanco", detail: "ETA asesina en Madrid al presidente del Gobierno Luis Carrero Blanco." },
  { id: 180, year: 1976, title: "Referéndum para la Reforma Política", detail: "La ciudadanía aprueba la ley que abre el camino a elecciones democráticas." },
  { id: 181, year: 1977, title: "Pactos de la Moncloa", detail: "Gobierno, partidos y agentes sociales acuerdan medidas económicas y políticas durante la Transición." },
  { id: 182, year: 1979, title: "Primeras elecciones municipales democráticas", detail: "España celebra sus primeras elecciones locales libres desde la Segunda República." },
  { id: 183, year: 1981, title: "Nueva ley del divorcio", detail: "La Ley 30/1981 vuelve a regular el divorcio en España." },
  { id: 184, year: 1985, title: "Firma del Tratado de Adhesión europeo", detail: "España firma su incorporación a las Comunidades Europeas, efectiva desde 1986." },
  { id: 185, year: 1986, title: "Referéndum sobre la permanencia en la OTAN", detail: "La mayoría de votantes respalda la permanencia de España en la Alianza Atlántica." },
  { id: 186, year: 1992, title: "Primer tren de alta velocidad en España", detail: "Se inaugura la línea AVE entre Madrid y Sevilla." },
  { id: 187, year: 1995, title: "España entra en el espacio Schengen", detail: "Comienza a aplicarse la libre circulación sin controles fronterizos interiores." },
  { id: 188, year: 2005, title: "Matrimonio entre personas del mismo sexo", detail: "Una reforma del Código Civil reconoce el matrimonio con los mismos efectos para parejas del mismo o distinto sexo." },
  { id: 189, year: 2011, title: "ETA anuncia el cese definitivo de su actividad armada", detail: "La organización terrorista comunica el final definitivo de la violencia armada." },
  { id: 190, year: 2020, title: "Primer estado de alarma por la COVID-19", detail: "El Gobierno declara el estado de alarma y limita la movilidad ante la pandemia." }
];
