// El valor es la superficie en km². Ninguna carta está a menos de un 8% de otra: si no,
// colocarla bien sería cuestión de suerte. Los países que faltan suelen faltar por eso
// (China y Canadá se parecen demasiado a Estados Unidos, Alemania a Japón).
window.COUNTRY_CARDS = [
  { id: 2001, value: 17098246, title: "Rusia", detail: "El país más extenso del mundo: ocupa once husos horarios." },
  { id: 2002, value: 9833517, title: "Estados Unidos", detail: "Superficie total, aguas interiores incluidas; Alaska aporta casi una sexta parte." },
  { id: 2003, value: 8515767, title: "Brasil", detail: "Ocupa casi la mitad de Sudamérica." },
  { id: 2004, value: 7692024, title: "Australia", detail: "Un país y un continente a la vez." },
  { id: 2005, value: 3287263, title: "India", detail: "El séptimo país más extenso y, desde 2023, el más poblado." },
  { id: 2006, value: 2780400, title: "Argentina", detail: "El país más extenso de habla hispana." },
  { id: 2007, value: 2381741, title: "Argelia", detail: "El más extenso de África; en su mayor parte, Sáhara." },
  { id: 2008, value: 2149690, title: "Arabia Saudí", detail: "Ocupa cuatro quintas partes de la península arábiga." },
  { id: 2009, value: 1964375, title: "México", detail: "El tercer país más extenso de América Latina." },
  { id: 2010, value: 1648195, title: "Irán", detail: "Más de tres veces la superficie de España." },
  { id: 2011, value: 1221037, title: "Sudáfrica", detail: "Rodea por completo a otro país, Lesoto." },
  { id: 2012, value: 1098581, title: "Bolivia", detail: "Perdió su salida al mar en la guerra del Pacífico." },
  { id: 2013, value: 1001450, title: "Egipto", detail: "Justo por encima del millón de kilómetros cuadrados." },
  { id: 2014, value: 923768, title: "Nigeria", detail: "El país más poblado de África." },
  { id: 2015, value: 783562, title: "Turquía", detail: "Repartida entre Asia y Europa." },
  { id: 2016, value: 652230, title: "Afganistán", detail: "Montañoso y sin salida al mar, en el corazón de Asia." },
  { id: 2017, value: 603550, title: "Ucrania", detail: "El país más extenso situado por completo en Europa." },
  { id: 2018, value: 551695, title: "Francia", detail: "Superficie de la Francia metropolitana; con los territorios de ultramar pasa de 640.000 km²." },
  { id: 2019, value: 505944, title: "España", detail: "El segundo país más extenso de la Unión Europea, por detrás de Francia." },
  { id: 2020, value: 446550, title: "Marruecos", detail: "Sin contar el Sáhara Occidental, cuyo estatus sigue sin resolverse." },
  { id: 2021, value: 377975, title: "Japón", detail: "Un archipiélago alargado que se extiende más de 3.000 kilómetros." },
  { id: 2022, value: 338455, title: "Finlandia", detail: "El país con más lagos del mundo: unos 188.000." },
  { id: 2023, value: 301340, title: "Italia", detail: "La bota mediterránea, con Sicilia y Cerdeña incluidas." },
  { id: 2024, value: 268021, title: "Nueva Zelanda", detail: "Dos islas principales en mitad del Pacífico." },
  { id: 2025, value: 243610, title: "Reino Unido", detail: "Algo menos de la mitad de España." },
  { id: 2026, value: 207600, title: "Bielorrusia", detail: "Llanuras y bosques entre Polonia y Rusia." },
  { id: 2027, value: 176215, title: "Uruguay", detail: "El segundo país más pequeño de Sudamérica, tras Surinam." },
  { id: 2028, value: 147570, title: "Bangladés", detail: "Un delta densamente poblado, con más de 170 millones de personas." },
  { id: 2029, value: 131957, title: "Grecia", detail: "Unas 6.000 islas e islotes, de los que se habitan alrededor de 200." },
  { id: 2030, value: 120538, title: "Corea del Norte", detail: "Algo más extensa que su vecina del sur." },
  { id: 2031, value: 109884, title: "Cuba", detail: "La isla más grande del Caribe." },
  { id: 2032, value: 100210, title: "Corea del Sur", detail: "Montañosa, con más de la mitad de la población en el área de Seúl." },
  { id: 2033, value: 92212, title: "Portugal", detail: "Cabe cinco veces y media en España." },
  { id: 2034, value: 83879, title: "Austria", detail: "Alpina y sin salida al mar." },
  { id: 2035, value: 70273, title: "Irlanda", detail: "La isla esmeralda, sin contar Irlanda del Norte." },
  { id: 2036, value: 64589, title: "Letonia", detail: "Báltica, con más de la mitad del territorio cubierto de bosque." },
  { id: 2037, value: 56594, title: "Croacia", detail: "Su costa adriática suma más de mil islas." },
  { id: 2038, value: 51100, title: "Costa Rica", detail: "Sin ejército desde 1948." },
  { id: 2039, value: 45339, title: "Estonia", detail: "La más pequeña de las tres repúblicas bálticas." },
  { id: 2040, value: 41291, title: "Suiza", detail: "Los Alpes ocupan alrededor del 60% del país." },
  { id: 2041, value: 30528, title: "Bélgica", detail: "Una de las densidades de población más altas de Europa." },
  { id: 2042, value: 22072, title: "Israel", detail: "Poco más extenso que la provincia de Badajoz." },
  { id: 2043, value: 20273, title: "Eslovenia", detail: "Entre los Alpes y el Adriático, con apenas 47 kilómetros de costa." },
  { id: 2044, value: 17818, title: "Kuwait", detail: "Un emirato desértico en el golfo Pérsico." },
  { id: 2045, value: 11586, title: "Catar", detail: "Una península más pequeña que la provincia de Cuenca." },
  { id: 2046, value: 10452, title: "Líbano", detail: "Una franja mediterránea con montañas nevadas a la vista del mar." },
  { id: 2047, value: 9251, title: "Chipre", detail: "La tercera isla más grande del Mediterráneo." },
  { id: 2048, value: 5765, title: "Brunéi", detail: "Un sultanato petrolero en la isla de Borneo." },
  { id: 2049, value: 4033, title: "Cabo Verde", detail: "Diez islas volcánicas frente a la costa africana." },
  { id: 2050, value: 2586, title: "Luxemburgo", detail: "Un gran ducado más pequeño que la provincia de Álava." },
  { id: 2051, value: 2040, title: "Mauricio", detail: "Una isla del Índico, al este de Madagascar." },
  { id: 2052, value: 734, title: "Singapur", detail: "Una ciudad-estado que gana terreno al mar cada año." },
  { id: 2053, value: 468, title: "Andorra", detail: "Un principado pirenaico entre España y Francia." },
  { id: 2054, value: 316, title: "Malta", detail: "Un archipiélago en mitad del Mediterráneo." },
  { id: 2055, value: 160, title: "Liechtenstein", detail: "Un principado alpino entre Suiza y Austria." },
  { id: 2056, value: 61, title: "San Marino", detail: "La república más antigua del mundo, rodeada por Italia." },
  { id: 2057, value: 21, title: "Nauru", detail: "Una isla de coral: el país más pequeño fuera de Europa." },
  { id: 2058, value: 2.08, title: "Mónaco", detail: "El segundo país más pequeño del mundo, en dos kilómetros cuadrados." },
  { id: 2059, value: 0.49, title: "Ciudad del Vaticano", detail: "El país más pequeño del mundo: cabría dentro del Retiro." }
];
