// Distancias entre ciudades. Se calculan en línea recta sobre la superficie terrestre
// (círculo máximo) entre coordenadas fijas de los centros urbanos, con radio terrestre
// medio de 6.371 km. No son distancias por carretera, tren ni avión.
window.CITY_DISTANCE_CARDS = [
  { id: 11001, value: 17, title: "París — Versalles", detail: "17 km entre centros urbanos, calculados como distancia de círculo máximo sobre la Tierra." },
  { id: 11002, value: 27, title: "Berlín — Potsdam", detail: "27 km en línea recta entre los centros urbanos." },
  { id: 11003, value: 30, title: "Madrid — Alcalá de Henares", detail: "30 km en línea recta entre los centros urbanos." },
  { id: 11004, value: 34, title: "Ámsterdam — Utrecht", detail: "34 km en línea recta entre los centros urbanos." },
  { id: 11005, value: 67, title: "Madrid — Toledo", detail: "67 km en línea recta entre los centros urbanos." },
  { id: 11006, value: 76, title: "Londres — Brighton", detail: "76 km en línea recta entre los centros urbanos." },
  { id: 11007, value: 85, title: "Barcelona — Girona", detail: "85 km en línea recta entre los centros urbanos." },
  { id: 11008, value: 112, title: "París — Ruan", detail: "112 km en línea recta entre los centros urbanos." },
  { id: 11009, value: 130, title: "París — Reims", detail: "130 km en línea recta entre los centros urbanos." },
  { id: 11010, value: 188, title: "Roma — Nápoles", detail: "188 km en línea recta entre los centros urbanos." },
  { id: 11011, value: 204, title: "París — Lille", detail: "204 km en línea recta entre los centros urbanos." },
  { id: 11012, value: 273, title: "Madrid — Zaragoza", detail: "273 km en línea recta entre los centros urbanos." },
  { id: 11013, value: 303, title: "Madrid — Valencia", detail: "303 km en línea recta entre los centros urbanos." },
  { id: 11014, value: 344, title: "París — Londres", detail: "344 km en línea recta entre los centros urbanos." },
  { id: 11015, value: 390, title: "Madrid — Sevilla", detail: "390 km en línea recta entre los centros urbanos." },
  { id: 11016, value: 477, title: "Roma — Milán", detail: "477 km en línea recta entre los centros urbanos." },
  { id: 11017, value: 831, title: "París — Barcelona", detail: "831 km en línea recta entre los centros urbanos." },
  { id: 11018, value: 1053, title: "Madrid — París", detail: "1.053 km en línea recta entre los centros urbanos." },
  { id: 11019, value: 1144, title: "Nueva York — Chicago", detail: "1.144 km en línea recta entre los centros urbanos." },
  { id: 11020, value: 1263, title: "Madrid — Londres", detail: "1.263 km en línea recta entre los centros urbanos." },
  { id: 11021, value: 1869, title: "Madrid — Berlín", detail: "1.869 km en línea recta entre los centros urbanos." },
  { id: 11022, value: 2370, title: "Madrid — Atenas", detail: "2.370 km en línea recta entre los centros urbanos." },
  { id: 11023, value: 2891, title: "Madrid — Reikiavik", detail: "2.891 km en línea recta entre los centros urbanos." },
  { id: 11024, value: 3351, title: "Madrid — El Cairo", detail: "3.351 km en línea recta entre los centros urbanos." },
  { id: 11025, value: 4774, title: "Madrid — Teherán", detail: "4.774 km en línea recta entre los centros urbanos." },
  { id: 11026, value: 5311, title: "Singapur — Tokio", detail: "5.311 km en línea recta entre los centros urbanos." },
  { id: 11027, value: 5837, title: "París — Nueva York", detail: "5.837 km en línea recta entre los centros urbanos." },
  { id: 11028, value: 683, title: "Roma — Zúrich", detail: "683 km en línea recta entre los centros urbanos." },
  { id: 11029, value: 7192, title: "Londres — Bombay", detail: "7.192 km en línea recta entre los centros urbanos." },
  { id: 11030, value: 8070, title: "Estambul — Nueva York", detail: "8.070 km en línea recta entre los centros urbanos." },
  { id: 11031, value: 534, title: "Londres — Edimburgo", detail: "534 km en línea recta entre los centros urbanos." },
  { id: 11032, value: 9363, title: "Madrid — Los Ángeles", detail: "9.363 km en línea recta entre los centros urbanos." },
  { id: 11033, value: 10702, title: "Madrid — Santiago de Chile", detail: "10.702 km en línea recta entre los centros urbanos." },
  { id: 11034, value: 11707, title: "Johannesburgo — Pekín", detail: "11.707 km en línea recta entre los centros urbanos." },
  { id: 11035, value: 12649, title: "Madrid — Honolulu", detail: "12.649 km en línea recta entre los centros urbanos." },
  { id: 11036, value: 14615, title: "Madrid — Perth", detail: "14.615 km en línea recta entre los centros urbanos." },
  { id: 11037, value: 17685, title: "Madrid — Sídney", detail: "17.685 km en línea recta entre los centros urbanos." },
  { id: 11038, value: 19597, title: "Madrid — Auckland", detail: "19.597 km en línea recta entre los centros urbanos." }
];
