// Distancias entre ciudades. Se calculan en línea recta sobre la superficie terrestre
// (círculo máximo) entre coordenadas fijas de los centros urbanos, con radio terrestre
// medio de 6.371 km. No son distancias por carretera, tren ni avión.
window.CITY_DISTANCE_CARDS = [
  { id: 11001, value: 17, title: "París — Versalles", detail: "17 km entre centros urbanos, calculados como distancia de círculo máximo sobre la Tierra." },
  { id: 11002, value: 27, title: "Berlín — Potsdam", detail: "27 km en línea recta entre los centros urbanos." },
  { id: 11003, value: 30, title: "Madrid — Alcalá de Henares", detail: "30 km en línea recta entre los centros urbanos." },
  { id: 11004, value: 34, title: "Ámsterdam — Utrecht", detail: "34 km en línea recta entre los centros urbanos." },
  { id: 11005, value: 67, title: "Madrid — Toledo", detail: "67 km en línea recta entre los centros urbanos." },
  { id: 11006, value: 76, title: "Londres — Brighton", detail: "76 km en línea recta entre los centros urbanos." },
  { id: 11007, value: 85, title: "Barcelona — Girona", detail: "85 km en línea recta entre los centros urbanos." },
  { id: 11008, value: 112, title: "París — Ruan", detail: "112 km en línea recta entre los centros urbanos." },
  { id: 11009, value: 130, title: "París — Reims", detail: "130 km en línea recta entre los centros urbanos." },
  { id: 11010, value: 188, title: "Roma — Nápoles", detail: "188 km en línea recta entre los centros urbanos." },
  { id: 11011, value: 204, title: "París — Lille", detail: "204 km en línea recta entre los centros urbanos." },
  { id: 11041, value: 205, title: "Buenos Aires — Montevideo", detail: "205 km en línea recta entre los centros urbanos." },
  { id: 11070, value: 239, title: "Bogotá — Medellín", detail: "239 km en línea recta entre los centros urbanos." },
  { id: 11012, value: 273, title: "Madrid — Zaragoza", detail: "273 km en línea recta entre los centros urbanos." },
  { id: 11013, value: 303, title: "Madrid — Valencia", detail: "303 km en línea recta entre los centros urbanos." },
  { id: 11014, value: 344, title: "París — Londres", detail: "344 km en línea recta entre los centros urbanos." },
  { id: 11040, value: 361, title: "Río de Janeiro — São Paulo", detail: "361 km en línea recta entre los centros urbanos." },
  { id: 11015, value: 390, title: "Madrid — Sevilla", detail: "390 km en línea recta entre los centros urbanos." },
  { id: 11068, value: 418, title: "Sofía — Sarajevo", detail: "418 km en línea recta entre los centros urbanos." },
  { id: 11042, value: 425, title: "El Cairo — Jerusalén", detail: "425 km en línea recta entre los centros urbanos." },
  { id: 11049, value: 461, title: "Ciudad de México — Guadalajara", detail: "461 km en línea recta entre los centros urbanos." },
  { id: 11016, value: 477, title: "Roma — Milán", detail: "477 km en línea recta entre los centros urbanos." },
  { id: 11048, value: 493, title: "Auckland — Wellington", detail: "493 km en línea recta entre los centros urbanos." },
  { id: 11050, value: 504, title: "Toronto — Montreal", detail: "504 km en línea recta entre los centros urbanos." },
  { id: 11043, value: 505, title: "Nairobi — Kampala", detail: "505 km en línea recta entre los centros urbanos." },
  { id: 11031, value: 534, title: "Londres — Edimburgo", detail: "534 km en línea recta entre los centros urbanos." },
  { id: 11039, value: 559, title: "San Francisco — Los Ángeles", detail: "559 km en línea recta entre los centros urbanos." },
  { id: 11028, value: 683, title: "Roma — Zúrich", detail: "683 km en línea recta entre los centros urbanos." },
  { id: 11061, value: 709, title: "Hamburgo — Oslo", detail: "709 km en línea recta entre los centros urbanos." },
  { id: 11047, value: 713, title: "Sídney — Melbourne", detail: "713 km en línea recta entre los centros urbanos." },
  { id: 11017, value: 831, title: "París — Barcelona", detail: "831 km en línea recta entre los centros urbanos." },
  { id: 11053, value: 1051, title: "Roma — Atenas", detail: "1.051 km en línea recta entre los centros urbanos." },
  { id: 11018, value: 1053, title: "Madrid — París", detail: "1.053 km en línea recta entre los centros urbanos." },
  { id: 11045, value: 1067, title: "Pekín — Shanghái", detail: "1.067 km en línea recta entre los centros urbanos." },
  { id: 11019, value: 1144, title: "Nueva York — Chicago", detail: "1.144 km en línea recta entre los centros urbanos." },
  { id: 11044, value: 1148, title: "Delhi — Bombay", detail: "1.148 km en línea recta entre los centros urbanos." },
  { id: 11046, value: 1149, title: "Tokio — Seúl", detail: "1.149 km en línea recta entre los centros urbanos." },
  { id: 11060, value: 1183, title: "Berlín — Roma", detail: "1.183 km en línea recta entre los centros urbanos." },
  { id: 11020, value: 1263, title: "Madrid — Londres", detail: "1.263 km en línea recta entre los centros urbanos." },
  { id: 11067, value: 1343, title: "Montevideo — Santiago de Chile", detail: "1.343 km en línea recta entre los centros urbanos." },
  { id: 11065, value: 1486, title: "Praga — San Petersburgo", detail: "1.486 km en línea recta entre los centros urbanos." },
  { id: 11059, value: 1495, title: "Dublín — Reikiavik", detail: "1.495 km en línea recta entre los centros urbanos." },
  { id: 11058, value: 1547, title: "Gibraltar — París", detail: "1.547 km en línea recta entre los centros urbanos." },
  { id: 11054, value: 1623, title: "Teherán — Kabul", detail: "1.623 km en línea recta entre los centros urbanos." },
  { id: 11021, value: 1869, title: "Madrid — Berlín", detail: "1.869 km en línea recta entre los centros urbanos." },
  { id: 11063, value: 2160, title: "La Habana — Caracas", detail: "2.160 km en línea recta entre los centros urbanos." },
  { id: 11022, value: 2370, title: "Madrid — Atenas", detail: "2.370 km en línea recta entre los centros urbanos." },
  { id: 11066, value: 2393, title: "Estocolmo — Ankara", detail: "2.393 km en línea recta entre los centros urbanos." },
  { id: 11064, value: 2759, title: "Lisboa — Varsovia", detail: "2.759 km en línea recta entre los centros urbanos." },
  { id: 11055, value: 2777, title: "Viena — Bakú", detail: "2.777 km en línea recta entre los centros urbanos." },
  { id: 11023, value: 2891, title: "Madrid — Reikiavik", detail: "2.891 km en línea recta entre los centros urbanos." },
  { id: 11024, value: 3351, title: "Madrid — El Cairo", detail: "3.351 km en línea recta entre los centros urbanos." },
  { id: 11056, value: 4612, title: "Doha — Copenhague", detail: "4.612 km en línea recta entre los centros urbanos." },
  { id: 11025, value: 4774, title: "Madrid — Teherán", detail: "4.774 km en línea recta entre los centros urbanos." },
  { id: 11026, value: 5311, title: "Singapur — Tokio", detail: "5.311 km en línea recta entre los centros urbanos." },
  { id: 11027, value: 5837, title: "París — Nueva York", detail: "5.837 km en línea recta entre los centros urbanos." },
  { id: 11029, value: 7192, title: "Londres — Bombay", detail: "7.192 km en línea recta entre los centros urbanos." },
  { id: 11030, value: 8070, title: "Estambul — Nueva York", detail: "8.070 km en línea recta entre los centros urbanos." },
  { id: 11057, value: 9076, title: "Tallin — Los Ángeles", detail: "9.076 km en línea recta entre los centros urbanos." },
  { id: 11032, value: 9363, title: "Madrid — Los Ángeles", detail: "9.363 km en línea recta entre los centros urbanos." },
  { id: 11051, value: 9562, title: "El Cairo — Tokio", detail: "9.562 km en línea recta entre los centros urbanos." },
  { id: 11033, value: 10702, title: "Madrid — Santiago de Chile", detail: "10.702 km en línea recta entre los centros urbanos." },
  { id: 11034, value: 11707, title: "Johannesburgo — Pekín", detail: "11.707 km en línea recta entre los centros urbanos." },
  { id: 11052, value: 12644, title: "Lima — Moscú", detail: "12.644 km en línea recta entre los centros urbanos." },
  { id: 11035, value: 12649, title: "Madrid — Honolulu", detail: "12.649 km en línea recta entre los centros urbanos." },
  { id: 11036, value: 14615, title: "Madrid — Perth", detail: "14.615 km en línea recta entre los centros urbanos." },
  { id: 11062, value: 15107, title: "Seúl — Quito", detail: "15.107 km en línea recta entre los centros urbanos." },
  { id: 11069, value: 16932, title: "Brasilia — Pekín", detail: "16.932 km en línea recta entre los centros urbanos." },
  { id: 11037, value: 17685, title: "Madrid — Sídney", detail: "17.685 km en línea recta entre los centros urbanos." },
  { id: 11038, value: 19597, title: "Madrid — Auckland", detail: "19.597 km en línea recta entre los centros urbanos." }
];
