// Inventos y descubrimientos. Comparte el eje del tiempo con la historia, pero no sus
// épocas: aquí las bandas van de la escritura a la edición genética.
//
// Dos criterios al elegir las cartas. Uno, que la fecha sea un hecho concreto y datable
// —una patente, una publicación, una primera demostración— y no el año difuso en que
// «apareció» algo. Dos, una selección variada de fechas, sin alterar los datos para
// forzar separación. Los empates son válidos en cualquier orden. Donde la fecha es
// aproximada o discutida, lo dicen el título y la explicación.
window.INVENTION_CARDS = [
  { id: 4001, year: -3300, title: "La escritura cuneiforme (fecha aproximada)", detail: "En Sumeria se empiezan a marcar cuentas sobre arcilla blanda; es el primer sistema de escritura conocido." },
  { id: 4002, year: -3000, title: "La rueda de alfarero (fecha aproximada)", detail: "El torno de alfarero es el primer uso documentado de la rueda, antes que el transporte." },
  { id: 4003, year: -2600, title: "El papiro egipcio (fecha aproximada)", detail: "Egipto convierte una planta del Nilo en la primera superficie ligera para escribir." },
  { id: 4004, year: -1750, title: "El código de Hammurabi", detail: "Babilonia graba en piedra uno de los primeros conjuntos de leyes escritas que se conservan." },
  { id: 4005, year: -630, title: "Las primeras monedas acuñadas (fecha aproximada)", detail: "El reino de Lidia sella trozos de electro con un peso garantizado por el Estado." },
  { id: 4006, year: -240, title: "Eratóstenes mide la Tierra", detail: "Con dos sombras y una distancia calcula la circunferencia del planeta con un error de pocos puntos." },
  { id: 4007, year: -212, title: "Muere Arquímedes, estudioso de la palanca", detail: "Arquímedes muere en Siracusa durante la conquista romana. La fecha corresponde a su muerte, no a la formulación de la ley de la palanca." },
  { id: 4008, year: -46, title: "Julio César decreta la reforma del calendario", detail: "La reforma se decreta en 46 a. C.; el calendario juliano entra en vigor el 1 de enero de 45 a. C." },
  { id: 4009, year: 105, title: "El papel en China", detail: "Cai Lun presenta al emperador un papel barato hecho con corteza, cáñamo y trapos." },
  { id: 4010, year: 150, title: "El Almagesto de Ptolomeo", detail: "El modelo del cielo con la Tierra en el centro que se enseñará durante catorce siglos." },
  { id: 4011, year: 750, title: "El astrolabio en el mundo islámico (siglo VIII, fecha aproximada)", detail: "El astrolabio, de origen antiguo, se desarrolla en el mundo islámico desde el siglo VIII. Se usa 750 como referencia aproximada del siglo, no como fecha de una invención puntual.", label: "c. 750" },
  { id: 4012, year: 830, title: "El tratado de álgebra de Al-Juarismi (fecha aproximada)", detail: "Al-Juarismi escribe su tratado de álgebra durante el reinado de al-Mamún (813–833). Se sitúa aproximadamente hacia 830, no en 850, fecha asociada a su muerte.", label: "c. 830" },
  { id: 4013, year: 1044, title: "La primera fórmula escrita de la pólvora", detail: "Un manual militar chino, el Wujing Zongyao, recoge tres recetas de mezcla explosiva." },
  { id: 4014, year: 1088, title: "El reloj astronómico de Su Song", detail: "Una torre de agua y engranajes que mueve una esfera celeste: el escape mecánico antes que en Europa." },
  { id: 4015, year: 1286, title: "Las primeras gafas (fecha aproximada)", detail: "En la Toscana se montan dos lentes convexas sobre la nariz para leer de cerca." },
  { id: 4016, year: 1450, title: "La imprenta de tipos móviles de Gutenberg", detail: "Tipos de metal reutilizables y una prensa de vino: el libro deja de copiarse a mano." },
  { id: 4017, year: 1543, title: "Copérnico pone el Sol en el centro", detail: "«De revolutionibus» se publica el año de su muerte y desplaza a la Tierra del centro del universo." },
  { id: 4018, year: 1582, title: "El calendario gregoriano", detail: "Para recuperar el desfase acumulado, a jueves 4 de octubre le sigue viernes 15." },
  { id: 4019, year: 1600, title: "Gilbert explica el imán", detail: "«De Magnete» demuestra que la Tierra entera se comporta como un imán." },
  { id: 4020, year: 1608, title: "Lippershey solicita una patente para el telescopio", detail: "El óptico Hans Lippershey solicita en los Países Bajos la primera patente de un catalejo." },
  { id: 4021, year: 1610, title: "Galileo publica lo que ve en el cielo", detail: "«Sidereus Nuncius» describe los cráteres de la Luna y cuatro lunas girando en torno a Júpiter." },
  { id: 4022, year: 1628, title: "Harvey descubre la circulación de la sangre", detail: "Demuestra que la sangre da vueltas por el cuerpo impulsada por el corazón." },
  { id: 4023, year: 1642, title: "La calculadora de Pascal", detail: "Una caja de ruedas dentadas que suma y resta, construida para el despacho de impuestos de su padre." },
  { id: 4024, year: 1656, title: "El reloj de péndulo", detail: "Huygens aplica el péndulo a la relojería y el error diario pasa de minutos a segundos." },
  { id: 4025, year: 1665, title: "Hooke ve la célula", detail: "«Micrographia» dibuja las celdillas del corcho y les da el nombre que aún usamos." },
  { id: 4026, year: 1676, title: "Rømer mide la velocidad de la luz", detail: "Los eclipses de las lunas de Júpiter se retrasan: la luz tarda en llegar, no es instantánea." },
  { id: 4027, year: 1687, title: "Los «Principia» de Newton", detail: "Tres leyes del movimiento y la gravitación universal explican la manzana y los planetas a la vez." },
  { id: 4028, year: 1698, title: "La primera máquina de vapor comercial", detail: "Thomas Savery patenta una bomba de vapor para achicar agua de las minas." },
  { id: 4029, year: 1712, title: "La máquina atmosférica de Newcomen", detail: "El primer motor de vapor que funciona de verdad, con pistón y cilindro." },
  { id: 4030, year: 1714, title: "El termómetro de mercurio", detail: "Fahrenheit desarrolla el termómetro de mercurio; la publicación de la escala que lleva su nombre llegará en 1724." },
  { id: 4031, year: 1735, title: "Linneo publica la primera edición de «Systema Naturae»", detail: "Linneo presenta su clasificación de la naturaleza. Los puntos de partida de su nomenclatura binomial llegarán en 1753 para plantas y 1758 para animales." },
  { id: 4032, year: 1752, title: "El pararrayos de Franklin", detail: "Tras el experimento de la cometa, propone una punta metálica conectada a tierra." },
  { id: 4033, year: 1769, title: "Watt patenta el condensador separado", detail: "Enfriar el vapor fuera del cilindro triplica el rendimiento y arranca la revolución industrial." },
  { id: 4034, year: 1774, title: "El descubrimiento del oxígeno", detail: "Priestley aísla el gas que mantiene la llama; Lavoisier lo nombra y explica la combustión." },
  { id: 4035, year: 1783, title: "El globo de los hermanos Montgolfier", detail: "Un globo de aire caliente eleva a dos personas sobre París: el primer vuelo tripulado." },
  { id: 4036, year: 1796, title: "La vacuna de la viruela", detail: "Jenner inocula viruela de las vacas a un niño y lo protege de la humana." },
  { id: 4037, year: 1800, title: "La pila de Volta", detail: "Discos de cobre y cinc separados por paño húmedo: la primera corriente eléctrica continua." },
  { id: 4038, year: 1804, title: "La primera locomotora de vapor", detail: "Trevithick arrastra diez toneladas sobre raíles en Gales y gana una apuesta." },
  { id: 4039, year: 1816, title: "El estetoscopio", detail: "Laënnec enrolla un papel para no pegar la oreja al pecho de una paciente y funda la auscultación." },
  { id: 4040, year: 1821, title: "El primer motor eléctrico", detail: "Faraday hace girar un alambre alrededor de un imán: la electricidad se convierte en movimiento." },
  { id: 4041, year: 1826, title: "La primera fotografía conservada (fecha aproximada)", detail: "Niépce fija una vista desde su ventana sobre una placa de betún. La fotografía se fecha en 1826 o 1827; el mazo utiliza 1826 como referencia aproximada.", label: "c. 1826" },
  { id: 4042, year: 1831, title: "La inducción electromagnética", detail: "Faraday descubre que un imán en movimiento genera corriente: el principio de todo generador." },
  { id: 4043, year: 1837, title: "Morse desarrolla su telégrafo eléctrico", detail: "Morse desarrolla y demuestra su sistema telegráfico en 1837. La patente estadounidense se concede en 1840." },
  { id: 4044, year: 1839, title: "El daguerrotipo", detail: "Francia compra la patente y regala al mundo la primera fotografía nítida y repetible." },
  { id: 4045, year: 1844, title: "La vulcanización del caucho", detail: "Goodyear patenta el caucho con azufre y calor: deja de derretirse en verano y agrietarse en invierno." },
  { id: 4046, year: 1846, title: "La anestesia con éter", detail: "Una operación pública en Boston demuestra que se puede operar sin dolor." },
  { id: 4047, year: 1853, title: "Otis vende sus primeros ascensores de seguridad", detail: "Otis realiza sus primeras ventas en 1853. La célebre demostración pública del freno de seguridad en Nueva York tendrá lugar en 1854." },
  { id: 4048, year: 1855, title: "El convertidor Bessemer", detail: "Soplar aire sobre el hierro fundido abarata el acero y hace posibles rieles, puentes y rascacielos." },
  { id: 4049, year: 1859, title: "«El origen de las especies»", detail: "Darwin explica la diversidad de la vida por selección natural." },
  { id: 4050, year: 1861, title: "La primera fotografía en color", detail: "Maxwell proyecta tres imágenes filtradas en rojo, verde y azul y las superpone." },
  { id: 4051, year: 1865, title: "Mendel presenta sus experimentos sobre la herencia", detail: "Mendel expone sus resultados con guisantes en 1865 ante la Sociedad de Historia Natural de Brno; el artículo se publica en 1866." },
  { id: 4052, year: 1867, title: "La dinamita", detail: "Nobel estabiliza la nitroglicerina con tierra de diatomeas y la vuelve manejable." },
  { id: 4053, year: 1869, title: "La tabla periódica", detail: "Mendeléyev ordena los elementos y deja huecos para los que aún no se habían descubierto." },
  { id: 4054, year: 1876, title: "La patente del teléfono", detail: "Bell registra el aparato que convierte la voz en corriente eléctrica y la devuelve al otro lado." },
  { id: 4055, year: 1879, title: "La lámpara incandescente duradera", detail: "Edison da con un filamento que aguanta cuarenta horas y hace viable la luz eléctrica." },
  { id: 4056, year: 1886, title: "La patente del automóvil", detail: "Carl Benz registra un triciclo con motor de gasolina: el primer coche pensado como tal." },
  { id: 4057, year: 1888, title: "El neumático hinchable", detail: "Dunlop pone tubos de goma con aire en el triciclo de su hijo y patenta la idea." },
  { id: 4058, year: 1895, title: "Los rayos X", detail: "Röntgen fotografía los huesos de la mano de su mujer sin abrirle la piel." },
  { id: 4059, year: 1898, title: "Se descubren el polonio y el radio", detail: "Marie y Pierre Curie anuncian el descubrimiento de estos elementos. El aislamiento del radio metálico lo realizarán Marie Curie y André Debierne en 1910." },
  { id: 4060, year: 1901, title: "La primera señal de radio transatlántica", detail: "Marconi asegura haber recibido en Terranova tres puntos enviados desde Cornualles." },
  { id: 4061, year: 1903, title: "El primer vuelo de los hermanos Wright", detail: "Doce segundos y treinta y seis metros en Kitty Hawk, con un aparato más pesado que el aire." },
  { id: 4062, year: 1905, title: "La relatividad especial", detail: "Einstein publica en un solo año cuatro artículos que rehacen la física, uno de ellos con E=mc²." },
  { id: 4063, year: 1907, title: "La baquelita, el primer plástico sintético", detail: "Baekeland fabrica un material que no viene de ninguna planta ni animal." },
  { id: 4064, year: 1909, title: "El proceso Haber para el amoniaco", detail: "Fijar el nitrógeno del aire da fertilizantes baratos y multiplica las cosechas del siglo." },
  { id: 4065, year: 1911, title: "Rutherford propone el modelo nuclear del átomo", detail: "Rutherford interpreta los experimentos de dispersión de Geiger y Marsden, publicados en 1909, y propone un átomo con un núcleo pequeño y concentrado en 1911." },
  { id: 4066, year: 1913, title: "La cadena de montaje de Ford", detail: "El chasis pasa por delante del obrero y el tiempo de fabricación cae de doce horas a hora y media." },
  { id: 4067, year: 1915, title: "La relatividad general", detail: "La gravedad deja de ser una fuerza y pasa a ser la curvatura del espacio y el tiempo." },
  { id: 4068, year: 1921, title: "La insulina", detail: "Banting y Best extraen de un páncreas la hormona que convierte la diabetes en enfermedad tratable." },
  { id: 4069, year: 1926, title: "La primera demostración de la televisión", detail: "Baird transmite una cara reconocible en movimiento ante la Royal Institution." },
  { id: 4070, year: 1928, title: "La penicilina", detail: "Fleming se encuentra un moho que ha matado las bacterias de una placa que olvidó destapar." },
  { id: 4071, year: 1930, title: "La patente del motor a reacción", detail: "Frank Whittle registra la turbina de gas para aviación con veintitrés años." },
  { id: 4072, year: 1935, title: "El radar", detail: "Watson-Watt detecta un bombardero a trece kilómetros rebotando ondas de radio en él." },
  { id: 4073, year: 1938, title: "La fisión nuclear", detail: "Hahn y Strassmann parten el uranio; Meitner y Frisch explican por qué y lo bautizan." },
  { id: 4074, year: 1940, title: "Las medias de nailon salen a la venta", detail: "Cuatro millones de pares en cuatro días: la primera fibra sintética conquista la calle." },
  { id: 4075, year: 1942, title: "La primera reacción nuclear en cadena", detail: "Bajo las gradas de un campo de fútbol de Chicago, una pila de grafito y uranio se sostiene sola." },
  { id: 4076, year: 1946, title: "El ENIAC", detail: "Treinta toneladas y dieciocho mil válvulas en el primer gran computador electrónico de uso general." },
  { id: 4077, year: 1947, title: "El transistor", detail: "Tres investigadores de Bell Labs sustituyen la válvula por un trocito de germanio." },
  { id: 4078, year: 1953, title: "La estructura del ADN", detail: "La doble hélice, apoyada en las imágenes de rayos X de Rosalind Franklin." },
  { id: 4079, year: 1955, title: "La vacuna de la polio", detail: "La campaña de Salk empieza a vaciar los pabellones de pulmones de acero." },
  { id: 4080, year: 1957, title: "El Sputnik", detail: "Una esfera de 58 centímetros da la vuelta al mundo cada 96 minutos y abre la carrera espacial." },
  { id: 4081, year: 1958, title: "El circuito integrado", detail: "Kilby mete varios componentes en una sola pieza de semiconductor: nace el chip." },
  { id: 4082, year: 1960, title: "El láser", detail: "Maiman consigue el primer haz con un rubí sintético y una lámpara de flash." },
  { id: 4083, year: 1961, title: "El primer humano en el espacio", detail: "Yuri Gagarin da una vuelta completa a la Tierra en 108 minutos." },
  { id: 4084, year: 1967, title: "El primer trasplante de corazón", detail: "Christiaan Barnard opera en Ciudad del Cabo; el paciente vive dieciocho días." },
  { id: 4085, year: 1969, title: "La llegada a la Luna", detail: "El Apolo 11 posa el módulo Eagle en el mar de la Tranquilidad." },
  { id: 4086, year: 1971, title: "El primer microprocesador", detail: "El Intel 4004 mete una unidad de cálculo entera en un chip del tamaño de una uña." },
  { id: 4087, year: 1973, title: "La primera llamada desde un móvil", detail: "Martin Cooper llama desde una acera de Nueva York con un aparato de casi un kilo." },
  { id: 4088, year: 1978, title: "El primer bebé por fecundación in vitro", detail: "Nace Louise Brown tras una década de intentos de Edwards y Steptoe." },
  { id: 4089, year: 1979, title: "El walkman", detail: "Sony saca un casete sin altavoz: la música pasa a ser algo que se lleva encima." },
  { id: 4090, year: 1981, title: "El IBM PC", detail: "Una arquitectura abierta convierte el ordenador personal en un estándar que otros pueden copiar." },
  { id: 4091, year: 1983, title: "El protocolo TCP/IP", detail: "ARPANET cambia de protocolo en un solo día y las redes empiezan a poder hablar entre sí." },
  { id: 4092, year: 1984, title: "La huella genética", detail: "Alec Jeffreys descubre por accidente que el ADN identifica a una persona como una huella dactilar." },
  { id: 4093, year: 1989, title: "La propuesta de la World Wide Web", detail: "Berners-Lee entrega en el CERN un memorando que su jefe anota: «vago, pero interesante»." },
  { id: 4094, year: 1990, title: "El telescopio espacial Hubble", detail: "El telescopio espacial se lanza con un defecto de forma en su espejo primario. Una misión de servicio instalará óptica correctora en 1993." },
  { id: 4095, year: 1996, title: "La oveja Dolly", detail: "El primer mamífero clonado a partir de una célula adulta." },
  { id: 4096, year: 1997, title: "Deep Blue gana a Kaspárov", detail: "Una máquina derrota por primera vez al campeón del mundo de ajedrez en un match completo." },
  { id: 4097, year: 2001, title: "El primer borrador del genoma humano", detail: "Dos equipos rivales publican a la vez la secuencia casi completa de nuestros cromosomas." },
  { id: 4098, year: 2007, title: "El iPhone", detail: "Una pantalla táctil sin teclado redefine lo que se espera de un teléfono." },
  { id: 4099, year: 2012, title: "CRISPR como herramienta de edición genética", detail: "Doudna y Charpentier convierten un sistema inmunitario bacteriano en unas tijeras para el ADN." },
  { id: 4100, year: 2015, title: "La detección de ondas gravitacionales", detail: "LIGO registra el temblor del espacio provocado por dos agujeros negros al fundirse." },
  { id: 4101, year: 2019, title: "La primera imagen de un agujero negro", detail: "Ocho radiotelescopios repartidos por el planeta fotografían el de la galaxia M87." },
  { id: 4102, year: 2020, title: "Las vacunas de ARN mensajero", detail: "Una técnica que llevaba décadas en el laboratorio se despliega contra la covid en menos de un año." },
  { id: 4103, year: 2022, title: "Las primeras imágenes del James Webb", detail: "El sucesor del Hubble mira en infrarrojo y alcanza a ver galaxias del universo primitivo." }
];
