// Esperanza de vida de referencia. Cada cifra es una longevidad típica o máxima
// ampliamente documentada para la especie; cambia con el hábitat y el cuidado humano.
window.ANIMAL_LIFESPAN_CARDS = [
  { id: 12001, value: 0.015, title: "Efímera", detail: "El adulto de algunas efímeras vive apenas unos días: sale del agua para reproducirse y muere poco después." },
  { id: 12002, value: 0.025, title: "Mosca de mayo", detail: "La fase alada suele durar alrededor de una semana, aunque la fase juvenil acuática es mucho más larga." },
  { id: 12003, value: 0.04, title: "Mosquito común", detail: "Un adulto puede vivir unas dos semanas; las hembras suelen durar más que los machos." },
  { id: 12004, value: 0.065, title: "Mosca de la fruta", detail: "En condiciones favorables, su ciclo adulto ronda unas pocas semanas." },
  { id: 12005, value: 0.1, title: "Abeja obrera", detail: "Una obrera de verano suele vivir unas seis semanas, trabajando sin parar desde que emerge." },
  { id: 12006, value: 0.16, title: "Mariposa monarca", detail: "Las generaciones migratorias pueden vivir varios meses, mucho más que otras mariposas." },
  { id: 12007, value: 0.25, title: "Ratón doméstico", detail: "En libertad su vida suele ser corta por depredadores y enfermedades; con cuidados vive bastante más." },
  { id: 12008, value: 0.4, title: "Rata parda", detail: "Una rata salvaje rara vez llega a dos años, aunque en cautividad puede superar esa cifra." },
  { id: 12009, value: 0.65, title: "Hámster sirio", detail: "Su esperanza de vida habitual está cerca de dos años, pero la mortalidad juvenil reduce el promedio." },
  { id: 12010, value: 1, title: "Jerbo", detail: "Este pequeño roedor desértico suele vivir unos tres años en condiciones favorables." },
  { id: 12011, value: 1.6, title: "Cobaya", detail: "Una cobaya doméstica bien cuidada suele vivir entre cinco y ocho años." },
  { id: 12012, value: 2.5, title: "Conejo europeo", detail: "En la naturaleza muchos conejos no pasan de su segundo año, por la presión de los depredadores." },
  { id: 12013, value: 4, title: "Erizo europeo", detail: "Puede rondar los siete años, aunque pocos ejemplares silvestres alcanzan esa edad." },
  { id: 12014, value: 6.5, title: "Ardilla roja", detail: "En bosques favorables puede vivir cerca de siete años; la vida media real suele ser menor." },
  { id: 12015, value: 10, title: "Zorro rojo", detail: "En libertad vive pocos años de media, pero se han documentado individuos de diez o más." },
  { id: 12016, value: 13, title: "Perro doméstico", detail: "La longevidad varía mucho por raza y tamaño; los perros pequeños suelen vivir más." },
  { id: 12017, value: 17, title: "Gato doméstico", detail: "Un gato de interior bien cuidado puede superar con frecuencia los quince años." },
  { id: 12018, value: 22, title: "Lince ibérico", detail: "En condiciones de conservación favorables puede superar los veinte años." },
  { id: 12019, value: 28, title: "Dragón de Komodo", detail: "Este gran varano suele vivir alrededor de treinta años en libertad." },
  { id: 12020, value: 36, title: "Águila harpía", detail: "Las grandes rapaces pueden vivir décadas; su reproducción lenta ayuda a explicar esa longevidad." },
  { id: 12021, value: 46, title: "Bisonte americano", detail: "Los bisontes viven unos veinte años en libertad y pueden superar los cuarenta bajo cuidado humano." },
  { id: 12022, value: 58, title: "Hipopótamo común", detail: "Su esperanza de vida ronda los cincuenta y cinco años tanto en libertad como bajo cuidado humano." },
  { id: 12023, value: 72, title: "Elefante africano", detail: "Los elefantes pueden vivir varias décadas, con hembras que alcanzan edades muy avanzadas." },
  { id: 12024, value: 90, title: "Ballena azul", detail: "Las estimaciones de edad sugieren una longevidad típica de ochenta a noventa años." },
  { id: 12025, value: 115, title: "Tortuga gigante de Galápagos", detail: "Estas tortugas pueden superar el siglo de vida y siguen creciendo lentamente durante décadas." },
  { id: 12026, value: 145, title: "Guacamayo rojo", detail: "Los grandes loros pueden vivir más de medio siglo y algunos llegan mucho más lejos en cautividad." },
  { id: 12027, value: 185, title: "Koi", detail: "Estas carpas ornamentales pueden vivir más de un siglo con agua y cuidados excelentes." },
  { id: 12028, value: 235, title: "Ballena boreal", detail: "La especie cuenta con individuos que superan los doscientos años, detectados por métodos biológicos." },
  { id: 12029, value: 300, title: "Tiburón de Groenlandia", detail: "Su crecimiento lentísimo se asocia a una vida de varios siglos; es uno de los vertebrados más longevos." },
  { id: 12030, value: 390, title: "Almeja de Islandia", detail: "La almeja oceánica puede vivir varios siglos; una concha famosa fue fechada en más de quinientos años." },
  { id: 12031, value: 500, title: "Coral negro", detail: "Algunas colonias de coral negro de aguas profundas llevan viviendo más de cuatro siglos." },
  { id: 12032, value: 650, title: "Esponja de vidrio", detail: "Las esponjas de aguas frías crecen tan despacio que algunas se estiman en varios siglos." },
  { id: 12033, value: 850, title: "Esponja antártica", detail: "Su metabolismo extremadamente lento permite estimaciones de longevidad de muchos siglos." },
  { id: 12034, value: 1100, title: "Esponja barril antártica", detail: "Algunas esponjas polares se consideran entre los animales más longevos conocidos." },
  { id: 12035, value: 1450, title: "Coral de bambú", detail: "Los anillos de su esqueleto revelan colonias que han crecido durante más de un milenio." },
  { id: 12036, value: 1900, title: "Coral dorado", detail: "Una colonia de coral profundo puede persistir durante cerca de dos mil años." },
  { id: 12037, value: 2500, title: "Esponja Monorhaphis", detail: "Su larguísima espícula central acumula capas durante milenios en el fondo marino." },
  { id: 12038, value: 3300, title: "Esponja de aguas profundas", detail: "Las estimaciones más altas para algunas esponjas profundas llegan a varios milenios." }
];
