// Historia de la medicina. Se usan hitos concretos y datables —publicación, ensayo,
// demostración, aprobación o intervención— y se evita presentar una sola persona como
// autora de procesos que fueron colectivos.
window.MEDICINE_CARDS = [
  { id: 9001, year: -400, title: "El corpus hipocrático (fecha aproximada)", detail: "Una colección de tratados griegos empieza a explicar la enfermedad mediante observación y causas naturales, no solo religiosas." },
  { id: 9002, year: 1025, title: "El Canon de medicina de Avicena", detail: "La gran síntesis médica de Ibn Sina ordena conocimientos grecorromanos e islámicos y se enseñará durante siglos." },
  { id: 9003, year: 1242, title: "Ibn al-Nafis describe la circulación pulmonar", detail: "Explica que la sangre pasa del corazón a los pulmones y regresa, en vez de atravesar poros invisibles entre los ventrículos." },
  { id: 9004, year: 1543, title: "Vesalio publica De humani corporis fabrica", detail: "Las disecciones humanas y sus ilustraciones corrigen numerosos errores anatómicos heredados de Galeno." },
  { id: 9005, year: 1628, title: "Harvey explica la circulación de la sangre", detail: "William Harvey demuestra que el corazón impulsa la sangre en un circuito continuo por todo el cuerpo." },
  { id: 9006, year: 1665, title: "Micrographia", detail: "Robert Hooke publica dibujos realizados al microscopio y emplea la palabra célula al describir el corcho." },
  { id: 9007, year: 1674, title: "Leeuwenhoek observa microorganismos", detail: "Sus microscopios de una sola lente revelan seres diminutos en agua que el ojo humano nunca había visto." },
  { id: 9008, year: 1721, title: "La variolización llega a Inglaterra", detail: "Lady Mary Wortley Montagu promueve una práctica otomana que reduce el riesgo de morir de viruela, aunque todavía puede transmitirla." },
  { id: 9009, year: 1747, title: "James Lind prueba tratamientos contra el escorbuto", detail: "Compara seis remedios entre marineros y observa que los cítricos producen la recuperación más clara." },
  { id: 9010, year: 1761, title: "Morgagni relaciona síntomas y órganos", detail: "La anatomía patológica moderna nace al comparar lo sufrido por pacientes con lo encontrado después en las autopsias." },
  { id: 9011, year: 1796, title: "Primera vacuna contra la viruela", detail: "Edward Jenner inocula material de viruela vacuna para proteger frente a la viruela humana." },
  { id: 9012, year: 1816, title: "Invención del estetoscopio", detail: "René Laennec enrolla papel para escuchar el pecho de una paciente y después diseña un tubo de madera." },
  { id: 9013, year: 1846, title: "Demostración pública de anestesia con éter", detail: "Una operación sin dolor visible en el Hospital General de Massachusetts impulsa la anestesia quirúrgica." },
  { id: 9014, year: 1847, title: "Semmelweis exige lavarse las manos", detail: "La desinfección con cal clorada reduce de forma drástica la fiebre puerperal en una clínica de Viena." },
  { id: 9015, year: 1854, title: "John Snow rastrea el cólera", detail: "Un mapa de muertes alrededor de una bomba de agua en Londres aporta una prueba decisiva de transmisión por agua contaminada." },
  { id: 9016, year: 1867, title: "Lister publica la cirugía antiséptica", detail: "El uso de ácido carbólico para limpiar heridas e instrumental reduce las infecciones después de operar." },
  { id: 9017, year: 1882, title: "Koch identifica el bacilo de la tuberculosis", detail: "Robert Koch presenta el microorganismo causante de una de las enfermedades más mortales de su tiempo." },
  { id: 9018, year: 1885, title: "Vacuna de Pasteur contra la rabia", detail: "Joseph Meister recibe un tratamiento tras la mordedura de un perro rabioso y sobrevive." },
  { id: 9019, year: 1895, title: "Röntgen descubre los rayos X", detail: "Una radiografía de la mano de su esposa muestra huesos y anillo sin necesidad de abrir el cuerpo." },
  { id: 9020, year: 1901, title: "Descubrimiento de los grupos sanguíneos ABO", detail: "Karl Landsteiner explica por qué algunas transfusiones funcionaban y otras provocaban reacciones mortales." },
  { id: 9021, year: 1921, title: "Aislamiento de la insulina", detail: "El equipo de Toronto obtiene una sustancia pancreática que pronto permitirá tratar una diabetes antes casi siempre mortal." },
  { id: 9022, year: 1928, title: "Fleming observa el efecto de la penicilina", detail: "Un moho contamina una placa y deja a su alrededor una zona sin bacterias, origen del primer gran antibiótico." },
  { id: 9023, year: 1935, title: "El primer antibacteriano de uso amplio", detail: "Los resultados del Prontosil abren la era de las sulfamidas para tratar infecciones bacterianas dentro del cuerpo." },
  { id: 9024, year: 1937, title: "Primer banco de sangre hospitalario de Estados Unidos", detail: "El Cook County Hospital de Chicago organiza sangre almacenada para disponer de ella cuando una transfusión sea urgente." },
  { id: 9025, year: 1943, title: "Primer riñón artificial práctico", detail: "Willem Kolff construye una máquina de diálisis con tubos, madera y un tambor giratorio en los Países Bajos ocupados." },
  { id: 9026, year: 1944, title: "La penicilina llega a producción masiva", detail: "La colaboración científica e industrial permite tratar a gran escala infecciones de soldados y civiles." },
  { id: 9027, year: 1953, title: "Estructura de doble hélice del ADN", detail: "Watson y Crick proponen el modelo apoyándose en datos esenciales de difracción obtenidos por Rosalind Franklin y Maurice Wilkins." },
  { id: 9028, year: 1954, title: "Primer trasplante renal exitoso", detail: "Joseph Murray y su equipo trasplantan un riñón entre gemelos idénticos y evitan así el rechazo inmunitario." },
  { id: 9029, year: 1955, title: "Vacuna de Salk contra la polio", detail: "Un enorme ensayo confirma la eficacia de la vacuna inactivada y comienza una campaña masiva de inmunización." },
  { id: 9030, year: 1958, title: "Primer marcapasos implantable", detail: "En Suecia se implanta un marcapasos diseñado por Rune Elmqvist. El primer dispositivo falla a las pocas horas y debe reemplazarse." },
  { id: 9031, year: 1960, title: "Aprobación de la píldora anticonceptiva", detail: "Estados Unidos autoriza Enovid como anticonceptivo oral y cambia profundamente la planificación familiar." },
  { id: 9032, year: 1967, title: "Primer trasplante humano de corazón", detail: "Christiaan Barnard dirige en Ciudad del Cabo la operación que demuestra la viabilidad técnica del procedimiento." },
  { id: 9033, year: 1971, title: "Primer escáner clínico por tomografía", detail: "Una imagen cerebral obtenida por cortes computarizados inaugura una nueva forma de mirar dentro del cuerpo." },
  { id: 9034, year: 1978, title: "Nace el primer bebé por fecundación in vitro", detail: "Louise Brown nace en Inglaterra después de que la fecundación se realizara fuera del cuerpo." },
  { id: 9035, year: 1980, title: "La viruela queda erradicada", detail: "La Asamblea Mundial de la Salud declara eliminada la primera enfermedad humana vencida mediante una campaña global." },
  { id: 9036, year: 1983, title: "Identificación del virus causante del sida", detail: "Un equipo del Instituto Pasteur aísla el retrovirus que después recibirá el nombre de VIH." },
  { id: 9037, year: 1987, title: "AZT, primer tratamiento aprobado contra el VIH", detail: "El fármaco reduce la reproducción del virus, aunque sus dosis iniciales producen efectos adversos importantes." },
  { id: 9038, year: 1990, title: "Comienza el Proyecto Genoma Humano", detail: "Una colaboración internacional se propone leer y cartografiar el conjunto completo del ADN humano." },
  { id: 9039, year: 1996, title: "Nace la oveja Dolly", detail: "Es el primer mamífero clonado a partir del núcleo de una célula adulta y demuestra que esa célula puede reprogramarse." },
  { id: 9040, year: 1998, title: "Herceptin inaugura una terapia dirigida", detail: "Se aprueba un anticuerpo diseñado para tumores de mama que producen en exceso la proteína HER2." },
  { id: 9041, year: 2003, title: "Finaliza el Proyecto Genoma Humano", detail: "El consorcio internacional anuncia una secuencia de referencia que cubre la gran mayoría del genoma." },
  { id: 9042, year: 2006, title: "Primera vacuna contra el virus del papiloma humano", detail: "La inmunización previene infecciones responsables de la mayoría de los cánceres de cuello uterino." },
  { id: 9043, year: 2010, title: "Primera célula controlada por un genoma sintético", detail: "Un genoma construido en laboratorio toma el control de una célula bacteriana y dirige su reproducción." },
  { id: 9044, year: 2012, title: "CRISPR-Cas9 se convierte en herramienta programable", detail: "Jennifer Doudna, Emmanuelle Charpentier y su equipo muestran cómo guiar la proteína para cortar ADN en un punto elegido." },
  { id: 9045, year: 2020, title: "Vacunas de ARN mensajero contra la COVID-19", detail: "Las primeras vacunas de ARNm autorizadas demuestran que la plataforma puede desarrollarse y fabricarse a gran velocidad." },
  { id: 9046, year: 2022, title: "Primer trasplante de corazón de cerdo modificado", detail: "Un paciente recibe por primera vez un corazón de cerdo con varias ediciones genéticas en una intervención experimental." },
  { id: 9047, year: 2023, title: "Primera terapia CRISPR autorizada", detail: "Reino Unido aprueba un tratamiento que edita células madre de la sangre para combatir anemia falciforme y beta talasemia." },
  { id: 9048, year: 2024, title: "Riñón de cerdo modificado en una persona viva", detail: "Un hospital de Massachusetts realiza el primer trasplante de un riñón porcino editado genéticamente a un receptor vivo." }
];
