window.MOVIE_CARDS = [
  { id: 1001, year: 1902, title: "Viaje a la Luna", detail: "Georges Méliès crea un hito del cine fantástico con el célebre cohete clavado en el ojo de la Luna." },
  { id: 1002, year: 1920, title: "El gabinete del doctor Caligari", detail: "Robert Wiene levanta el expresionismo alemán con decorados torcidos y sombras pintadas." },
  { id: 1003, year: 1925, title: "El acorazado Potemkin", detail: "Serguéi Eisenstein rueda la escalinata de Odesa, la secuencia más copiada de la historia." },
  { id: 1004, year: 1927, title: "Metrópolis", detail: "Fritz Lang imagina una ciudad futura partida entre la élite y los obreros del subsuelo." },
  { id: 1005, year: 1931, title: "Luces de la ciudad", detail: "Charles Chaplin estrena su romance mudo cuando el cine ya hablaba, y gana la apuesta." },
  { id: 1006, year: 1933, title: "King Kong", detail: "El gorila gigante trepa al Empire State en la película que popularizó la animación fotograma a fotograma." },
  { id: 1007, year: 1936, title: "Tiempos modernos", detail: "Chaplin se enreda entre los engranajes de la cadena de montaje." },
  { id: 1008, year: 1937, title: "Blancanieves y los siete enanitos", detail: "Disney arriesga su estudio en el primer largometraje de animación en color." },
  { id: 1009, year: 1939, title: "Lo que el viento se llevó", detail: "Scarlett O'Hara y el incendio de Atlanta en el mayor éxito de taquilla de su tiempo." },
  { id: 1010, year: 1940, title: "El gran dictador", detail: "Chaplin baila con el globo terráqueo y ridiculiza a Hitler en plena guerra." },
  { id: 1011, year: 1941, title: "Ciudadano Kane", detail: "Orson Welles debuta a los 25 años con «Rosebud» y cambia el lenguaje del cine." },
  { id: 1012, year: 1942, title: "Casablanca", detail: "Bogart e Ingrid Bergman se despiden en la niebla del aeropuerto." },
  { id: 1013, year: 1946, title: "¡Qué bello es vivir!", detail: "Frank Capra manda un ángel a rescatar a James Stewart en Nochebuena." },
  { id: 1014, year: 1948, title: "Ladrón de bicicletas", detail: "Vittorio De Sica firma la cumbre del neorrealismo italiano con actores no profesionales." },
  { id: 1015, year: 1950, title: "La Cenicienta", detail: "Disney recupera el pulso de posguerra con el zapato de cristal y «Bibbidi-Bobbidi-Boo»." },
  { id: 1016, year: 1952, title: "Cantando bajo la lluvia", detail: "Gene Kelly baila con paraguas mientras Hollywood pasa del mudo al sonoro." },
  { id: 1017, year: 1953, title: "¡Bienvenido, Míster Marshall!", detail: "Luis García Berlanga disfraza de andaluz a un pueblo castellano para recibir el Plan Marshall." },
  { id: 1018, year: 1954, title: "La ventana indiscreta", detail: "Hitchcock encierra a James Stewart en una silla de ruedas espiando el patio de vecinos." },
  { id: 1019, year: 1955, title: "Rebelde sin causa", detail: "James Dean convierte la cazadora roja en el uniforme de una generación." },
  { id: 1020, year: 1956, title: "Los diez mandamientos", detail: "Cecil B. DeMille abre el mar Rojo con Charlton Heston al frente." },
  { id: 1021, year: 1957, title: "Doce hombres sin piedad", detail: "Sidney Lumet resuelve un juicio entero dentro de una sala de deliberaciones." },
  { id: 1022, year: 1958, title: "Vértigo (De entre los muertos)", detail: "El efecto de zoom contrario lo resuelve Irmin Roberts, cámara de segunda unidad, a petición de Hitchcock, para filmar el miedo a las alturas. Roberts no figura en los créditos." },
  { id: 1023, year: 1959, title: "Con faldas y a lo loco", detail: "Billy Wilder viste de mujer a Curtis y Lemmon y cierra con «nadie es perfecto»." },
  { id: 1024, year: 1960, title: "Psicosis", detail: "La ducha del motel Bates y los violines de Bernard Herrmann fundan el cine de terror moderno." },
  { id: 1025, year: 1961, title: "Viridiana", detail: "Luis Buñuel gana la Palma de Oro con una película prohibida de inmediato en España." },
  { id: 1026, year: 1962, title: "Lawrence de Arabia", detail: "David Lean rueda el desierto en 70 mm, buena parte de él en Almería." },
  { id: 1027, year: 1963, title: "El verdugo", detail: "Berlanga y Azcona convierten la pena de muerte en una comedia negra insoportablemente lúcida." },
  { id: 1028, year: 1964, title: "Mary Poppins", detail: "Julie Andrews aterriza con paraguas y mezcla actores reales con dibujos animados." },
  { id: 1029, year: 1965, title: "Sonrisas y lágrimas", detail: "La familia Von Trapp canta en los Alpes y huye de la Austria anexionada." },
  { id: 1030, year: 1966, title: "El bueno, el feo y el malo", detail: "Sergio Leone cierra su trilogía del dólar con el duelo final del cementerio de Sad Hill, rodado en Burgos." },
  { id: 1031, year: 1967, title: "El libro de la selva", detail: "El último largometraje supervisado por Walt Disney en persona." },
  { id: 1032, year: 1968, title: "2001: Una odisea del espacio", detail: "Kubrick salta del hueso al satélite y presenta a HAL 9000." },
  { id: 1033, year: 1970, title: "Tristana", detail: "Buñuel dirige a Catherine Deneuve y Fernando Rey en un Toledo asfixiante." },
  { id: 1034, year: 1971, title: "La naranja mecánica", detail: "Kubrick adapta a Anthony Burgess y provoca un escándalo que dura décadas." },
  { id: 1035, year: 1972, title: "El padrino", detail: "Coppola convierte a Marlon Brando en Vito Corleone." },
  { id: 1036, year: 1973, title: "El exorcista", detail: "William Friedkin lleva el terror a las salas y provoca desmayos en las colas." },
  { id: 1037, year: 1974, title: "El padrino. Parte II", detail: "Coppola cuenta a la vez el ascenso del joven Vito y la caída moral de Michael." },
  { id: 1038, year: 1975, title: "Tiburón", detail: "Universal la estrena en más de 400 salas con una campaña de televisión sin precedentes y fija el modelo del gran estreno de verano. La decisión fue de la dirección del estudio, y el estreno masivo ya existía: El proceso de Billy Jack había abierto en más de mil salas en 1974. El tiburón mecánico casi nunca funcionaba." },
  { id: 1039, year: 1976, title: "Rocky", detail: "Sylvester Stallone escribió el guion en tres días y exigió protagonizarlo." },
  { id: 1040, year: 1977, title: "La guerra de las galaxias", detail: "George Lucas estrena su aventura espacial, respaldada por Alan Ladd Jr. pese a las dudas de otros ejecutivos de Fox." },
  { id: 1041, year: 1978, title: "Grease", detail: "Travolta y Olivia Newton-John convierten el instituto Rydell en un fenómeno mundial." },
  { id: 1042, year: 1979, title: "Alien, el octavo pasajero", detail: "Ridley Scott y H. R. Giger encierran a Ripley con un monstruo en la nave Nostromo." },
  { id: 1043, year: 1980, title: "El resplandor", detail: "Kubrick utiliza la Steadicam para recorrer los pasillos del hotel Overlook; el sistema ya se había empleado en películas de 1976." },
  { id: 1044, year: 1981, title: "En busca del arca perdida", detail: "Spielberg y Lucas presentan a Indiana Jones y su látigo." },
  { id: 1045, year: 1982, title: "E.T., el extraterrestre", detail: "La bicicleta cruza la luna llena en la película más taquillera de la década." },
  { id: 1046, year: 1983, title: "El retorno del Jedi", detail: "Luke se enfrenta al Emperador y la trilogía original se cierra en Endor." },
  { id: 1047, year: 1984, title: "Los santos inocentes", detail: "Mario Camus adapta a Delibes; Paco Rabal y Alfredo Landa comparten premio en Cannes." },
  { id: 1048, year: 1985, title: "Regreso al futuro", detail: "Un DeLorean alcanza las 88 millas por hora y viaja a 1955." },
  { id: 1049, year: 1986, title: "Top Gun", detail: "Tom Cruise vuela en F-14 y dispara las solicitudes de ingreso en la Marina estadounidense." },
  { id: 1050, year: 1987, title: "Dirty Dancing", detail: "Patrick Swayze levanta a Jennifer Grey en el número final de un hotel de los Catskills." },
  { id: 1051, year: 1988, title: "Mujeres al borde de un ataque de nervios", detail: "Pedro Almodóvar da el salto internacional con Carmen Maura y un gazpacho con somníferos." },
  { id: 1052, year: 1989, title: "La sirenita", detail: "Sebastián canta «Bajo el mar» a Ariel en la película que impulsa el renacimiento de la animación Disney." },
  { id: 1053, year: 1990, title: "Solo en casa", detail: "Macaulay Culkin defiende su casa de dos ladrones torpes en Navidad." },
  { id: 1054, year: 1991, title: "El silencio de los corderos", detail: "Anthony Hopkins interpreta a Hannibal Lecter y gana el Óscar al mejor actor en la ceremonia de 1992." },
  { id: 1055, year: 1992, title: "Aladdín", detail: "Robin Williams improvisa al Genio y cambia el doblaje de la animación para siempre." },
  { id: 1056, year: 1993, title: "Parque Jurásico", detail: "Spielberg mezcla animatrónicos e imagen digital y el vaso de agua tiembla." },
  { id: 1057, year: 1994, title: "El rey león", detail: "Simba, Mufasa y el «Hakuna matata» arrasan en todo el mundo." },
  { id: 1058, year: 1995, title: "Toy Story", detail: "Pixar estrena el primer largometraje hecho íntegramente por ordenador." },
  { id: 1059, year: 1996, title: "Independence Day", detail: "Roland Emmerich vuela la Casa Blanca y devuelve la moda del cine catastrofista." },
  { id: 1060, year: 1997, title: "Titanic", detail: "La película de James Cameron alcanza un récord de taquilla y, en 1998, gana once Óscars, igualando la marca de «Ben-Hur»." },
  { id: 1061, year: 1998, title: "Salvar al soldado Ryan", detail: "Spielberg abre con veinte minutos de desembarco en Omaha Beach." },
  { id: 1062, year: 1999, title: "Matrix", detail: "Las hermanas Wachowski popularizan el «bullet time» y la pastilla roja." },
  { id: 1063, year: 2000, title: "Gladiator", detail: "Ridley Scott devuelve el cine de romanos con Russell Crowe en el Coliseo." },
  { id: 1064, year: 2001, title: "El señor de los anillos: La comunidad del anillo", detail: "Peter Jackson estrena en Nueva Zelanda la primera parte de la trilogía." },
  { id: 1065, year: 2002, title: "Spider-Man", detail: "Sam Raimi inaugura la era moderna del superhéroe en taquilla." },
  { id: 1066, year: 2003, title: "Buscando a Nemo", detail: "Pixar cruza el océano detrás de un pez payaso y una amiga sin memoria." },
  { id: 1067, year: 2004, title: "Mar adentro", detail: "Alejandro Amenábar cuenta la historia de Ramón Sampedro y gana el Óscar a la mejor película extranjera." },
  { id: 1068, year: 2005, title: "Batman Begins", detail: "Christopher Nolan reinicia Batman con un tono realista." },
  { id: 1069, year: 2006, title: "El laberinto del fauno", detail: "Guillermo del Toro mezcla maquis y cuento oscuro en una coproducción hispano-mexicana." },
  { id: 1070, year: 2007, title: "El orfanato", detail: "J. A. Bayona debuta con el mayor éxito del terror español en salas." },
  { id: 1071, year: 2008, title: "El caballero oscuro", detail: "Heath Ledger convierte al Joker en un papel póstumo premiado con el Óscar." },
  { id: 1072, year: 2009, title: "Avatar", detail: "La película de James Cameron populariza el cine comercial en 3D digital." },
  { id: 1073, year: 2010, title: "Origen", detail: "Nolan encadena sueños dentro de sueños y deja la peonza girando." },
  { id: 1074, year: 2011, title: "Harry Potter y las reliquias de la Muerte. Parte 2", detail: "La saga se despide tras diez años y ocho películas." },
  { id: 1075, year: 2012, title: "Los Vengadores", detail: "Marvel reúne por fin a sus héroes y consolida el universo compartido." },
  { id: 1076, year: 2013, title: "Frozen: El reino del hielo", detail: "«Let it go» se cuela en todas las casas del planeta." },
  { id: 1077, year: 2014, title: "Ocho apellidos vascos", detail: "Emilio Martínez-Lázaro firma la comedia española más taquillera de la historia." },
  { id: 1078, year: 2015, title: "Del revés (Inside Out)", detail: "Pixar se mete en la cabeza de una niña y da voz a sus cinco emociones." },
  { id: 1079, year: 2016, title: "La La Land", detail: "Damien Chazelle rescata el musical y protagoniza el mayor error de sobre de los Óscar." },
  { id: 1080, year: 2017, title: "Coco", detail: "Pixar viaja al Día de Muertos mexicano con «Recuérdame»." },
  { id: 1081, year: 2018, title: "Campeones", detail: "Javier Fesser gana el Goya con un equipo de baloncesto de jugadores con discapacidad intelectual." },
  { id: 1082, year: 2019, title: "Parásitos", detail: "La película de Bong Joon-ho se convierte en la primera de habla no inglesa en ganar el Óscar a mejor película, en la ceremonia de 2020." },
  { id: 1083, year: 2020, title: "Soul", detail: "Pixar estrena la película en Disney+ en España y otros mercados; en países sin el servicio también tiene estreno en cines." },
  { id: 1084, year: 2021, title: "El buen patrón", detail: "Fernando León de Aranoa dirige a Javier Bardem y bate el récord de nominaciones a los Goya." },
  { id: 1085, year: 2022, title: "As bestas", detail: "Rodrigo Sorogoyen dirige un thriller rural con diálogos en francés, castellano y gallego que triunfa en los Goya." },
  { id: 1086, year: 2023, title: "Barbie", detail: "Greta Gerwig tiñe el verano de rosa y lidera la taquilla mundial del año." },
  { id: 1087, year: 2024, title: "Del revés 2 (Inside Out 2)", detail: "La secuela incorpora a Ansiedad a las emociones de Riley y se convierte en uno de los grandes éxitos de taquilla de 2024." }
];
