window.MOVIE_CARDS = [
  { id: 1001, year: 1902, title: "Viaje a la Luna", detail: "Georges Méliès estrena una de las obras fundacionales del cine fantástico y de los efectos visuales." },
  { id: 1002, year: 1903, title: "Asalto y robo de un tren", detail: "El corto de Edwin S. Porter se convierte en una referencia temprana del cine narrativo estadounidense." },
  { id: 1003, year: 1914, title: "Cabiria", detail: "La superproducción italiana de Giovanni Pastrone destaca por sus decorados y movimientos de cámara." },
  { id: 1004, year: 1916, title: "Intolerancia", detail: "D. W. Griffith entrelaza cuatro relatos históricos mediante un montaje muy ambicioso para su época." },
  { id: 1005, year: 1920, title: "El gabinete del doctor Caligari", detail: "Robert Wiene firma una obra esencial del expresionismo alemán." },
  { id: 1006, year: 1922, title: "Nosferatu", detail: "F. W. Murnau lleva el mito de Drácula al cine en uno de los grandes clásicos del terror mudo." },
  { id: 1007, year: 1925, title: "El acorazado Potemkin", detail: "Serguéi Eisenstein convierte la rebelión de un buque ruso en una lección de montaje cinematográfico." },
  { id: 1008, year: 1926, title: "El maquinista de La General", detail: "Buster Keaton combina comedia, acción y precisión visual alrededor de una locomotora." },
  { id: 1009, year: 1927, title: "Metrópolis", detail: "Fritz Lang imagina una ciudad futurista que marcará para siempre la ciencia ficción visual." },
  { id: 1010, year: 1927, title: "El cantor de jazz", detail: "La película populariza el cine sonoro sincronizado y acelera el final de la era muda." },
  { id: 1011, year: 1929, title: "Un perro andaluz", detail: "Luis Buñuel y Salvador Dalí presentan un cortometraje surrealista de imágenes inolvidables." },
  { id: 1012, year: 1931, title: "Luces de la ciudad", detail: "Charles Chaplin mezcla romanticismo y comedia en una de las cumbres de su personaje Charlot." },
  { id: 1013, year: 1933, title: "King Kong", detail: "El gigantesco simio de Willis O'Brien asombra al público gracias a la animación fotograma a fotograma." },
  { id: 1014, year: 1936, title: "Tiempos modernos", detail: "Chaplin satiriza el trabajo industrial y la mecanización en plena Gran Depresión." },
  { id: 1015, year: 1937, title: "Blancanieves y los siete enanitos", detail: "Disney estrena su primer largometraje de animación y transforma la industria del género." },
  { id: 1016, year: 1939, title: "El mago de Oz", detail: "Dorothy viaja al colorido mundo de Oz en uno de los musicales más recordados de Hollywood." },
  { id: 1017, year: 1939, title: "Lo que el viento se llevó", detail: "La adaptación de la novela de Margaret Mitchell se convierte en un enorme fenómeno comercial." },
  { id: 1018, year: 1941, title: "Ciudadano Kane", detail: "Orson Welles debuta en el largometraje con una estructura y una fotografía profundamente influyentes." },
  { id: 1019, year: 1942, title: "Casablanca", detail: "Humphrey Bogart e Ingrid Bergman protagonizan un romance marcado por la Segunda Guerra Mundial." },
  { id: 1020, year: 1946, title: "¡Qué bello es vivir!", detail: "Frank Capra narra cómo George Bailey descubre el valor que ha tenido su vida para los demás." },
  { id: 1021, year: 1948, title: "Ladrón de bicicletas", detail: "Vittorio De Sica convierte la búsqueda de una bicicleta en emblema del neorrealismo italiano." },
  { id: 1022, year: 1949, title: "El tercer hombre", detail: "Carol Reed rueda un célebre thriller entre las ruinas y sombras de la Viena de posguerra." },
  { id: 1023, year: 1950, title: "Rashōmon", detail: "Akira Kurosawa relata un mismo crimen desde versiones incompatibles y alcanza reconocimiento mundial." },
  { id: 1024, year: 1952, title: "Cantando bajo la lluvia", detail: "Gene Kelly y Stanley Donen celebran con humor el paso de Hollywood del cine mudo al sonoro." },
  { id: 1025, year: 1953, title: "Bienvenido, Mister Marshall", detail: "Luis García Berlanga retrata con ironía las esperanzas de un pueblo español ante la ayuda estadounidense." },
  { id: 1026, year: 1954, title: "Los siete samuráis", detail: "Kurosawa reúne a siete guerreros para defender una aldea y redefine el cine de aventuras." },
  { id: 1027, year: 1954, title: "La ventana indiscreta", detail: "Alfred Hitchcock convierte la observación de los vecinos en un brillante ejercicio de suspense." },
  { id: 1028, year: 1955, title: "La noche del cazador", detail: "Charles Laughton dirige una fábula oscura protagonizada por un inquietante Robert Mitchum." },
  { id: 1029, year: 1956, title: "Centauros del desierto", detail: "John Ford y John Wayne exploran la obsesión y el racismo dentro del wéstern clásico." },
  { id: 1030, year: 1957, title: "Doce hombres sin piedad", detail: "Sidney Lumet concentra el drama en un jurado que debe decidir el destino de un acusado." },
  { id: 1031, year: 1959, title: "Los 400 golpes", detail: "François Truffaut presenta a Antoine Doinel e impulsa la Nouvelle Vague francesa." },
  { id: 1032, year: 1959, title: "Con faldas y a lo loco", detail: "Billy Wilder reúne a Marilyn Monroe, Tony Curtis y Jack Lemmon en una comedia clásica." },
  { id: 1033, year: 1960, title: "Psicosis", detail: "Hitchcock sorprende al público con el motel Bates y una nueva forma de entender el terror." },
  { id: 1034, year: 1960, title: "Al final de la escapada", detail: "Jean-Luc Godard rompe convenciones narrativas y de montaje en una obra clave de la Nouvelle Vague." },
  { id: 1035, year: 1961, title: "Viridiana", detail: "Luis Buñuel gana la Palma de Oro con una sátira que provocó una fuerte polémica en España." },
  { id: 1036, year: 1961, title: "West Side Story", detail: "El musical traslada Romeo y Julieta a las calles de Nueva York y triunfa en los Óscar." },
  { id: 1037, year: 1962, title: "Lawrence de Arabia", detail: "David Lean convierte la vida de T. E. Lawrence en un gran espectáculo épico filmado en el desierto." },
  { id: 1038, year: 1963, title: "Fellini 8½", detail: "Federico Fellini transforma una crisis creativa en una película libre, onírica y autorreferencial." },
  { id: 1039, year: 1964, title: "¿Teléfono rojo? Volamos hacia Moscú", detail: "Stanley Kubrick satiriza la lógica de la guerra nuclear durante la Guerra Fría." },
  { id: 1040, year: 1965, title: "Sonrisas y lágrimas", detail: "Julie Andrews protagoniza el musical de la familia von Trapp en los Alpes austríacos." },
  { id: 1041, year: 1966, title: "El bueno, el feo y el malo", detail: "Sergio Leone culmina su trilogía del dólar con música inolvidable de Ennio Morricone." },
  { id: 1042, year: 1968, title: "2001: Una odisea del espacio", detail: "Kubrick y Arthur C. Clarke exploran la evolución humana y la inteligencia artificial." },
  { id: 1043, year: 1968, title: "La noche de los muertos vivientes", detail: "George A. Romero establece muchas de las reglas modernas del cine de zombis." },
  { id: 1044, year: 1972, title: "El padrino", detail: "Francis Ford Coppola adapta la saga de los Corleone y crea un referente del cine criminal." },
  { id: 1045, year: 1973, title: "El espíritu de la colmena", detail: "Víctor Erice observa la infancia y la posguerra española a través de la mirada de Ana." },
  { id: 1046, year: 1973, title: "El exorcista", detail: "William Friedkin convierte una posesión demoníaca en un fenómeno cultural del cine de terror." },
  { id: 1047, year: 1975, title: "Tiburón", detail: "Steven Spielberg transforma el miedo a un gran tiburón en el modelo del éxito veraniego moderno." },
  { id: 1048, year: 1976, title: "Cría cuervos", detail: "Carlos Saura mezcla memoria, infancia y heridas familiares en los últimos años del franquismo." },
  { id: 1049, year: 1976, title: "Rocky", detail: "Sylvester Stallone encarna a un boxeador humilde ante la oportunidad de su vida." },
  { id: 1050, year: 1977, title: "La guerra de las galaxias", detail: "George Lucas inicia una aventura espacial que cambia los efectos visuales y el cine comercial." },
  { id: 1051, year: 1979, title: "Alien, el octavo pasajero", detail: "Ridley Scott combina ciencia ficción y terror dentro de la nave Nostromo." },
  { id: 1052, year: 1980, title: "El resplandor", detail: "Kubrick adapta a Stephen King y convierte el hotel Overlook en icono del terror." },
  { id: 1053, year: 1981, title: "En busca del arca perdida", detail: "Spielberg y Lucas presentan al arqueólogo aventurero Indiana Jones." },
  { id: 1054, year: 1982, title: "Blade Runner", detail: "Ridley Scott imagina un futuro noir que se volverá esencial para la ciencia ficción." },
  { id: 1055, year: 1982, title: "E.T., el extraterrestre", detail: "La amistad entre Elliott y un visitante de otro planeta emociona a públicos de todo el mundo." },
  { id: 1056, year: 1984, title: "Terminator", detail: "James Cameron enfrenta a Sarah Connor con un asesino cibernético llegado del futuro." },
  { id: 1057, year: 1985, title: "Regreso al futuro", detail: "Marty McFly viaja a 1955 en un DeLorean y pone en peligro su propia existencia." },
  { id: 1058, year: 1987, title: "La princesa prometida", detail: "Rob Reiner combina cuento, aventura, romance y humor en una película de culto." },
  { id: 1059, year: 1988, title: "Cinema Paradiso", detail: "Giuseppe Tornatore celebra el amor por el cine a través de la amistad entre Totò y Alfredo." },
  { id: 1060, year: 1988, title: "Mujeres al borde de un ataque de nervios", detail: "Pedro Almodóvar mezcla melodrama y comedia en el Madrid de finales de los ochenta." },
  { id: 1061, year: 1989, title: "Batman", detail: "Tim Burton lleva al héroe de Gotham a una superproducción gótica protagonizada por Michael Keaton." },
  { id: 1062, year: 1990, title: "Uno de los nuestros", detail: "Martin Scorsese sigue durante décadas el ascenso y caída de Henry Hill dentro de la mafia." },
  { id: 1063, year: 1991, title: "El silencio de los corderos", detail: "Clarice Starling busca la ayuda de Hannibal Lecter para atrapar a un asesino en serie." },
  { id: 1064, year: 1993, title: "Parque Jurásico", detail: "Spielberg combina animatrónica e imágenes digitales para devolver los dinosaurios a la vida." },
  { id: 1065, year: 1993, title: "La lista de Schindler", detail: "Spielberg narra en blanco y negro cómo Oskar Schindler salvó a más de mil judíos del Holocausto." },
  { id: 1066, year: 1994, title: "Pulp Fiction", detail: "Quentin Tarantino entrecruza historias criminales con diálogos, humor y una estructura no lineal." },
  { id: 1067, year: 1994, title: "El rey león", detail: "Disney traslada un drama de crecimiento y poder a la sabana africana." },
  { id: 1068, year: 1995, title: "Toy Story", detail: "Pixar estrena el primer largometraje realizado completamente mediante animación digital." },
  { id: 1069, year: 1996, title: "Tesis", detail: "Alejandro Amenábar debuta con un thriller sobre la violencia audiovisual y las películas clandestinas." },
  { id: 1070, year: 1996, title: "Fargo", detail: "Los hermanos Coen mezclan crimen, humor negro y paisaje nevado en Minnesota." },
  { id: 1071, year: 1997, title: "Titanic", detail: "James Cameron combina una historia romántica con la recreación del hundimiento del transatlántico." },
  { id: 1072, year: 1998, title: "El show de Truman", detail: "Jim Carrey interpreta a un hombre cuya vida entera es un programa de televisión." },
  { id: 1073, year: 1999, title: "Matrix", detail: "Las Wachowski mezclan acción, filosofía y efectos innovadores alrededor de una realidad simulada." },
  { id: 1074, year: 2000, title: "Gladiator", detail: "Ridley Scott revive el cine épico romano con la historia del general Máximo." },
  { id: 1075, year: 2001, title: "El viaje de Chihiro", detail: "Hayao Miyazaki acompaña a Chihiro por un mundo de espíritus y gana reconocimiento internacional." },
  { id: 1076, year: 2001, title: "El señor de los anillos: La comunidad del anillo", detail: "Peter Jackson inicia en la Tierra Media una de las grandes trilogías del cine fantástico." },
  { id: 1077, year: 2001, title: "Los otros", detail: "Alejandro Amenábar encierra a Nicole Kidman y sus hijos en una mansión llena de secretos." },
  { id: 1078, year: 2002, title: "Ciudad de Dios", detail: "Fernando Meirelles y Kátia Lund recorren décadas de violencia en una favela de Río de Janeiro." },
  { id: 1079, year: 2003, title: "Buscando a Nemo", detail: "Pixar lleva a Marlin a cruzar el océano para encontrar a su hijo desaparecido." },
  { id: 1080, year: 2003, title: "Oldboy", detail: "Park Chan-wook construye un intenso relato de cautiverio, investigación y venganza." },
  { id: 1081, year: 2004, title: "Mar adentro", detail: "Amenábar relata la lucha de Ramón Sampedro por decidir sobre su propia vida." },
  { id: 1082, year: 2004, title: "Los increíbles", detail: "Brad Bird presenta para Pixar a una familia de superhéroes obligada a ocultar sus poderes." },
  { id: 1083, year: 2006, title: "El laberinto del fauno", detail: "Guillermo del Toro mezcla la posguerra española con una oscura fantasía protagonizada por Ofelia." },
  { id: 1084, year: 2007, title: "El orfanato", detail: "J. A. Bayona debuta con una historia de misterio y pérdida protagonizada por Belén Rueda." },
  { id: 1085, year: 2008, title: "El caballero oscuro", detail: "Christopher Nolan enfrenta a Batman con el Joker interpretado por Heath Ledger." },
  { id: 1086, year: 2009, title: "Up", detail: "Pixar hace volar la casa de Carl Fredricksen rumbo a Sudamérica con Russell como polizón." },
  { id: 1087, year: 2010, title: "Origen", detail: "Christopher Nolan construye un thriller de espionaje dentro de sueños compartidos." },
  { id: 1088, year: 2011, title: "Intocable", detail: "La comedia francesa narra la amistad entre Philippe y Driss y alcanza un enorme éxito internacional." },
  { id: 1089, year: 2012, title: "Los Vengadores", detail: "Marvel reúne a sus principales superhéroes en una misma película dirigida por Joss Whedon." },
  { id: 1090, year: 2013, title: "Her", detail: "Spike Jonze imagina el vínculo sentimental entre un hombre y un sistema operativo." },
  { id: 1091, year: 2014, title: "Interstellar", detail: "Un grupo de astronautas cruza un agujero de gusano en busca de un futuro para la humanidad." },
  { id: 1092, year: 2015, title: "Mad Max: Furia en la carretera", detail: "George Miller regresa al desierto con una persecución de acción dominada por Furiosa." },
  { id: 1093, year: 2016, title: "La ciudad de las estrellas: La La Land", detail: "Damien Chazelle convierte los sueños de Mia y Sebastian en un musical contemporáneo." },
  { id: 1094, year: 2017, title: "Déjame salir", detail: "Jordan Peele combina terror y sátira social durante una inquietante visita familiar." },
  { id: 1095, year: 2018, title: "Campeones", detail: "Javier Fesser dirige una comedia sobre un entrenador y un equipo de baloncesto muy especial." },
  { id: 1096, year: 2018, title: "Roma", detail: "Alfonso Cuarón recrea recuerdos de infancia en el México de los años setenta." },
  { id: 1097, year: 2019, title: "Parásitos", detail: "Bong Joon-ho mezcla comedia, suspense y crítica social y conquista la Palma de Oro y el Óscar." },
  { id: 1098, year: 2021, title: "Dune", detail: "Denis Villeneuve lleva Arrakis a la gran pantalla en una nueva adaptación de la novela de Frank Herbert." },
  { id: 1099, year: 2022, title: "Alcarràs", detail: "Carla Simón retrata a una familia de agricultores catalanes y gana el Oso de Oro de Berlín." },
  { id: 1100, year: 2022, title: "Todo a la vez en todas partes", detail: "Daniels combinan multiversos, acción y drama familiar en una película ganadora del Óscar." },
  { id: 1101, year: 2023, title: "La sociedad de la nieve", detail: "J. A. Bayona reconstruye la supervivencia de los pasajeros del vuelo 571 en los Andes." },
  { id: 1102, year: 2023, title: "Oppenheimer", detail: "Christopher Nolan narra el papel del físico J. Robert Oppenheimer en el desarrollo de la bomba atómica." },
  { id: 1103, year: 2024, title: "Dune: Parte Dos", detail: "Paul Atreides se une a los fremen mientras Villeneuve completa la segunda parte de su adaptación." }
];

