// Historia mundial. Tercer juego del bloque de Historia, junto a la historia de España y
// los inventos, y con los mismos dos criterios que aquel: fechas de hechos concretos y
// ningún año repetido, para que ninguna pareja de cartas se acierte por suerte. Donde la
// fecha es tradicional o aproximada, lo dice el propio título.
//
// El mazo evita a propósito los hitos técnicos y científicos, que son el juego de al
// lado, y mira más allá de España, que tiene el suyo.
window.WORLD_CARDS = [
  { id: 5001, year: -3100, title: "La unificación de Egipto (fecha aproximada)", detail: "El Alto y el Bajo Egipto quedan bajo un solo rey y arranca el linaje de los faraones." },
  { id: 5002, year: -2560, title: "La Gran Pirámide de Guiza (fecha aproximada)", detail: "La tumba de Keops: durante casi cuatro mil años, el edificio más alto del mundo." },
  { id: 5003, year: -1274, title: "La batalla de Qadesh", detail: "Egipcios e hititas chocan en Siria y firman después el primer tratado de paz conservado." },
  { id: 5004, year: -1200, title: "El colapso de la Edad del Bronce (fecha aproximada)", detail: "En pocas décadas caen casi todas las grandes ciudades del Mediterráneo oriental." },
  { id: 5005, year: -753, title: "La fundación de Roma (fecha tradicional)", detail: "La tradición fija en este año la fundación de la ciudad por Rómulo." },
  { id: 5006, year: -586, title: "La destrucción del Primer Templo de Jerusalén", detail: "Nabucodonosor arrasa la ciudad y comienza el exilio de Babilonia." },
  { id: 5007, year: -539, title: "Ciro el Grande conquista Babilonia", detail: "El Imperio persa se convierte en el mayor que ha visto el mundo hasta entonces." },
  { id: 5008, year: -509, title: "Nace la República romana (fecha tradicional)", detail: "Roma expulsa a su último rey y se dota de cónsules elegidos cada año." },
  { id: 5009, year: -490, title: "La batalla de Maratón", detail: "Atenas detiene a los persas en la llanura que dio nombre a la carrera." },
  { id: 5010, year: -480, title: "Las Termópilas y Salamina", detail: "Trescientos espartanos frenan el paso y la flota griega vence poco después en Salamina." },
  { id: 5011, year: -431, title: "Empieza la guerra del Peloponeso", detail: "Atenas y Esparta se enfrentan durante veintisiete años y Grecia sale agotada." },
  { id: 5012, year: -399, title: "La muerte de Sócrates", detail: "Condenado por corromper a la juventud, bebe la cicuta en Atenas." },
  { id: 5013, year: -331, title: "La batalla de Gaugamela", detail: "Alejandro derrota a Darío III y el Imperio persa queda en sus manos." },
  { id: 5014, year: -323, title: "La muerte de Alejandro Magno", detail: "Muere en Babilonia a los 32 años y sus generales se reparten el imperio." },
  { id: 5015, year: -264, title: "Empieza la primera guerra púnica", detail: "Roma y Cartago se disputan Sicilia y el dominio del Mediterráneo occidental." },
  { id: 5016, year: -216, title: "La batalla de Cannas", detail: "Aníbal envuelve y destruye al mayor ejército que Roma había reunido nunca." },
  { id: 5017, year: -146, title: "La destrucción de Cartago", detail: "Roma arrasa la ciudad rival y el mismo año somete Grecia." },
  { id: 5018, year: -44, title: "El asesinato de Julio César", detail: "Apuñalado en el Senado en los idus de marzo, semanas después de ser nombrado dictador perpetuo." },
  { id: 5019, year: -31, title: "La batalla de Accio", detail: "Octavio derrota a Marco Antonio y Cleopatra, y Egipto pasa a ser provincia romana." },
  { id: 5020, year: -27, title: "Augusto, el primer emperador", detail: "El Senado le concede el título y la República romana se convierte en Imperio." },
  { id: 5021, year: 64, title: "El gran incendio de Roma", detail: "Arde buena parte de la ciudad y Nerón culpa a los cristianos." },
  { id: 5022, year: 79, title: "La erupción del Vesubio", detail: "Pompeya y Herculano quedan sepultadas bajo ceniza, y con ellas la vida cotidiana romana." },
  { id: 5023, year: 117, title: "La máxima extensión del Imperio romano", detail: "A la muerte de Trajano, el Imperio llega del Atlántico al golfo Pérsico." },
  { id: 5024, year: 313, title: "El edicto de Milán", detail: "Constantino y Licinio conceden libertad de culto y el cristianismo deja de ser perseguido." },
  { id: 5025, year: 325, title: "El concilio de Nicea", detail: "La primera asamblea de obispos de todo el Imperio fija el credo cristiano." },
  { id: 5026, year: 330, title: "Constantinopla, la nueva Roma", detail: "Constantino traslada la capital del Imperio al Bósforo." },
  { id: 5027, year: 395, title: "La división definitiva del Imperio romano", detail: "A la muerte de Teodosio, Oriente y Occidente ya no vuelven a unirse." },
  { id: 5028, year: 410, title: "El saqueo de Roma por los visigodos", detail: "Alarico entra en la ciudad; era la primera vez en ochocientos años." },
  { id: 5029, year: 476, title: "Cae el Imperio romano de Occidente", detail: "Odoacro depone al último emperador y devuelve las insignias a Constantinopla." },
  { id: 5030, year: 529, title: "El Código de Justiniano", detail: "El emperador ordena todo el derecho romano en un cuerpo único que llegará hasta hoy." },
  { id: 5031, year: 622, title: "La Hégira", detail: "Mahoma emigra de La Meca a Medina y con ese año empieza el calendario musulmán." },
  { id: 5032, year: 732, title: "La batalla de Poitiers", detail: "Carlos Martel detiene el avance musulmán en el corazón de la Galia." },
  { id: 5033, year: 800, title: "Carlomagno, emperador", detail: "El papa lo corona en Roma la noche de Navidad y renace la idea de imperio en Occidente." },
  { id: 5034, year: 843, title: "El tratado de Verdún", detail: "El imperio carolingio se reparte entre tres nietos y de ahí saldrán Francia y Alemania." },
  { id: 5035, year: 1054, title: "El Cisma de Oriente", detail: "Roma y Constantinopla se excomulgan mutuamente y la cristiandad se parte en dos." },
  { id: 5036, year: 1066, title: "La batalla de Hastings", detail: "Guillermo de Normandía conquista Inglaterra y cambia su lengua y su nobleza." },
  { id: 5037, year: 1095, title: "Urbano II predica la primera cruzada", detail: "En Clermont llama a rescatar Jerusalén y la multitud responde «Dios lo quiere»." },
  { id: 5038, year: 1099, title: "Los cruzados toman Jerusalén", detail: "Tras un mes de asedio, la ciudad cae y se funda un reino latino en Oriente." },
  { id: 5039, year: 1206, title: "Gengis Kan unifica a los mongoles", detail: "Las tribus de la estepa lo proclaman kan y empieza el mayor imperio terrestre de la historia." },
  { id: 5040, year: 1215, title: "La Carta Magna", detail: "Los barones ingleses obligan al rey Juan a aceptar límites a su poder por escrito." },
  { id: 5041, year: 1258, title: "Los mongoles saquean Bagdad", detail: "Cae el califato abasí y con él la mayor biblioteca del mundo islámico." },
  { id: 5042, year: 1291, title: "La caída de Acre", detail: "El último bastión cruzado en Tierra Santa se rinde y acaban dos siglos de cruzadas." },
  { id: 5043, year: 1337, title: "Empieza la guerra de los Cien Años", detail: "Inglaterra y Francia se disputan la corona francesa durante ciento dieciséis años." },
  { id: 5044, year: 1347, title: "La peste negra llega a Europa", detail: "En cinco años muere entre un tercio y la mitad de la población del continente." },
  { id: 5045, year: 1431, title: "La hoguera de Juana de Arco", detail: "Quemada en Ruan a los diecinueve años tras haber dado la vuelta a la guerra." },
  { id: 5046, year: 1453, title: "La caída de Constantinopla", detail: "Mehmed II toma la ciudad y el Imperio bizantino desaparece tras once siglos." },
  { id: 5047, year: 1492, title: "Colón llega a América", detail: "Tres naves —las carabelas Pinta y Niña y la nao Santa María— llegan al Caribe buscando una ruta occidental hacia Asia." },
  { id: 5048, year: 1517, title: "Lutero y sus noventa y cinco tesis", detail: "La protesta contra las indulgencias rompe la unidad religiosa de Europa." },
  { id: 5049, year: 1521, title: "La caída de Tenochtitlan", detail: "Tras un asedio de tres meses cae la capital mexica y con ella el imperio azteca." },
  { id: 5050, year: 1522, title: "La primera vuelta al mundo", detail: "De las cinco naves de Magallanes vuelve una, con Elcano y dieciocho hombres." },
  { id: 5051, year: 1532, title: "Pizarro captura a Atahualpa", detail: "En Cajamarca, un puñado de hombres apresa al inca y el imperio se derrumba." },
  { id: 5052, year: 1555, title: "La paz de Augsburgo", detail: "Cada príncipe alemán decide la religión de su territorio: «de quien es la tierra, la religión»." },
  { id: 5053, year: 1618, title: "Empieza la guerra de los Treinta Años", detail: "Una defenestración en Praga prende el conflicto que arrasará Centroeuropa." },
  { id: 5054, year: 1648, title: "La paz de Westfalia", detail: "Nace el sistema de Estados soberanos que sigue ordenando el mapa." },
  { id: 5055, year: 1689, title: "La Declaración de Derechos inglesa", detail: "El Parlamento impone condiciones a la corona y nace la monarquía parlamentaria." },
  { id: 5056, year: 1707, title: "El Acta de Unión", detail: "Inglaterra y Escocia se funden en un solo reino, Gran Bretaña." },
  { id: 5057, year: 1721, title: "Pedro el Grande, emperador de Rusia", detail: "Tras vencer a Suecia, convierte el zarato en un imperio con capital nueva en el Báltico." },
  { id: 5058, year: 1756, title: "Empieza la guerra de los Siete Años", detail: "El primer conflicto que se pelea a la vez en Europa, América y la India." },
  { id: 5059, year: 1776, title: "La Declaración de Independencia de Estados Unidos", detail: "Trece colonias se declaran libres el 4 de julio en Filadelfia." },
  { id: 5060, year: 1789, title: "La toma de la Bastilla", detail: "El asalto a la prisión el 14 de julio abre la Revolución francesa." },
  { id: 5061, year: 1793, title: "La ejecución de Luis XVI", detail: "El rey muere en la guillotina y empieza el Terror." },
  { id: 5062, year: 1804, title: "La independencia de Haití", detail: "La única revuelta de esclavos que acaba fundando un Estado." },
  { id: 5063, year: 1805, title: "La batalla de Austerlitz", detail: "Napoleón derrota a Austria y Rusia en su victoria más celebrada." },
  { id: 5064, year: 1810, title: "Empiezan las independencias hispanoamericanas", detail: "Las juntas de Caracas, Buenos Aires y México abren quince años de guerra." },
  { id: 5065, year: 1815, title: "La batalla de Waterloo", detail: "La derrota definitiva de Napoleón y el fin de veinte años de guerras en Europa." },
  { id: 5066, year: 1821, title: "La independencia de México", detail: "Tras once años de guerra, el virreinato de Nueva España deja de existir." },
  { id: 5067, year: 1830, title: "La Revolución de Julio en Francia", detail: "Tres jornadas de barricadas en París derriban a Carlos X." },
  { id: 5068, year: 1833, title: "El Parlamento británico aprueba la abolición de la esclavitud", detail: "La ley se aprueba en 1833 y entra en vigor en 1834 en gran parte de las colonias británicas, con excepciones y un régimen transitorio de aprendizaje forzoso." },
  { id: 5069, year: 1839, title: "La primera guerra del Opio", detail: "China intenta cortar el tráfico de opio y acaba cediendo Hong Kong." },
  { id: 5070, year: 1848, title: "La primavera de los pueblos", detail: "Una oleada de revoluciones se extiende por numerosos Estados europeos, con reivindicaciones liberales, sociales y nacionales." },
  { id: 5071, year: 1853, title: "Perry llega a Japón con los barcos negros", detail: "La expedición estadounidense llega en 1853. La presión diplomática desemboca en el Tratado de Kanagawa, firmado en 1854." },
  { id: 5072, year: 1857, title: "La rebelión de los cipayos", detail: "El levantamiento en la India acaba con la Compañía y pone el país bajo la corona británica." },
  { id: 5073, year: 1861, title: "Empieza la guerra de Secesión", detail: "Once estados del sur se separan y Estados Unidos se parte en dos durante cuatro años." },
  { id: 5074, year: 1865, title: "El asesinato de Lincoln", detail: "Lincoln muere el 15 de abril, seis días después de la rendición del ejército de Lee. La abolición constitucional de la esclavitud se ratifica en diciembre de ese año." },
  { id: 5075, year: 1869, title: "Se abre el canal de Suez", detail: "El canal conecta el Mediterráneo con el mar Rojo y acorta la ruta marítima entre Europa y Asia al evitar rodear África." },
  { id: 5076, year: 1871, title: "La proclamación del Imperio alemán", detail: "Bismarck reúne los Estados alemanes y corona al káiser en Versalles." },
  { id: 5077, year: 1885, title: "Concluye la Conferencia de Berlín", detail: "Las potencias acuerdan reglas para la expansión colonial en África. Muchas fronteras se negociarán y modificarán durante las décadas posteriores." },
  { id: 5078, year: 1894, title: "El caso Dreyfus", detail: "La condena de un capitán judío por una traición que no cometió divide a Francia durante doce años." },
  { id: 5079, year: 1900, title: "La rebelión de los bóxers", detail: "Ocho potencias envían tropas a Pekín y China queda todavía más sometida." },
  { id: 5080, year: 1905, title: "El Domingo Sangriento en San Petersburgo", detail: "La guardia dispara contra una manifestación pacífica y estalla la primera revolución rusa." },
  { id: 5081, year: 1910, title: "Empieza la Revolución mexicana", detail: "Diez años de guerra civil contra treinta de dictadura de Porfirio Díaz." },
  { id: 5082, year: 1912, title: "El hundimiento del Titanic", detail: "El buque considerado insumergible choca con un iceberg en su viaje inaugural." },
  { id: 5083, year: 1914, title: "Empieza la Primera Guerra Mundial", detail: "El atentado de Sarajevo enciende un sistema de alianzas que arrastra a toda Europa." },
  { id: 5084, year: 1917, title: "La Revolución de Octubre", detail: "Los bolcheviques toman el poder en Rusia y fundan el primer Estado comunista." },
  { id: 5085, year: 1919, title: "El tratado de Versalles", detail: "La paz impuesta a Alemania siembra el rencor que veinte años después dará otra guerra." },
  { id: 5086, year: 1922, title: "La marcha sobre Roma", detail: "Mussolini llega al poder y estrena en Europa un régimen fascista." },
  { id: 5087, year: 1929, title: "El crac del 29", detail: "La bolsa de Nueva York se hunde en octubre y arrastra al mundo a la Gran Depresión." },
  { id: 5088, year: 1933, title: "Hitler, canciller de Alemania", detail: "Llega al poder por la vía legal y en meses desmonta la república." },
  { id: 5089, year: 1939, title: "Empieza la Segunda Guerra Mundial", detail: "Alemania invade Polonia y Francia y el Reino Unido declaran la guerra." },
  { id: 5090, year: 1941, title: "El ataque a Pearl Harbor", detail: "Japón bombardea la flota estadounidense y la guerra se vuelve verdaderamente mundial." },
  { id: 5091, year: 1944, title: "El desembarco de Normandía", detail: "La mayor operación anfibia de la historia abre el frente occidental." },
  { id: 5092, year: 1945, title: "Hiroshima y Nagasaki", detail: "Dos bombas atómicas acaban la guerra y estrenan una amenaza nueva." },
  { id: 5093, year: 1947, title: "La independencia y partición de la India", detail: "Nacen la India y Pakistán, y con ellos el mayor desplazamiento de población del siglo." },
  { id: 5094, year: 1948, title: "La fundación del Estado de Israel", detail: "La proclamación en Tel Aviv desata la primera guerra árabe-israelí." },
  { id: 5095, year: 1949, title: "Mao proclama la República Popular China", detail: "Tras veintidós años de guerra civil, los comunistas ganan y el rival se refugia en Taiwán." },
  { id: 5096, year: 1953, title: "El armisticio de Corea", detail: "El armisticio suspende los combates sin un tratado de paz. La línea de demarcación militar queda cerca del paralelo 38, pero no coincide exactamente con él." },
  { id: 5097, year: 1955, title: "Rosa Parks no cede el asiento", detail: "Su detención impulsa el boicot a los autobuses de Montgomery, uno de los grandes hitos del movimiento por los derechos civiles." },
  { id: 5098, year: 1956, title: "La crisis de Suez", detail: "Egipto nacionaliza el canal y la respuesta militar franco-británica fracasa: Europa deja de mandar sola." },
  { id: 5099, year: 1959, title: "La Revolución cubana", detail: "Castro entra en La Habana y Batista huye en Nochevieja." },
  { id: 5100, year: 1960, title: "El año de África", detail: "Diecisiete colonias africanas se independizan en un solo año." },
  { id: 5101, year: 1962, title: "La crisis de los misiles", detail: "Trece días de octubre en que el mundo estuvo más cerca de una guerra nuclear." },
  { id: 5102, year: 1963, title: "El asesinato de Kennedy", detail: "Un magnicidio en Dallas retransmitido y discutido durante décadas." },
  { id: 5103, year: 1968, title: "La Primavera de Praga", detail: "Checoslovaquia ensaya un socialismo con rostro humano y los tanques del Pacto lo aplastan." },
  { id: 5104, year: 1973, title: "El golpe de Estado en Chile", detail: "Pinochet bombardea La Moneda y empieza una dictadura de diecisiete años." },
  { id: 5105, year: 1975, title: "El fin de la guerra de Vietnam", detail: "La caída de Saigón cierra veinte años de guerra y la primera derrota estadounidense." },
  { id: 5106, year: 1979, title: "La Revolución iraní", detail: "El sah huye, Jomeini vuelve del exilio y nace la República Islámica." },
  { id: 5107, year: 1985, title: "Gorbachov y la perestroika", detail: "El nuevo secretario general abre la URSS y, sin quererlo, la desmonta." },
  { id: 5108, year: 1989, title: "La caída del muro de Berlín", detail: "Una rueda de prensa confusa abre las fronteras y esa noche la gente derriba el muro." },
  { id: 5109, year: 1994, title: "Mandela, presidente de Sudáfrica", detail: "Las primeras elecciones nacionales con sufragio universal sin exclusión racial llevan a Mandela a la presidencia." },
  { id: 5110, year: 1997, title: "La devolución de Hong Kong", detail: "El Reino Unido entrega la colonia a China y se cierra el ciclo imperial europeo." },
  { id: 5111, year: 2001, title: "Los atentados del 11 de septiembre", detail: "Dos aviones derriban las Torres Gemelas y cambian dos décadas de política mundial." },
  { id: 5112, year: 2003, title: "La invasión de Irak", detail: "Una coalición derriba a Sadam Huseín sobre la base de unas armas que no aparecieron." },
  { id: 5113, year: 2008, title: "La quiebra de Lehman Brothers", detail: "El banco cae en septiembre y arrastra al mundo a la mayor crisis desde el 29." },
  { id: 5114, year: 2011, title: "La Primavera Árabe se extiende por la región", detail: "Las protestas iniciadas en Túnez en diciembre de 2010 se extienden en 2011 por países del norte de África y Oriente Próximo." },
  { id: 5115, year: 2016, title: "El referéndum del Brexit", detail: "La salida de la Unión Europea gana con el 51,9 % frente al 48,1 %: una diferencia de 3,8 puntos porcentuales." },
  { id: 5116, year: 2020, title: "La OMS declara pandemia", detail: "En marzo se confina medio mundo a la vez, algo que no había pasado nunca." },
  { id: 5117, year: 2022, title: "La invasión rusa de Ucrania", detail: "La mayor guerra en suelo europeo desde 1945." }
];
