// Hitos de la música. El año corresponde a un estreno, publicación, lanzamiento o
// cambio de formato concreto. El recorrido mezcla música clásica, popular y tecnología
// musical: la pregunta es cuándo ocurrió el hito, no qué género es "más importante".
window.MUSIC_CARDS = [
  { id: 6001, year: 1607, title: "Estreno de L'Orfeo", detail: "La ópera de Claudio Monteverdi se estrena en Mantua y se convierte en una de las primeras obras maestras del género." },
  { id: 6002, year: 1721, title: "Conciertos de Brandeburgo", detail: "Johann Sebastian Bach dedica a Christian Ludwig de Brandeburgo los seis conciertos que resumen el esplendor instrumental barroco." },
  { id: 6003, year: 1741, title: "Publicación de las Variaciones Goldberg", detail: "Bach publica un aria con treinta variaciones que se convertirá en una cima de la música para teclado." },
  { id: 6004, year: 1787, title: "Estreno de Don Giovanni", detail: "Mozart estrena en Praga su ópera sobre el mito de don Juan, a medio camino entre la comedia y el drama." },
  { id: 6005, year: 1805, title: "Estreno público de la Heroica", detail: "La Tercera sinfonía de Beethoven se presenta en Viena y ensancha la escala y la ambición de la sinfonía." },
  { id: 6006, year: 1824, title: "Estreno de la Novena de Beethoven", detail: "La Novena se estrena en Viena con Beethoven presente en el escenario y Michael Umlauf al frente de la ejecución. La obra incorpora voces en la Oda a la alegría." },
  { id: 6007, year: 1830, title: "Estreno de la Sinfonía fantástica", detail: "Hector Berlioz convierte una obsesión amorosa en un relato sinfónico de cinco movimientos." },
  { id: 6008, year: 1865, title: "Estreno de Tristán e Isolda", detail: "La ópera de Wagner se estrena en Múnich y lleva la tensión armónica del romanticismo hasta un nuevo límite." },
  { id: 6009, year: 1877, title: "Edison presenta el fonógrafo", detail: "La reproducción del sonido deja de ser una idea: una grabación puede conservarse y volver a escucharse." },
  { id: 6010, year: 1888, title: "Se graba «Israel en Egipto» en el Crystal Palace", detail: "Un cilindro conserva un fragmento del oratorio de Händel interpretado en Londres. Es una grabación histórica temprana, pero existen registros musicales anteriores." },
  { id: 6011, year: 1893, title: "Estreno de la Sinfonía del Nuevo Mundo", detail: "Antonín Dvořák estrena en Nueva York su Novena sinfonía, inspirada por su estancia en Estados Unidos." },
  { id: 6012, year: 1902, title: "Caruso graba en Milán", detail: "Diez arias registradas por Enrico Caruso ayudan a demostrar que el disco puede llevar una gran voz a un público masivo." },
  { id: 6013, year: 1913, title: "El escándalo de La consagración de la primavera", detail: "El ballet de Stravinski se estrena en París entre protestas y cambia para siempre el ritmo orquestal del siglo XX." },
  { id: 6014, year: 1920, title: "Comienza la radio comercial", detail: "La emisora KDKA inicia emisiones regulares en Pittsburgh; la música puede entrar en millones de hogares sin soporte físico." },
  { id: 6015, year: 1925, title: "Llega la grabación eléctrica", detail: "Micrófonos y amplificación sustituyen al gran embudo acústico y permiten registrar más matices y frecuencias." },
  { id: 6016, year: 1932, title: "La primera guitarra eléctrica comercial", detail: "La Rickenbacker Frying Pan demuestra que una pastilla electromagnética puede convertir la guitarra en protagonista." },
  { id: 6017, year: 1935, title: "Presentación del Magnetophon", detail: "AEG muestra en Berlín una grabadora de cinta magnética que hará posible editar y copiar sonido con mucha más facilidad." },
  { id: 6018, year: 1948, title: "Nace el disco de larga duración", detail: "Columbia presenta el LP de 33⅓ rpm, capaz de guardar una obra extensa o un álbum completo por disco." },
  { id: 6019, year: 1954, title: "Rock Around the Clock", detail: "Bill Haley and His Comets graban el tema que, impulsado después por el cine, lleva el rock and roll al gran público." },
  { id: 6020, year: 1956, title: "Primer álbum de Elvis Presley", detail: "El debut de Elvis llega al número uno y su portada se convierte en una de las imágenes fundacionales del rock." },
  { id: 6021, year: 1959, title: "Kind of Blue", detail: "Miles Davis publica el álbum de jazz modal más célebre y uno de los discos más vendidos de la historia del género." },
  { id: 6022, year: 1962, title: "Love Me Do", detail: "The Beatles lanzan su primer sencillo y comienza una carrera que transformará la cultura popular mundial." },
  { id: 6023, year: 1965, title: "Like a Rolling Stone", detail: "Bob Dylan rompe la duración habitual del sencillo y lleva una escritura más literaria al centro del pop." },
  { id: 6024, year: 1967, title: "Sgt. Pepper's Lonely Hearts Club Band", detail: "The Beatles convierten el estudio de grabación en instrumento y el álbum en una obra pensada como conjunto." },
  { id: 6025, year: 1969, title: "Festival de Woodstock", detail: "Más de treinta actuaciones y una multitud gigantesca fijan el gran símbolo musical de la contracultura." },
  { id: 6026, year: 1971, title: "What's Going On", detail: "Marvin Gaye publica un álbum conceptual que une soul, conciencia social y una producción de enorme influencia." },
  { id: 6027, year: 1973, title: "The Dark Side of the Moon", detail: "Pink Floyd combina rock, síntesis electrónica y sonido de estudio en uno de los álbumes más duraderos de las listas." },
  { id: 6028, year: 1975, title: "Bohemian Rhapsody", detail: "Queen publica un sencillo de seis minutos, sin estribillo convencional y con una sección operística grabada por capas." },
  { id: 6029, year: 1977, title: "Rumours", detail: "Fleetwood Mac transforma las tensiones internas del grupo en uno de los discos más vendidos de todos los tiempos." },
  { id: 6030, year: 1979, title: "Rapper's Delight", detail: "The Sugarhill Gang lleva el hip-hop a las listas internacionales con uno de los primeros grandes éxitos comerciales del rap." },
  { id: 6031, year: 1981, title: "MTV empieza a emitir", detail: "El canal inaugura una era en la que el videoclip y la imagen del artista pasan a ser inseparables de la canción." },
  { id: 6032, year: 1982, title: "Thriller", detail: "Michael Jackson publica el álbum más vendido de la historia y convierte sus videoclips en acontecimientos globales." },
  { id: 6033, year: 1984, title: "Purple Rain", detail: "Prince une álbum, película y gira en una obra que mezcla rock, pop, funk y una puesta en escena inolvidable." },
  { id: 6034, year: 1986, title: "Graceland", detail: "Paul Simon graba con músicos sudafricanos un álbum popular y polémico que amplía el mercado internacional de la llamada world music." },
  { id: 6035, year: 1987, title: "The Joshua Tree", detail: "U2 alcanza dimensión mundial con un disco inspirado por los paisajes, la música y las contradicciones de Estados Unidos." },
  { id: 6036, year: 1989, title: "Like a Prayer", detail: "Madonna publica un álbum más personal y provoca un debate mundial al mezclar imaginería religiosa y cultura pop." },
  { id: 6037, year: 1991, title: "Nevermind", detail: "Nirvana lleva el grunge de Seattle al número uno y altera el sonido dominante del rock de los noventa." },
  { id: 6038, year: 1992, title: "Automatic for the People", detail: "R.E.M. publica su disco más contemplativo y confirma que el rock alternativo puede ocupar el centro del mercado." },
  { id: 6039, year: 1994, title: "Definitely Maybe", detail: "El debut de Oasis se convierte en emblema del britpop y en el álbum de debut más rápidamente vendido del Reino Unido hasta entonces." },
  { id: 6040, year: 1997, title: "OK Computer", detail: "Radiohead combina guitarras y experimentación electrónica en un retrato inquietante de la vida tecnológica moderna." },
  { id: 6041, year: 1999, title: "Napster abre el intercambio musical", detail: "El servicio entre usuarios populariza el MP3 y desata una crisis sobre cómo distribuir y pagar la música en internet." },
  { id: 6042, year: 2001, title: "Apple presenta el iPod", detail: "Un reproductor de bolsillo y su biblioteca digital hacen cotidiana la idea de llevar miles de canciones encima." },
  { id: 6043, year: 2003, title: "Abre iTunes Store", detail: "La venta legal de canciones sueltas por internet ofrece una alternativa masiva a la descarga no autorizada." },
  { id: 6044, year: 2005, title: "YouTube lleva el videoclip a la red", detail: "La nueva plataforma permite compartir vídeos musicales sin depender de la programación de un canal de televisión." },
  { id: 6045, year: 2007, title: "In Rainbows y el precio elegido", detail: "Radiohead distribuye el álbum desde su web dejando que cada comprador decida cuánto pagar por la descarga." },
  { id: 6046, year: 2008, title: "Spotify inicia su servicio", detail: "La plataforma se lanza en varios países europeos y acelera el paso de poseer discos a escuchar un catálogo bajo demanda." },
  { id: 6047, year: 2011, title: "21 de Adele", detail: "El segundo álbum de Adele domina ventas y premios en plena transición de la industria hacia el streaming." },
  { id: 6048, year: 2012, title: "Gangnam Style supera mil millones", detail: "El vídeo de PSY se convierte en el primero de YouTube en alcanzar mil millones de reproducciones." },
  { id: 6049, year: 2017, title: "Despacito se convierte en fenómeno mundial", detail: "Luis Fonsi y Daddy Yankee llevan una canción en español al número uno de decenas de países y a cifras récord en internet." },
  { id: 6050, year: 2020, title: "Un álbum íntegramente en español lidera Billboard", detail: "El último tour del mundo de Bad Bunny es el primer álbum completamente en español que alcanza el número uno del Billboard 200." },
  { id: 6051, year: 2023, title: "The Eras Tour", detail: "Taylor Swift inicia una gira que recorre todas sus etapas discográficas y se convierte en un fenómeno cultural y económico global." }
];
