// El valor es la población a 1 de enero de 2026, según la revisión de 2024 de las
// Perspectivas de la Población Mundial de la ONU (tabla de Worldometer). Ninguna carta está
// a menos de un 8% de otra: si no, colocarla bien sería cuestión de suerte. Los países que
// faltan suelen faltar por eso — China queda a un 4% de la India, y Argentina a un 4% de España.
window.POPULATION_CARDS = [
  { id: 3001, value: 1476625576, title: "India", detail: "El país más poblado del mundo: adelantó a China en 2023." },
  { id: 3002, value: 349035494, title: "Estados Unidos", detail: "El tercero, pero a menos de la cuarta parte del primero." },
  { id: 3003, value: 287886782, title: "Indonesia", detail: "Diecisiete mil islas y más gente que toda Sudamérica junta." },
  { id: 3004, value: 242431832, title: "Nigeria", detail: "El país más poblado de África, y con la población más joven del continente." },
  { id: 3005, value: 213562666, title: "Brasil", detail: "Casi la mitad de la población de Sudamérica." },
  { id: 3006, value: 177818044, title: "Bangladesh", detail: "En un territorio del tamaño de Grecia y Bulgaria juntas." },
  { id: 3007, value: 132997658, title: "México", detail: "El país hispanohablante más poblado del mundo, con diferencia." },
  { id: 3008, value: 122427731, title: "Japón", detail: "Pierde medio millón de habitantes al año desde 2010." },
  { id: 3009, value: 102177431, title: "Vietnam", detail: "Superó los cien millones en 2023." },
  { id: 3010, value: 93168497, title: "Irán", detail: "Ha triplicado su población desde 1970." },
  { id: 3011, value: 83644258, title: "Alemania", detail: "El país más poblado de la Unión Europea." },
  { id: 3012, value: 72563780, title: "Tanzania", detail: "Ha multiplicado por siete su población desde la independencia, en 1961." },
  { id: 3013, value: 66746401, title: "Francia", detail: "La cifra incluye los territorios de ultramar." },
  { id: 3014, value: 58926166, title: "Italia", detail: "Una de las natalidades más bajas del mundo: lleva quince años perdiendo gente." },
  { id: 3015, value: 53936226, title: "Colombia", detail: "El segundo país hispanohablante más poblado." },
  { id: 3016, value: 47850793, title: "España", detail: "Ha crecido en más de seis millones desde el año 2000, casi todo por migración." },
  { id: 3017, value: 42961653, title: "Yemen", detail: "Ha doblado su población desde 1995 pese a la guerra." },
  { id: 3018, value: 38762441, title: "Marruecos", detail: "Casi tanta gente como España en una superficie parecida." },
  { id: 3019, value: 34922148, title: "Perú", detail: "Un tercio vive en Lima y su área metropolitana." },
  { id: 3020, value: 28633711, title: "Venezuela", detail: "Ha perdido millones de habitantes desde 2015 por la emigración." },
  { id: 3021, value: 26472497, title: "Siria", detail: "La guerra desplazó a más de la mitad de su población." },
  { id: 3022, value: 23348315, title: "Sri Lanka", detail: "Una isla con más habitantes que Australia." },
  { id: 3023, value: 19945850, title: "Chile", detail: "Más de un tercio vive en el Gran Santiago." },
  { id: 3024, value: 18444506, title: "Ecuador", detail: "Prácticamente la misma población que los Países Bajos, en cinco veces más territorio." },
  { id: 3025, value: 14889693, title: "Ruanda", detail: "El país más densamente poblado de África continental." },
  { id: 3026, value: 12749291, title: "Bolivia", detail: "Dos capitales: La Paz es la sede del gobierno; Sucre, la constitucional." },
  { id: 3027, value: 11609500, title: "República Dominicana", detail: "Comparte isla con Haití, que tiene una población parecida." },
  { id: 3028, value: 10395362, title: "Portugal", detail: "Lleva una década estancado: pierde nacimientos y gana residentes extranjeros." },
  { id: 3029, value: 9007798, title: "Suiza", detail: "Una cuarta parte de sus residentes no tiene pasaporte suizo." },
  { id: 3030, value: 7095279, title: "Paraguay", detail: "Uno de los países más jóvenes de América: la edad media no llega a los 27 años." },
  { id: 3031, value: 6391253, title: "El Salvador", detail: "El país más pequeño y más densamente poblado de América continental." },
  { id: 3032, value: 5652989, title: "Noruega", detail: "Más gente que Irlanda, en cinco veces más superficie." },
  { id: 3033, value: 5174789, title: "Costa Rica", detail: "Sin ejército desde 1948." },
  { id: 3034, value: 4625718, title: "Panamá", detail: "La mitad vive en la capital y su entorno." },
  { id: 3035, value: 3822345, title: "Croacia", detail: "Ha perdido medio millón de habitantes desde que entró en la Unión Europea." },
  { id: 3036, value: 3382537, title: "Uruguay", detail: "Casi la mitad vive en Montevideo." },
  { id: 3037, value: 3114242, title: "Bosnia y Herzegovina", detail: "Un millón menos que antes de la guerra de los noventa." },
  { id: 3038, value: 2797338, title: "Lituania", detail: "La mayor de las tres repúblicas bálticas." },
  { id: 3039, value: 2114573, title: "Eslovenia", detail: "Cabe cuatro veces en Castilla y León y tiene casi la misma gente." },
  { id: 3040, value: 1835935, title: "Letonia", detail: "Ha perdido una cuarta parte de su población desde 1991." },
  { id: 3041, value: 1331062, title: "Estonia", detail: "La menos poblada de las bálticas, y la más digitalizada de Europa." },
  { id: 3042, value: 687448, title: "Luxemburgo", detail: "Casi la mitad de sus residentes son extranjeros." },
  { id: 3043, value: 626233, title: "Montenegro", detail: "Menos gente que la ciudad de Valencia." },
  { id: 3044, value: 549011, title: "Malta", detail: "El país más densamente poblado de la Unión Europea." },
  { id: 3045, value: 402329, title: "Islandia", detail: "Dos de cada tres islandeses viven en Reikiavik y alrededores." },
  { id: 3046, value: 83753, title: "Andorra", detail: "Menos habitantes que Cuenca capital." },
  { id: 3047, value: 38087, title: "Mónaco", detail: "El país más densamente poblado del mundo: 38.000 personas en dos km²." },
  { id: 3048, value: 33605, title: "San Marino", detail: "La república más antigua del mundo que sigue en pie." },
  { id: 3049, value: 506, title: "Ciudad del Vaticano", detail: "El país menos poblado del mundo: cabría entero en un instituto grande." }
];
