// Velocidades de referencia en km/h, no un ranking homogéneo de récords absolutos.
// El título identifica el movimiento y si se trata de crucero, carrera o muestra medida.
// Las cartas pendientes se señalan antes de jugar; no se consideran verificadas.
// Véase VERIFICACION_CORRECCIONES.md para fuentes y limitaciones.
window.ANIMAL_SPEED_CARDS = [
  { id: 13001, value: 0.03, title: "Caracol de jardín", detail: "Se desplaza con su pie musculoso a una velocidad punta cercana a 0,03 km/h." },
  { id: 13002, value: 0.05, title: "Babosa · en revisión", detail: "Dato pendiente de verificación. Falta identificar la especie y documentar la cifra.", reviewStatus: "pending" },
  { id: 13003, value: 0.08, title: "Estrella de mar · en revisión", detail: "Dato pendiente de verificación. Falta identificar la especie y documentar la cifra.", reviewStatus: "pending" },
  { id: 13004, value: 0.13, title: "Tortuga gigante", detail: "En tierra, una tortuga gigante camina con calma a unas décimas de km/h." },
  { id: 13005, value: 0.22, title: "Perezoso de tres dedos", detail: "Entre las ramas se mueve con enorme cautela: su velocidad punta es muy baja." },
  { id: 13006, value: 0.36, title: "Caballito de mar · en revisión", detail: "Dato pendiente de verificación. Falta identificar la especie y documentar la cifra.", reviewStatus: "pending" },
  { id: 13007, value: 10, title: "Koala (máximo observado en un estudio)", detail: "Un estudio de locomoción registró 2,78 m/s en tierra, aproximadamente 10 km/h. Es el máximo de esa muestra, no un récord absoluto de la especie.", source: "https://journals.biologists.com/jeb/article/222/24/jeb207506/223548/Quantifying-koala-locomotion-strategies" },
  { id: 13008, value: 1, title: "Panda gigante (marcha habitual) · en revisión", detail: "Dato pendiente de verificación. El texto describe una marcha habitual; falta una fuente para su valor numérico.", reviewStatus: "pending" },
  { id: 13009, value: 1.7, title: "Pingüino emperador (en tierra) · en revisión", detail: "Dato pendiente de verificación. El modo terrestre está especificado, pero falta una fuente para la cifra.", reviewStatus: "pending" },
  { id: 13010, value: 24.1, title: "Manatí de Florida (aceleración nadando)", detail: "La FWC indica aceleraciones cortas de hasta 15 millas por hora, aproximadamente 24,1 km/h. Su velocidad habitual de nado es menor.", source: "https://myfwc.com/education/wildlife/manatee/facts-and-information/" },
  { id: 13011, value: 4.6, title: "Cangrejo ermitaño", detail: "Su concha le protege, pero también limita notablemente la velocidad con la que puede desplazarse." },
  { id: 13012, value: 7.5, title: "Gallina doméstica", detail: "Puede correr en un sprint corto, aunque sus patas están hechas para buscar alimento y rascar el suelo." },
  { id: 13013, value: 12, title: "Erizo europeo", detail: "Puede moverse con sorprendente agilidad antes de hacerse una bola defensiva." },
  { id: 13014, value: 10, title: "Oso polar (nadando)", detail: "SeaWorld recoge una velocidad de nado de hasta unos 10 km/h. No debe confundirse con la velocidad de carrera en tierra.", source: "https://seaworld.org/animals/all-about/polar-bears/adaptations/" },
  { id: 13015, value: 30, title: "Hipopótamo común (en tierra)", detail: "En tierra puede correr rápido pese a su masa; en el agua no nada, se impulsa desde el fondo." },
  { id: 13016, value: 45, title: "Elefante africano · en revisión", detail: "Dato pendiente de verificación. Falta una fuente para elefantes africanos; una medición en elefantes asiáticos no resuelve esta carta.", reviewStatus: "pending" },
  { id: 13017, value: 55, title: "Jirafa (galopando)", detail: "Sus larguísimas patas le permiten un galope de unos 55 km/h." },
  { id: 13018, value: 48, title: "Emú (corriendo)", detail: "San Diego Zoo sitúa su velocidad de carrera en hasta 30 millas por hora, aproximadamente 48 km/h. Se elimina la referencia de 65 km/h que no concordaba con la explicación.", source: "https://animals.sandiegozoo.org/animals/emu" },
  { id: 13019, value: 78, title: "León africano (esprint)", detail: "Puede superar los 70 km/h en un sprint, pero solo durante una distancia corta." },
  { id: 13020, value: 70, title: "Avestruz (esprint)", detail: "San Diego Zoo indica ráfagas de hasta 70 km/h; la velocidad sostenida es menor. No se usan 90 km/h como si fueran un máximo documentado.", source: "https://animals.sandiegozoo.org/animals/ostrich" },
  { id: 13021, value: 70.35, title: "Caballo Winning Brew (media de carrera)", detail: "Guinness registra 70,35 km/h de velocidad media sobre 402 metros en 2008. Es una media de carrera de ese ejemplar, no la velocidad punta instantánea de todos los caballos.", source: "https://www.guinnessworldrecords.com/world-records/fastest-speed-for-a-race-horse" },
  { id: 13022, value: 120, title: "Ñu azul · en revisión", detail: "Dato pendiente de verificación. Los 120 km/h no tienen respaldo suficiente; falta cerrar la sustitución con una fuente adecuada.", reviewStatus: "pending" },
  { id: 13023, value: 97, title: "Berrendo americano (carrera, referencia NPS)", detail: "El National Park Service cita hasta 60 millas por hora, unos 97 km/h. Se usa esa referencia redondeada, no un récord universal ni los 138 km/h anteriores.", source: "https://www.nps.gov/wica/learn/nature/pronghorn.htm" },
  { id: 13024, value: 112, title: "Guepardo (límite del rango de esprint)", detail: "Smithsonian da un rango de velocidad de esprint de aproximadamente 96 a 112 km/h. La carta usa el extremo superior publicado, no 158 km/h.", source: "https://nationalzoo.si.edu/animals/cheetah" },
  { id: 13025, value: 182, title: "Vencejo de garganta blanca · en revisión", detail: "Dato pendiente de verificación. Falta verificar la medición y la discrepancia entre 182 y 170 km/h.", reviewStatus: "pending" },
  { id: 13026, value: 210, title: "Águila real · en revisión", detail: "Dato pendiente de verificación. Falta documentar la cifra y distinguirla del otro descenso de águila real.", reviewStatus: "pending" },
  { id: 13027, value: 240, title: "Águila real en picado · en revisión", detail: "Dato pendiente de verificación. Falta documentar la cifra y distinguirla del otro descenso de águila real.", reviewStatus: "pending" },
  { id: 13028, value: 275, title: "Halcón gerifalte · en revisión", detail: "Dato pendiente de verificación. No se ha encontrado respaldo suficiente para los 275 km/h.", reviewStatus: "pending" },
  { id: 13029, value: 315, title: "Halcón sacre · en revisión", detail: "Dato pendiente de verificación. No se ha encontrado respaldo suficiente para los 315 km/h.", reviewStatus: "pending" },
  { id: 13030, value: 360, title: "Halcón peregrino (en picado)", detail: "Las mejores mediciones de picado del peregrino se acercan a 360 km/h." },
  { id: 13031, value: 0.104, title: "Hormiga roja", detail: "Pese a su diminuto tamaño, puede recorrer unas décimas de km/h al buscar alimento." },
  { id: 13032, value: 0.17, title: "Lapa", detail: "Este molusco se aferra a las rocas y avanza lentamente con su musculoso pie." },
  { id: 13033, value: 0.46, title: "Caracol marino · en revisión", detail: "Dato pendiente de verificación. Falta identificar la especie y documentar la cifra.", reviewStatus: "pending" },
  { id: 13034, value: 0.75, title: "Cangrejo de río (caminando por el fondo) · en revisión", detail: "Dato pendiente de verificación. Se compara la marcha por el fondo, pero falta documentar su cifra.", reviewStatus: "pending" },
  { id: 13035, value: 1.3, title: "Cangrejo araña", detail: "Sus patas largas le permiten una marcha lenta pero constante por el fondo marino." },
  { id: 13036, value: 3.5, title: "Topo europeo", detail: "Bajo tierra excava con potencia, pero sobre la superficie se desplaza a poca velocidad." },
  { id: 13037, value: 5.8, title: "Cucaracha americana", detail: "Puede correr varias decenas de longitudes de cuerpo por segundo para escapar." },
  { id: 13038, value: 27, title: "Abeja melífera (vuelo de crucero sin carga)", detail: "La literatura experimental cita alrededor de 7,5 m/s en vuelo sin carga, equivalentes a 27 km/h. Es una referencia de crucero; el viento, la carga y el método de medición importan.", source: "https://journals.biologists.com/jeb/article/209/5/978/16690/Visual-regulation-of-ground-speed-and-headwind" }
];
