// Velocidades punta de referencia. Se indica el modo de movimiento porque correr,
// nadar y picar no son pruebas equivalentes, aunque todos se expresen en km/h.
window.ANIMAL_SPEED_CARDS = [
  { id: 13001, value: 0.03, title: "Caracol de jardín", detail: "Se desplaza con su pie musculoso a una velocidad punta cercana a 0,03 km/h." },
  { id: 13002, value: 0.05, title: "Babosa", detail: "Su avance sobre el moco que produce es lentísimo, de apenas unas centésimas de km/h." },
  { id: 13003, value: 0.08, title: "Estrella de mar", detail: "Sus pequeños pies ambulacrales le permiten moverse, pero a un ritmo casi imperceptible." },
  { id: 13004, value: 0.13, title: "Tortuga gigante", detail: "En tierra, una tortuga gigante camina con calma a unas décimas de km/h." },
  { id: 13005, value: 0.22, title: "Perezoso de tres dedos", detail: "Entre las ramas se mueve con enorme cautela: su velocidad punta es muy baja." },
  { id: 13006, value: 0.36, title: "Caballito de mar", detail: "Es uno de los peces más lentos; nada con una pequeña aleta dorsal que vibra muy deprisa." },
  { id: 13007, value: 0.6, title: "Koala", detail: "En el suelo puede acelerar brevemente, pero su vida está adaptada a trepar y ahorrar energía." },
  { id: 13008, value: 1, title: "Panda gigante", detail: "Su marcha habitual es tranquila; no está construido para carreras largas ni rápidas." },
  { id: 13009, value: 1.7, title: "Pingüino emperador", detail: "Sobre el hielo camina despacio y ahorra energía, aunque bajo el agua resulta mucho más ágil." },
  { id: 13010, value: 2.8, title: "Manatí", detail: "Nada normalmente a poca velocidad y reserva sus aceleraciones para huir de un peligro." },
  { id: 13011, value: 4.6, title: "Cangrejo ermitaño", detail: "Su concha le protege, pero también limita notablemente la velocidad con la que puede desplazarse." },
  { id: 13012, value: 7.5, title: "Gallina doméstica", detail: "Puede correr en un sprint corto, aunque sus patas están hechas para buscar alimento y rascar el suelo." },
  { id: 13013, value: 12, title: "Erizo europeo", detail: "Puede moverse con sorprendente agilidad antes de hacerse una bola defensiva." },
  { id: 13014, value: 19, title: "Oso polar", detail: "Nadando puede alcanzar alrededor de 19 km/h durante tramos cortos." },
  { id: 13015, value: 30, title: "Hipopótamo común", detail: "En tierra puede correr rápido pese a su masa; en el agua no nada, se impulsa desde el fondo." },
  { id: 13016, value: 45, title: "Elefante africano", detail: "Un elefante puede avanzar muy deprisa sin llegar a despegar las cuatro patas a la vez del suelo." },
  { id: 13017, value: 55, title: "Jirafa", detail: "Sus larguísimas patas le permiten un galope de unos 55 km/h." },
  { id: 13018, value: 65, title: "Emú", detail: "Este ave no voladora puede correr cerca de 50 km/h; se toma 65 km/h como referencia punta." },
  { id: 13019, value: 78, title: "León africano", detail: "Puede superar los 70 km/h en un sprint, pero solo durante una distancia corta." },
  { id: 13020, value: 90, title: "Avestruz", detail: "El ave más grande del mundo puede correr cerca de 90 km/h con zancadas enormes." },
  { id: 13021, value: 105, title: "Caballo doméstico", detail: "Un caballo de carreras puede alcanzar alrededor de 105 km/h en una distancia corta." },
  { id: 13022, value: 120, title: "Ñu azul", detail: "En una huida puede alcanzar velocidades superiores a los cien km/h." },
  { id: 13023, value: 138, title: "Berrendo americano", detail: "Este antílope americano es uno de los corredores terrestres más rápidos y resistentes." },
  { id: 13024, value: 158, title: "Guepardo", detail: "Es el mamífero terrestre más veloz; su gran aceleración solo puede sostenerse pocos segundos." },
  { id: 13025, value: 182, title: "Vencejo de garganta blanca", detail: "Es una de las aves más rápidas en vuelo horizontal, con registros cercanos a 170 km/h." },
  { id: 13026, value: 210, title: "Águila real", detail: "En un descenso de caza puede superar los 200 km/h al cerrar parcialmente las alas." },
  { id: 13027, value: 240, title: "Águila real en picado", detail: "En un picado pronunciado, esta gran rapaz puede acercarse a 240 km/h." },
  { id: 13028, value: 275, title: "Halcón gerifalte", detail: "El mayor de los halcones es un cazador aéreo muy rápido, especialmente al descender." },
  { id: 13029, value: 315, title: "Halcón sacre", detail: "Su vuelo de caza incluye picados de más de 300 km/h." },
  { id: 13030, value: 360, title: "Halcón peregrino", detail: "Las mejores mediciones de picado del peregrino se acercan a 360 km/h." },
  { id: 13031, value: 0.104, title: "Hormiga roja", detail: "Pese a su diminuto tamaño, puede recorrer unas décimas de km/h al buscar alimento." },
  { id: 13032, value: 0.17, title: "Lapa", detail: "Este molusco se aferra a las rocas y avanza lentamente con su musculoso pie." },
  { id: 13033, value: 0.46, title: "Caracol marino", detail: "Un gasterópodo marino se desplaza despacio sobre las rocas y el fondo." },
  { id: 13034, value: 0.75, title: "Cangrejo de río", detail: "Camina por el fondo a menos de un km/h salvo cuando escapa con un rápido coletazo." },
  { id: 13035, value: 1.3, title: "Cangrejo araña", detail: "Sus patas largas le permiten una marcha lenta pero constante por el fondo marino." },
  { id: 13036, value: 3.5, title: "Topo europeo", detail: "Bajo tierra excava con potencia, pero sobre la superficie se desplaza a poca velocidad." },
  { id: 13037, value: 5.8, title: "Cucaracha americana", detail: "Puede correr varias decenas de longitudes de cuerpo por segundo para escapar." },
  { id: 13038, value: 9.5, title: "Abeja melífera", detail: "En vuelo de transporte suele rondar esta velocidad; sin carga puede ser más rápida." }
];
