// Historia de los videojuegos. Se toma el primer lanzamiento relevante indicado en la
// carta (arcade, país de origen o acceso público), no la fecha posterior de otra región.
window.VIDEOGAME_CARDS = [
  { id: 7001, year: 1952, title: "OXO", detail: "Alexander S. Douglas programa un tres en raya con pantalla gráfica para el ordenador EDSAC." },
  { id: 7002, year: 1958, title: "Tennis for Two", detail: "Un osciloscopio del laboratorio de Brookhaven muestra un partido de tenis controlado por dos personas." },
  { id: 7003, year: 1962, title: "Spacewar!", detail: "Dos naves se enfrentan alrededor de una estrella en el PDP-1; el programa se comparte entre universidades." },
  { id: 7004, year: 1971, title: "Computer Space", detail: "La primera máquina recreativa comercial basada en un videojuego llega a bares y salones estadounidenses." },
  { id: 7005, year: 1972, title: "Pong", detail: "Atari convierte un sencillo tenis electrónico en el primer gran éxito de las máquinas recreativas." },
  { id: 7006, year: 1977, title: "Atari 2600", detail: "Los cartuchos intercambiables separan la consola del juego y llevan el salón recreativo al televisor doméstico." },
  { id: 7007, year: 1978, title: "Space Invaders", detail: "Taito llena los salones japoneses con filas de alienígenas y una dificultad que crece al desaparecer enemigos." },
  { id: 7008, year: 1980, title: "Pac-Man", detail: "Un laberinto, cuatro fantasmas y un personaje reconocible amplían el público más allá de las naves y los disparos." },
  { id: 7009, year: 1981, title: "Donkey Kong", detail: "Nintendo presenta a Jumpman, futuro Mario, en un juego de plataformas diseñado por Shigeru Miyamoto." },
  { id: 7010, year: 1982, title: "Commodore 64", detail: "El ordenador doméstico combina precio, sonido y gráficos para convertirse en una de las mayores plataformas de juego de los ochenta." },
  { id: 7011, year: 1983, title: "Famicom llega a Japón", detail: "Nintendo lanza la consola que fuera de Japón se conocerá como NES y ayudará a reconstruir el mercado doméstico." },
  { id: 7012, year: 1984, title: "Tetris", detail: "Alekséi Pázhitnov crea en Moscú el rompecabezas de piezas que encajan y que acabará en casi cualquier plataforma imaginable." },
  { id: 7013, year: 1985, title: "Super Mario Bros.", detail: "Mario cruza el Reino Champiñón y establece el lenguaje de los juegos de plataformas para consola." },
  { id: 7014, year: 1986, title: "The Legend of Zelda", detail: "Nintendo lanza la aventura en Japón para Famicom Disk System, que guarda la partida en disco. La versión occidental en cartucho llegará en 1987." },
  { id: 7015, year: 1987, title: "Final Fantasy", detail: "Square publica el juego de rol que dará origen a una de las sagas japonesas más longevas." },
  { id: 7016, year: 1988, title: "Mega Drive", detail: "Sega estrena en Japón una consola de 16 bits que competirá directamente con Nintendo durante la siguiente generación." },
  { id: 7017, year: 1989, title: "Game Boy", detail: "Nintendo combina pantalla monocroma, autonomía y Tetris para convertir el juego portátil en un mercado masivo." },
  { id: 7018, year: 1990, title: "The Secret of Monkey Island", detail: "Lucasfilm Games convierte el duelo de insultos, el humor y los puzles sin muerte en una aventura gráfica de referencia." },
  { id: 7019, year: 1991, title: "Sonic the Hedgehog", detail: "Sega presenta a su mascota azul y hace de la velocidad la seña de identidad de Mega Drive." },
  { id: 7020, year: 1992, title: "Mortal Kombat", detail: "Sus luchadores digitalizados y su violencia desatan el debate que desembocará en la clasificación por edades estadounidense." },
  { id: 7021, year: 1993, title: "Doom", detail: "id Software populariza la acción en primera persona, el juego en red local y la distribución por shareware." },
  { id: 7022, year: 1994, title: "PlayStation llega a Japón", detail: "Sony entra en las consolas con discos compactos y una estrategia que impulsa definitivamente los gráficos tridimensionales." },
  { id: 7023, year: 1995, title: "Chrono Trigger", detail: "Un equipo de estrellas del rol japonés publica una aventura de viajes temporales con múltiples finales." },
  { id: 7024, year: 1996, title: "Pokémon Rojo y Verde", detail: "La captura e intercambio de criaturas debuta en Game Boy en Japón y nace un fenómeno mundial." },
  { id: 7025, year: 1997, title: "Final Fantasy VII", detail: "Las escenas generadas por ordenador y la historia de Cloud llevan el rol japonés a una audiencia internacional masiva." },
  { id: 7026, year: 1998, title: "Half-Life", detail: "Valve narra la invasión de Black Mesa sin apartar la cámara del jugador y renueva el diseño de la acción en primera persona." },
  { id: 7027, year: 1999, title: "Dreamcast llega a Europa", detail: "La última consola de Sega incorpora módem y anticipa el juego en línea como función doméstica habitual." },
  { id: 7028, year: 2000, title: "Los Sims", detail: "Maxis convierte la vida cotidiana, las casas y las relaciones en un juguete abierto para todo tipo de público." },
  { id: 7029, year: 2001, title: "Halo acompaña a la primera Xbox", detail: "Microsoft entra en el mercado de consolas y Master Chief redefine el control del shooter con mando." },
  { id: 7030, year: 2002, title: "Grand Theft Auto: Vice City", detail: "Rockstar transforma una ciudad abierta inspirada en Miami y los años ochenta en un enorme fenómeno cultural." },
  { id: 7031, year: 2003, title: "Steam abre sus puertas", detail: "Valve lanza la plataforma que acabará convirtiendo la descarga digital en el principal escaparate del juego para PC." },
  { id: 7032, year: 2004, title: "World of Warcraft", detail: "Millones de personas comparten el mundo persistente de Azeroth y el juego en línea entra en la cultura popular." },
  { id: 7033, year: 2005, title: "Shadow of the Colossus", detail: "Una aventura minimalista enfrenta al jugador a dieciséis gigantes y plantea el coste moral de cada victoria." },
  { id: 7034, year: 2006, title: "Nintendo Wii", detail: "El mando sensible al movimiento hace que familias y jugadores ocasionales se levanten del sofá para jugar." },
  { id: 7035, year: 2007, title: "BioShock", detail: "La ciudad submarina de Rapture combina acción, filosofía política y una de las revelaciones narrativas más recordadas." },
  { id: 7036, year: 2008, title: "Grand Theft Auto IV", detail: "Liberty City ofrece una ciudad abierta más densa y realista alrededor de la historia del inmigrante Niko Bellic." },
  { id: 7037, year: 2009, title: "Minecraft abre su versión pública", detail: "Markus Persson publica una primera versión jugable del mundo de bloques que crecerá junto a su comunidad." },
  { id: 7038, year: 2010, title: "Red Dead Redemption", detail: "Rockstar lleva su diseño de mundo abierto al ocaso del Lejano Oeste y a la tragedia de John Marston." },
  { id: 7039, year: 2011, title: "The Elder Scrolls V: Skyrim", detail: "La libertad para recorrer una provincia nórdica convierte el juego de rol de Bethesda en un fenómeno duradero." },
  { id: 7040, year: 2012, title: "Candy Crush Saga", detail: "El puzle para Facebook y móviles lleva el modelo gratuito y las partidas breves a cientos de millones de personas." },
  { id: 7041, year: 2013, title: "Grand Theft Auto V", detail: "Tres protagonistas comparten Los Santos en uno de los lanzamientos de entretenimiento más exitosos de la historia." },
  { id: 7042, year: 2014, title: "Hearthstone", detail: "Blizzard simplifica el juego de cartas coleccionables para pantallas táctiles y consolida el modelo de servicio digital." },
  { id: 7043, year: 2015, title: "The Witcher 3: Wild Hunt", detail: "CD Projekt convierte las decisiones morales y las historias secundarias en el corazón de un enorme mundo abierto." },
  { id: 7044, year: 2016, title: "Pokémon GO", detail: "La realidad aumentada llena parques y plazas de personas que buscan criaturas con el móvil." },
  { id: 7045, year: 2017, title: "Nintendo Switch", detail: "Una consola que pasa del televisor a las manos difumina la frontera entre jugar en casa y fuera." },
  { id: 7046, year: 2018, title: "God of War", detail: "Kratos cambia la mitología griega por la nórdica y una relación entre padre e hijo rodada sin cortes visibles." },
  { id: 7047, year: 2019, title: "Disco Elysium", detail: "Un detective sin memoria protagoniza un juego de rol construido alrededor del diálogo, la política y las voces de su propia mente." },
  { id: 7048, year: 2020, title: "Animal Crossing: New Horizons", detail: "La vida tranquila en una isla se convierte en lugar de encuentro mundial durante los confinamientos." },
  { id: 7049, year: 2022, title: "Elden Ring", detail: "FromSoftware abre su combate exigente a un mundo explorable creado junto al novelista George R. R. Martin." },
  { id: 7050, year: 2023, title: "The Legend of Zelda: Tears of the Kingdom", detail: "La aventura amplía Hyrule hacia el cielo y permite construir máquinas combinando objetos físicos." },
  { id: 7051, year: 2024, title: "Balatro", detail: "Un pequeño juego independiente mezcla manos de póquer y construcción de mazos hasta convertirse en una sorpresa mundial." }
];
