import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const read = name => fs.readFileSync(new URL('../' + name, import.meta.url), 'utf8');
const dom = new JSDOM('<main id="app"><div class="shell"></div></main>', {runScripts: 'outside-only', pretendToBeVisual: true, url: 'https://continuum.test'});
const w = dom.window, app = w.document.getElementById('app');
let vibrations = 0;
let reduced = false, cancelled = 0, flights = [];
w.matchMedia = () => ({matches: reduced, addEventListener() {}});
w.HTMLElement.prototype.animate = (frames, options) => { flights.push({frames, options}); return {cancel() {cancelled++;}, finished: Promise.resolve()}; };
w.navigator.vibrate = () => { vibrations++; return true; };
w.CONTINUUM = {Storage: w.localStorage, effectPrefs: () => ({haptics: true})};
w.eval(read('effects.js')); w.eval(read('chronicle-owl.js'));
const CT = w.CONTINUUM;
const mount = screen => { app.innerHTML = '<div class="shell"><button data-action="select-card">Carta</button><button data-quick="slot">Hueco</button></div>'; CT.Companion.mount(app, screen); };
const owl = () => app.querySelector('.cronista');
mount('home'); assert.equal(owl(), null);
mount('solo'); const original = owl(); assert.ok(original.querySelector('.cronista-sprite'));
app.querySelector('[data-action="select-card"]').click(); assert.equal(owl().dataset.mood, 'thinking');
app.querySelector('[data-quick="slot"]').click(); assert.equal(owl().dataset.mood, 'writing');
const beforeFeedback = vibrations;
CT.Effects.feedback(true); mount('solo'); assert.equal(owl(), original); assert.equal(owl().dataset.mood, 'success');
CT.Effects.feedback(true); CT.Effects.feedback(true); assert.equal(owl().dataset.mood, 'streak');
assert.ok(flights.at(-1).frames.some(frame => frame.transform.includes('-34px')), 'la racha despega');
assert.ok(owl().classList.contains('cronista-reacting'));
const oldFlights = flights.length;
reduced = true; CT.Effects.feedback(true); assert.equal(flights.length, oldFlights, 'reducir movimiento evita los vuelos');
reduced = false;
CT.Effects.feedback(false); assert.equal(owl().dataset.mood, 'failure');
CT.Effects.feedback(true); assert.equal(owl().dataset.mood, 'success'); assert.equal(vibrations - beforeFeedback, 6);
const modal = w.document.createElement('div'); modal.innerHTML = '<div class="reveal">1640</div>'; app.append(modal);
CT.Companion.reveal(modal); assert.equal(modal.querySelector('.cronista'), original);
mount('pass'); assert.equal(owl().dataset.mood, 'turn');
mount('winner'); assert.equal(owl().dataset.mood, 'finished');
mount('home'); assert.equal(owl(), null);
assert.ok(cancelled > 0, 'navegar cancela los vuelos activos');
mount('quick-game'); CT.Companion.roundEnd(true); assert.equal(owl().dataset.mood, 'finished');
CT.Companion.roundEnd(false); assert.equal(owl().dataset.mood, 'turn');
owl().querySelector('[data-cronista-toggle]').click(); assert.ok(owl().classList.contains('cronista-collapsed'));
mount('solo'); assert.equal(owl().querySelector('[data-cronista-toggle]').getAttribute('aria-expanded'), 'false');
assert.equal(w.localStorage.getItem('continuum-cronista-v1'), 'hidden');
owl().querySelector('[data-cronista-toggle]').click(); assert.equal(w.localStorage.getItem('continuum-cronista-v1'), 'visible');
owl().querySelector('[data-cronista-greet]').click(); assert.equal(owl().dataset.mood, 'greeting');
CT.Companion.mount(app, 'solo'); assert.equal(app.querySelectorAll('.cronista').length, 1);
assert.match(read('chronicle-owl.css'), /prefers-reduced-motion: reduce/);
dom.window.close();
console.log('Cronista: reacciones, racha, repintado, diálogos, final, preferencia y vibración OK.');
