import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {doc,getDoc,setDoc} from 'firebase/firestore';
import {createService,firestoreStore} from '../server/service.mjs';
if(!process.env.FIRESTORE_EMULATOR_HOST)throw Error('Solo se permite ejecutar esta prueba contra el emulador');
const projectId='demo-competicion',uid='player001',other='player002',matchId='match0001';
const env=await initializeTestEnvironment({projectId,firestore:{rules:fs.readFileSync(new URL('../server/firestore.rules',import.meta.url),'utf8')}});
const app=initializeApp({projectId},'competicion-tests'),db=getFirestore(app);
try {
 await env.clearFirestore();
 let time=Date.now();
 const execute=createService({store:firestoreStore(db),catalogs:{test:Array.from({length:40},(_,i)=>({id:i+1,value:i+1}))},now:()=>time});
 const command={type:'create',catalog:'test'};
 const created=await execute({uid,matchId,requestId:'create001',command});
 assert.deepEqual(await execute({uid,matchId,requestId:'create001',command}),created);
 await assert.rejects(execute({uid,matchId:'match002',requestId:'create001',command}),/IDEMPOTENCY_CONFLICT/);
 await assert.rejects(execute({uid,matchId:'match003',requestId:'create002',command}),/RATE_LIMIT/);
 await execute({uid:other,matchId,requestId:'join0001',command:{type:'join',version:0}});
 await execute({uid,matchId,requestId:'start001',command:{type:'start',version:1}});
 const me=env.authenticatedContext(uid).firestore(),them=env.authenticatedContext(other).firestore(),anon=env.unauthenticatedContext().firestore();
 await assertSucceeds(getDoc(doc(me,`matches/${matchId}`)));
 await assertSucceeds(getDoc(doc(me,`matches/${matchId}/private/${uid}`)));
 await assertFails(getDoc(doc(them,`matches/${matchId}/private/${uid}`)));
 await assertFails(getDoc(doc(me,`matchSecrets/${matchId}`)));
 await assertFails(getDoc(doc(anon,`matches/${matchId}`)));
 await assertFails(setDoc(doc(me,`matchResults/${matchId}`),{winners:[uid]}));
 await assertFails(setDoc(doc(me,`matches/${matchId}`),{version:999}));
 const state=(await db.doc(`matchSecrets/${matchId}`).get()).data(),cardId=state.players[uid].hand[0];
 const action={type:'play',cardId,index:0,version:2};
 const race=await Promise.allSettled(['play0001','play0002'].map(requestId=>execute({uid,matchId,requestId,command:action})));
 assert.equal(race.filter(r=>r.status==='fulfilled').length,1);
 assert.equal((await db.doc(`matchSecrets/${matchId}`).get()).data().version,3);
 const winner=race.findIndex(r=>r.status==='fulfilled');
 assert.deepEqual(await execute({uid,matchId,requestId:['play0001','play0002'][winner],command:action}),race[winner].value);
 await assert.rejects(execute({uid,matchId,requestId:['play0001','play0002'][winner],command:{...action,index:1}}),/IDEMPOTENCY_CONFLICT/);
 await db.doc(`matchQuotas/${uid}`).set({windowStart:time,count:60,lastCreatedAt:time});
 await assert.rejects(execute({uid,matchId,requestId:'finish01',command:{type:'endTurn',version:3}}),/RATE_LIMIT/);
 time+=60001;
 await execute({uid,matchId,requestId:'finish01',command:{type:'endTurn',version:3}});
 assert.equal((await db.doc(`matches/${matchId}`).get()).data().expireAt.toMillis(),created.public.expiresAt);
 const finalState=(await db.doc(`matchSecrets/${matchId}`).get()).data();
 finalState.discard.push(...finalState.players[uid].hand);finalState.players[uid].hand=[];
 finalState.phase='reveal';finalState.turnsInRound=1;
 await db.doc(`matchSecrets/${matchId}`).set(finalState);
 const finished=await execute({uid:other,matchId,requestId:'finish02',command:{type:'endTurn',version:4}});
 assert.deepEqual(finished.public.winners,[uid]);
 const result=await assertSucceeds(getDoc(doc(me,`matchResults/${matchId}`)));
 assert.equal(result.data().version,5);assert.equal(result.data().catalogHash,created.public.catalogHash);
 await assertFails(setDoc(doc(them,`matchResults/${matchId}`),{winners:[other]}));
 await assertFails(getDoc(doc(env.authenticatedContext('outsider0').firestore(),`matchResults/${matchId}`)));
 console.log('Servidor en Firestore: privacidad, escrituras denegadas, carrera real, reintento y cuotas: OK');
}finally{await db.terminate();await deleteApp(app);await env.cleanup();}
