import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const dom=new JSDOM('<main id="app" data-screen="solo"><div class="shell"><div class="timeline"><article class="timeline-card" data-id="1"><div class="card-visual"></div></article></div></div></main>',{runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window, app=w.document.querySelector('#app');
let stamps=0, followed=0, reduced=false;
w.matchMedia=()=>({matches:reduced});
w.CONTINUUM={Effects:{stamp(){stamps++;}}};
w.HTMLElement.prototype.animate=()=>({finished:Promise.resolve(),cancel(){}});
for(const name of ['a11y.js','immersion.js'])w.eval(fs.readFileSync(new URL('../'+name,import.meta.url),'utf8'));
const card=app.querySelector('.timeline-card');
w.CONTINUUM.dealIn([card],{delay:1000,seguir(){followed++;}});
assert.equal(card.style.visibility,'hidden');assert.equal(app.querySelector('.shell').inert,true);
await new Promise(r=>setTimeout(r,500));assert.equal(followed,0,'medio segundo después sigue esperando');
await new Promise(r=>setTimeout(r,550));assert.equal(followed,1);assert.equal(card.style.visibility,'');assert.equal(app.querySelector('.shell').inert,false);
w.CONTINUUM.dealIn([card],{delay:1000,seguir(){followed++;}});
w.CONTINUUM.paint(app,'<section class="pass-screen"><div class="panel"><h1>Resultado</h1><div class="logros-nuevos">Primer acierto</div></div></section>','solo-end');
assert.ok(app.querySelector('.atlas-final-fan .timeline-card'));
assert.ok(app.querySelector('.atlas-final-page .logros-nuevos'));
assert.equal(app.querySelector('.atlas-final-fan').getAttribute('aria-hidden'),'true');
await new Promise(r=>setTimeout(r,1050));assert.equal(followed,1,'navegar cancela el reparto pendiente');
const modal=w.document.createElement('div');modal.innerHTML='<div class="reveal"><div class="year">1986</div></div>';app.append(modal);
w.CONTINUUM.UI.reveal(modal);const year=modal.querySelector('.year');assert.ok(year.classList.contains('date-ink'));
const event=new w.Event('animationend');Object.defineProperty(event,'animationName',{value:'date-ink-stamp'});year.dispatchEvent(event);year.dispatchEvent(event);assert.equal(stamps,1,'un solo sello por revelado');
reduced=true;year.classList.remove('date-ink');w.CONTINUUM.UI.reveal(modal);assert.equal(year.classList.contains('date-ink'),false);
dom.window.close();console.log('WOW: espera IA, cancelación, abanico, logros, sello único y movimiento reducido OK.');
